dlang/dlang.org

- spec/expression.dd
Make the definition more precise.
The idea that the struct holes are filled with 0 is not tenable anymore:
1. it's not compatible with the C/C++ ABI
2. it has efficiency issues
3. it interferes with struct slicing
> rewrite section on struct equality comparison

- spec/ddoc.dd
Add some undocumented macros.
That is used by default theme of dmd.
https://github.com/dlang/dmd/blob/master/res/default_ddoc_theme.ddoc#L781
source:
https://github.com/dlang/dmd/blob/master/src/dmd/doc.d#L3296
> [spec] Add undocumented macros

- spec/lex.dd
We can remove typedef keyword from the specification too.
> [spec] Remove typedef from specification

- spec/function.dd
Documenting how function pointers can be converted to delegates, to clarify that no function overloads are necessary that replace delegates with function arguments. It complements the previous paragraph that shows that delegates can be initialized referencing any function, but they cannot be assigned like that; `toDelegate` fills that gap.
Motivated by https://forum.dlang.org/post/jueqsawmegwznoycdmjy@forum.dlang.org
> Add reference to `toDelegate` in the spec.

- spec/garbage.dd
documentation for https://github.com/dlang/druntime/pull/1924
> document open GC registry

- spec/function.dd
> document ref-return-scope function parameters

- spec/statement.dd
This brings the spec in line with the behavior of the implementation.
> Mark CatchParameter's Identifier as optional

- spec/ddoc.dd
As indicated on the old link : [obsolete](https://wiki.dlang.org/Community:Open_Source_Projects)
> update a link to an obsolete wiki page

- download.dd
Download page points to [`dlanguage/dmd`](https://hub.docker.com/r/dlanguage/dmd), but it's not maintained for about 10 months.  [`dlang2/dmd-ubuntu`](https://hub.docker.com/r/dlang2/dmd-ubuntu) by @wilzbach is suitable for most of users.  See wilzbach/dlang-docker#5
> Change Docker URL from dlanguage/dmd to dlang2/dmd-ubuntu

- spec/template.dd
This mainly affects template alias examples.
Also:
* Fix use of `std.string.stringOf`, which doesn't seem to exist. Changed to std.conv.text.
* Add implicit template nesting subheading to link to.
* Tweak nested template limitation subheading.
> [template.dd] Use better symbol names in examples; add local name alias example

- spec/expression.dd
> Add definition of full expression

- spec/template.dd
* Use better template parameter names.
* Tweak same instantiation arguments example.
* Add links to aggregate and function template sections.
* Add subheading for `TCopy.copy` example (not related to paragraph above it).
> [template.dd] Tweak examples

- spec/function.dd
Default arguments were incompletely specified.
> Function Default Parameters are underspecified

- spec/const3.dd
- spec/function.dd
This would solidify my preferred interpretation of `@trusted` in the spec. Others have disagreed with me on what `@trusted` should mean exactly, so this might be controversial.
> spec: close a loophole in definition of `@trusted`

- spec/arrays.dd
Remove ambiguity in rectangular array example and stress that dimensions and indices are in reverse order of each other. 
I keep making the mistake of giving the dimensions in the wrong order. I think ordering is confusing and different from other languages, so deserve a prominent reminder.
> Dimensions and indices are in reverse order.

- foundation/donate.dd
> Link users to the OpenCollective main page

- spec/expression.dd
This formalizes behavior already existing in the compiler. It simplifies the rvalue ref DIP.
> Improve order of evaluation spec, add lifetime of temporaries spec

- install.dd
The `--active` option is incorrect, it is actually `--activate`.
> Correct install options for install.sh

- glossary.dd
- spec/const3.dd
- spec/function.dd
Makes other topics easier to discuss (such as matching rules for function overloading).
> Introduce term qualifier-convertible

- download.dd
As presented in my DConf 2019 lightning talk, there is a big discrepancy in usage between the DMD and DUB snap packages, and LDC.  One might well assume that this is because the first two are listed on the downoad page but LDC is not.
This patch corrects the discrepancy, and splits out the install commands into separate lines with helpful comments.
> Add LDC to list of snap packages available to download

- spec/expression.dd
- spec/traits.dd
This PR documents the language changes in https://github.com/dlang/dmd/pull/5290.
> Document __traits(isModule) and __traits(isPackage)

- spec/contracts.dd
This gives this for now `https://dlang.org/spec/expression.html#%20%20%20%20%20%20%20%20AssertExpression`
b/c obviously macros are not aware of the indentation used in the source document.
> fix broken link due to macro split on multiple lines

- spec/struct.dd
A previous commit (823d8a4) clarified that destructors are called upon assignment to an initialized object. In doing so it spliced the sentence in a very unnatural way. I've attempted to correct the sentence grammar while preserving the semantics.
It's not clear to me if calling the dtor on assignment to initialized objects is necessary, or if it's just an optional thing the default opAssign is meant to do. I'd appreciate clarification on this.
> Fix confusing grammar in Assignment Overload spec

- spec/arrays.dd
From the language spec it appears as if there is no way to create an array and initialise its elements to something other than the element init value without having the values initialised twice.
> Add link to uninitializedArray in arrays

- js/run_examples.js
Issue in focus: https://issues.dlang.org/show_bug.cgi?id=19944
The appending of `import std.stdio: write, writeln, writef, writefln;` to the code conflicts when trying to access `std.file.write`
Before:
After:
> Fixes 19944 - Unit test failures in std.file

- download.dd
Trailing whitespace caused the link to be broken in some Firefox versions.
> download.dd: Fix local DMD link

- spec/iasm.dd
This commits adds the new grammar allowing basic type properties as iasm operand (https://github.com/dlang/dmd/pull/10069) and specify what kind of dotted expressions are accepted.
> Specify the dotted expressions allowed as iasm operand

- spec/operatoroverloading.dd
> For backward compatibility [...] the rewrites `a.opSliceUnary!(op)(a, i, j)` [...] are tried instead, respectively.
To:
> For backward compatibility [...] the rewrites `a.opSliceUnary!(op)(i, j)` [note: without `a` in parameter list] [...] are tried instead, respectively.
The compiler does not do the former rewrite, and looks like a small error.
> Fix typo in code

- spec/attribute.dd
Is allowed by spec since a few months but is fixed only since https://github.com/dlang/dmd/pull/10144 so now the use can be encouraged.
> update example of UDA using the "alias equal traits" syntax

- orgs-using-d.dd
While the current order seems reasonable when arguing that "Autonomous Intelligent Driving" may be abbreviated by "AID", then also "ArabiaWeather" -> "AW" and "Symmetry Investments" -> "SI" would need to sit in different positions.
> Fix alphabetic order

- spec/expression.dd
There already is #2578 attempting to fix it, but that is stalled because it also attempts to describe shift amounts out of range as undefined behavior, which is not agreed upon. In the mean time the blatant error in the spec persists, so this PR addresses only that so it can be merged sooner.
> fix Issue 19402 - specs for promotion rule of shift exp is wrong (without anything else)

- dlang.org.ddoc
Old PR: https://github.com/dlang/dlang.org/pull/2539
Old reverted in: https://github.com/dlang/dlang.org/pull/2541
I've recreated this PR after this topic have been brought up again in our Discord server.
We still think that it would be a good idea to have a more official and visible Discord server for those that prefer Discord over IRC. As brought up in the other PR we are willing to make changes to the server, if requested. Difference from the last PR is that it now says "Community Discord" instead of just "Discord".
**This should not be merged without further discussion and approval of multiple people.**
---
Text from the old PR:
Adds the Discord chat link for "D Language Code Club" (previously known as "D Code Club" and "Wilds Code Club") to the Community section. (in the following …
> Add community Discord join link to the community section

- areas-of-d-usage.dd
- orgs-using-d.dd
The github repo for eBay's TSV Utilities was changed from `eBay/tsv-utils-dlang` to `eBay/tsv-utils` last year. This PR updates the url references to point to the new location.
> Update the eBay tsv-utils repo URL to the new name.

- spec/hash-map.dd
"initialization of immutable variable from static this is deprecated"
> [Documentation example] Fix deprecation issue

- spec/traits.dd
Companion to https://github.com/dlang/dmd/pull/10528
> document hasCopyConstructor and hasPostblit traits

- spec/lex.dd
unsigned longs if they don't fit in a signed long
Spec change corresponding to my dmd PR: https://github.com/dlang/dmd/pull/10607
> fix issue 19432 automatically interpret big int literals as 

- spec/interface.dd
This link from the Interfaces section of the spec is broken currently. If you've been to the correct link, your browser can silently fix it, and then hide the 'www.' prefix in the address bar to further confuse. Best to check with curl:
```
$ curl -I http://lunesu.com/uploads/ModernCOMProgramminginD.pdf
curl: (7) Failed to connect to lunesu.com port 80: Connection refused
$ curl -I http://www.lunesu.com/uploads/ModernCOMProgramminginD.pdf
HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: application/pdf
...
```
> (trivial) fix lunesu.com link by adding www.

- spec/enum.dd
Clarify that `.min / .max` are not the min/max values that the enum type can validly hold, but instead these are the min/max of the enum member values.
> Clarification of .min and .max properties of enums

- spec/function.dd
- casting to types without pointers (e.g. `cast(size_t) new int`) is already allowed in `@safe` code
- casting to `void*` is allowed in `@safe` if the corresponding dmd PR gets merged.
https://github.com/dlang/dmd/pull/10672
> Update `@safe` casting rules

- spec/hash-map.dd
Consider the following code:
```
struct A
{
string s;
}
void main()	
{
assert(A("foo".idup) in [A("foo".idup): 2]);
}
```
It is plain to see that this code can only succeed if structs automatically generate opEquals/toHash that walk the struct's fields and call opEquals/toHash recursively. However, the documentation currently asserts that hashmaps do not do this:
> If the _KeyType_ is a struct or union type, a default mechanism is used to compute the hash and comparisons of it based on the **binary data** within the struct value.
(emphasis mine)
That is, the documentation currently implies that hashmaps perform a "flat" comparison, when the two "foo" strings would require a "deep" comparison.
As can be seen by throwing this code into run.dlang.io, this code started working in either 2.065 …
> hashmap: document that structs automatically generate specialized opEquals/toHash that recurse over fields

- index.dd
This reverts commit 8c3e5ea9d334864477c526a5cdddabbfc1b3946b.
`buf[0 .. 1024 * 1024]` creates a `void[]`  (length 1024 * 1024) which is then casted to a `float[]` (length ((1024 * 1024)) / float.sizeof)
> Partially revert "Fix bug in code example"

- spec/template.dd
According to the spec, a template instantiation only refers to an eponymous member if that member's declaration includes all of the template's parameters. As of DMD v2.090.0, this is not the actual behavior of the implementation, as demonstrated by the following example:
```d
template foo(T)
{
// Does not include T
enum foo = 42;
}
// Passes, but should fail according to spec
static assert(foo!void == 42);
```
This change updates the spec to match the actual behavior of the compiler.
> Bring eponymous template spec in line with implementation

- articles/const-faq.dd
This article explains why D's `const` is the way it is.
But what this article does *not* answer -- and ought to, or at least provide a link to -- is why and how and *when* to use `const` and `immutable` (and `in` and `enum`!).
> English improvements + sexism fix etc

- spec/module.dd
1. What do lines 120/1 "If present, the ModuleDeclaration appears syntactically first in the source file" mean? Would something like "If present, the ModuleDeclaration must appear before any imports or code (but may be preceded by comments)." be clearer?
2. I would suggest adding a code comment to line 139: " // It is best to avoid -'s in file names".
3. I don't understand the para at lines 261-264 on scope searching.
4. In the static import section (lines 366+) should a distinction between compile-time and runtime be mentioned (if there is one)?
5. In the renamed imports section (lines 381+) some advice ought to be given as to when and why to use this -- or to recommend not to.
> Minor English improvements

- spec/expression.dd
Signed integers have wraparound semantics.
https://forum.dlang.org/thread/n23bo3$qe$1@digitalmars.com
@tgehr
> Clarify signed integer overflow by explicit example.

- deprecate.dd
The deprecation was reverted in DMD PR 10763.
> Clarify 'body' keyword deprecation

- spec/pragma.dd
```
It was implemented as part of DMD PR 7182 but never documented.
Note that significant fixes came later, e.g. DMD PR 10562.
```
Testing here because the docs don't build on OSX.
> Add documentation for pragma(crt_{con,de}structor)

- spec/expression.dd
It is ParameterWithAttributes or ParameterWithMemberAttributes that precedes '=>'
> Fix GLINKs in Lambda grammar

- spec/betterc.dd
- spec/interfaceToC.dd
Rewrote the section about calling `printf` to support its implementation https://github.com/dlang/dmd/pull/10812
> document printf format validation

- css/style.css
- index.dd
adds scroll bars to non-fitting output & to readonly code starting at 500px
before:
after:
> Improve front page for small screens

- spec/traits.dd
Spec says if the type's default initializer is all zero bits then true is returned, otherwise false.
void is neither.
> Add example `__traits(isZeroInit, void))`

- spec/cpp_interface.dd
The current compile line example does not works because the C++ sample code use std. The option -L-lstdc++ was missing in the compile line example, which is needed in order to compile the sample code.
> Added missing argument in compile command example

- dcompiler.dd
- windbg.dd
replace occurrences of link.exe with optlink.exe
complementing removal of windbg.exe from the Windows installation: https://github.com/dlang/installer/pull/423
> replace windbg.exe description with more recent debug options

- spec/version.dd
See https://github.com/dlang/dmd/pull/11094
> Add AVR version identifier to documentation

- foundation/about.dd
- foundation/donate.dd
The intro on the foundation/about page was a little out of date. And it's supposed to be mirrored on the foundation/donate page, too.
> Add GSOC 2019 to DLF intro

- spec/objc_interface.dd
Update all usage examples and text referring to `@selector` to explicitly import `core.attribute.selector`.
See https://github.com/dlang/druntime/pull/3108 for reasoning.
> Explicitly import `core.attribute.selector`

- posix.mak
I found duplicate release-schedule entries on the sitemap page.
However I'm not sure why this is added separately.
> Remove duplicated release-schedule entry from sitemap

- spec/function.dd
Expanded description of trusted functions to include the notion that such have a _safe interface_.
> function.dd: add notion of safe interface

- spec/class.dd
When running gdc 9.3.0:
```
decl.d:45:12: error: allocator decl.XClass.new first argument must be type size_t, not uint
```
> class allocator receives size_t not uint

- spec/class.dd
* Add subsection headings for easier reference, with anchors.
* Tweak wording for delegating constructors.
* Split out 'Implicit Base Class Construction' section from delegating constructors, as it's independent. Change order of paragraphs as implicit `super()` also applies to implicit `this()`. Explain that an implicit `super` call must match a base constructor.
> [class.dd] Improve long Constructors section and add subsection headings

- spec/class.dd
- spec/function.dd
The Objective-C method specifics (added in #2540) make it hard to read the docs for people not interested in Objective-C linkage. This moves the details to a subsection.
Also:
* Mention that member functions are also called methods (which is used in some places in class.dd already).
* 2 minor tweaks to surrounding class docs.
> [class.dd] Move Objective-C method specifics to subsection

- spec/class.dd
- spec/struct.dd
Similar to #2809 but for structs.
* Move 'Union Constructors' section before struct ctors, rather than in the middle of it.
* Tweak struct constructor docs, add subsection headings and anchors for easier browsing.
* Fix ctor Parameters and ParameterList links.
* Fix 'delegate constructor' -> 'delegating constructor'.
* Reparent some existing H2 sections as H3 subsections under 'Struct Constructors'.
* Move 2 general paragraphs for copy constructor to end of the main section (as subsections are more specific).
* Add link to copy constructors from legacy postblit section.
> Improve struct constructor docs, add subsections

- spec/version.dd
Fix INT -> Int capitalization.
Simplify foreach iota example.
Explain using double braces to create a scope with foreach.
> [spec/version.dd] Improve Static If, Static Foreach sections

- install.dd
Add the keyring update info, which is a continuous reoccurring confusion, see also https://forum.dlang.org/post/tmnixwomwogmgjopsjqp@forum.dlang.org
> adding keyring hint to the install.sh help page

- posix.mak
blocking https://github.com/dlang/dmd/pull/11269
> move res/ to src/dmd/res

- spec/function.dd
* Split the `ref` example from the `out` examples, and put it first.
* Briefly describe each.
* Tweak the `scope` description.
> [spec] Document ref and out parameters

- spec/attribute.dd
The grammar is missing the string-style `extern(C++, "a", "b")` declaration. The `ArgumentList` isn't quite right here as it allows a trailing comma but the current implementation in dmd does not. However, this seems more like a bug in dmd since it's inconsistent with the rest of the grammar.
> Update extern(C++) grammar to support string namespaces

- spec/function.dd
* Tweak existing wording
* Mention `@safe` & -dip1000 needed for enforcement
*Update:*
* Split existing `return ref` example.
> [spec/function.dd] Add scope parameter section

- spec/attribute.dd
The semantics were changed with https://github.com/dlang/dmd/pull/6754.
Resolves https://issues.dlang.org/show_bug.cgi?id=20754.
> Fix spec wrt. the align attribute

- spec/lex.dd
1. I've replaced "Aka" with "alias". If that's not wanted I still think "Aka" is wrong and should be replaced by something else.
2. On lines 549-550 it says you can write a named character entity like this: `\name`. But I tried doing: `auto x = "\euro";` and it gave an error.
3. It is a real pity that `__DATE__` uses a US-specific format rather than the universal ISO8601. I hope an `__ISODATE__` and an `__ISOTIMESTAMP__` are added to repair this.
4. I don't know what the explanation for `__EOF__` means. Would "Tells the scanner to stop at this point in the source." be a correct alternative?
5. This page's very last example has the string `"foo\bar"`. Shouldn't this be `r"foo\bar"` or `"foo\\bar"`? And if not, a reason ought to be given.
> Minor English improvements + notes below

- articles/regular-expression.dd
Links to stdlib pages in https://dlang.org/articles/regular-expression.html are all broken.
I assume they worked fine until d5a1bf90b3e7513499614fea8f41b90af72b0260 relocated the page under /articles/, which broke them as they are relative links.
To fix this I propose turning them into absolute links.
> Fix broken stdlib links in regexes article

- spec/function.dd
These attributes are checked since dlang/dmd#11135.
> Document allowed storage classes for ... varargs

- spec/traits.dd
Related bug fix_ https://github.com/dlang/dmd/pull/11373
> Improve specs for `__traits(isSame)` over two tuples

- spec/function.dd
> Not all functions return rvalues

- spec/abi.dd
See dlang/dmd#11474 and dlang/druntime#3183
> Add mangling specification for 'in' parameters

- download.dd
This change fixes the info tooltip from "Linux setup and usage information" to "FreeBSD setup and usage information".
Also fixes the url from https://dlang.org/dmd-linux.html to https://dlang.org/dmd-freebsd.html
> Fixing FreeBSD info link

- download.dd
- remove dropped FreeBSD-32 builds
- fix FreeBSD info links
- remove unmaintained nightly release channel
Also see https://dlang.org/changelog/2.094.0.html#ldc-built-releases.
> update download page

- spec/function.dd
Underline the difference between argument and parameter.
Split the first sentence between type constructors and storage classes.
Finally, add documentation on what `in` will means with `-preview=in`.
Waiting on dlang/dmd#11000
> Expand on function parameters documentation, add -preview=in

- spec/expression.dd
You can see [here](https://dlang.org/spec/expression.html#function_literals) that there's a bit of the grammar specification involving parameters, and then below the text in question there are examples of function parameters, so I'm pretty sure this was a mistake.
> Fix argument/parameter mixup in function literal documentation

- spec/property.dd
This makes the example compile.
> Typo in example.

- spec/function.dd
Also, switch them around so that they are consistent with the language in the text above.
> Remove white space in return ref scope

- acknowledgements.dd
Old link:
http://www.relisoft.com/
New link:
https://bartoszmilewski.com/
> Dead link to info about Bartosz Milewski

- spec/cpp_interface.dd
see also https://github.com/dlang/dmd/pull/11905
> Document issue 21340 - `extern(C++, (expression))` now accepts empty tuples

- spec/version.dd
I added `CRuntime_Newlib` version indentifier corresponded to newlib-supported runtimes.
Related to dlang/dmd#11930
> Add CRuntime_Newlib version identifier

- spec/function.dd
In the previous version, the function call foo(1L) matched both
A.foo(long) and B.foo(int), because the literal 1L can implicitly
convert to int via value range propagation (VRP). Using a long variable
instead of a literal causes it to match only A.foo(long), as intended.
> Fix inaccuracy in overload set example

- spec/struct.dd
The "implicit blitting" of the text can be read as "implicit calling of copy constructor", leading to incorrect meaning of the text.
> Improve the wording of struct copy ctor spec.

- spec/function.dd
Previously this was only stated in the example.
> State in language spec that null is a safe value

- spec/function.dd
instead of leaving such recommendations as part of the main text.
> function.dd: use BEST_PRACTICE and IMPLEMENTATION_DEFINED

- spec/spec.ddoc
Instead of them being ad-hoc, and allowing for custom styling of each. Also makes it clear that they are not formally part of the spec.
> add Ddoc spec macros RATIONALE and NOTE

- spec/ob.dd
`auto p = void` won't compile even with live value enforcement turned off
> Live Functions: Swap auto for int* where needed

- spec/function.dd
Remove half-baked description and forward the reader to the full description.
> remove redundant description of Function Templates

- spec/function.dd
1. Promoted two sections from `H4` to `H3` so they show up in the table of contents.
2. Use `NOTE` macro.
3. Don't confusingly use same name twice.
> Minor adjustment to Scope Parameters section

- spec/function.dd
Minor wording improvements. The clause at line 1166 was removed because it is incorrect.
> improve Function Overloading section

- spec/lex.dd
$(D \) does not render as the literal character "\", so the docs were displaying wrong; this change fixes that.
> $(D \) -> $(D \\) in EscapeSequence docs

- spec/function.dd
1. fix incomplete examples
2. use code quoting
3. remove out-of-place reference to `in`
> adjust Ref and Out Parameters section

- spec/function.dd
The BetterC main should be in all compilers, not implementation defined.
> Improve main() function description

- spec/function.dd
Mostly removing unnecessary verbiage.
> Improve Safe Aliasing section wording

- dlang.org.ddoc
- foundation/index.dd
- foundation/prman.dd
- posix.mak
This adds a new page to the web site documenting the responsibilities of the two new pull-request managers. It does not belong in the main menu (which is cluttered enough) and is accessible from the Foundation page.
> Add PR manager responsibilities page

- download.dd
- js/platform-downloads.js
Companion PR: dlang/downloads.dlang.org#6
> Fix 21292: Link directly to https s3 downloads

- spec/function.dd
The information in this section was disorganized and scattered about. Several topics were covered redundantly. Best practices, undefined behavior, and implementation defined practices were identified. Removed glib comparisons to other languages. More precise definitions of terms.
> rewrote section on Pure Functions

- posix.mak
This can be merged once 2.093 has been released.
See https://github.com/dlang/dlang.org/pull/2821 for details.
> [2.093] Remove duplicate res path for the stable ddox build

- dstyle.dd
It is a D Style proposal. The suggestion is to state explicitly how continuation lines should be indented.
One logical line can be written as two or more lines (so called line continuation or line wrapping). One example is a long argument list, that can be made more readable if written in multiple lines. And I propose to use two indentation levels (8 spaces) for line wrapping.
So:
```d
my_func_name(arg1,
arg2);
```
instead of
```d
my_func_name(arg1,
arg2);
```
- This is how dfmt formats the code and it can't be configured: https://github.com/dlang-community/dfmt/issues/257
- Phobos or at least some Phobos maintainers seem to enforce this guideline (e.g. see the remarks to this PR: https://github.com/dlang/phobos/pull/7105)
> Indent continuation lines with 2 indentations

- spec/attribute.dd
- spec/function.dd
Having `nothrow` and `pure` appearing twice for function attributes should be tightened up.
> add FunctionAttributeKwd to grammar to factor out redundancy

- dstyle.dd
Reverts dlang/dlang.org#2766
Motivation:
Changes to the DStyle guide can't be made solely based on one's preference. Only changes match the currently established practices can be "codified" via a lightly reviewed PR. Otherwise DStyle changes need the consensus of the majority of active contributors.
That said, such changes don't need a DIP, since this is not change that affects any users of the language, only the contributors.
> Revert "Indent continuation lines with 2 indentations"

- spec/function.dd
1. Fixed enumeration of storage classes to match order entries in table.
2. Moved `in` documentation to its own paragraph.
3. Better example, more thorough explanation.
> improve Parameter Storage Classes section

- spec/declaration.dd
Add missing documentation for:
```
alias AliasSeq(T...) = T;
```
form of template declarations.
> document Alias Template Declarations

- spec/declaration.dd
Reverts dlang/dlang.org#2780 because it's already there in https://dlang.org/spec/template.html#alias-template
> Revert "document Alias Template Declarations"

- spec/pragma.dd
Putting `$(P ...)` inside an IMPLEMENTATION_DEFINED macro causes it to fail to format properly.
> Improve pragma lib and pragma linkerDirective

- spec/contracts.dd
as it's redundant with the much better written https://dlang.org/spec/expression.html#AssertExpression
> contracts.dd: remove outdated assert() section

- spec/pragma.dd
There were a lot of problems with the section with imprecise language and missing information. Also filed these bug reports as a result of investigating how it actually worked (and didn't):
https://issues.dlang.org/show_bug.cgi?id=21620
https://issues.dlang.org/show_bug.cgi?id=21621
https://issues.dlang.org/show_bug.cgi?id=21622
https://issues.dlang.org/show_bug.cgi?id=21623
The crt_destructor section should get the same treatment next.
> rewrite pragma(crt_constructor) section

- spec/function.dd
Saw #2916 and realize it needed some tiny adjustments w.r.t. `-preview=in`.
> Slightly rephrase and actualize -preview=in section

- spec/function.dd
> Add -preview=shortenedMethods to language spec

- spec/function.dd
Use more formal language. Mark IMPLEMENTATION_DEFINED and BEST_PRACTICE sections. Be more exact in specifying the behavior.
> improve Function Contracts section

- spec/pragma.dd
- spec/statement.dd
Moved the grammar for pragmas to all be in pragma.dd.
Clarified some of the prose.
> Improve pragma grammar and links

- spec/betterc.dd
- spec/expression.dd
- spec/function.dd
- spec/traits.dd
- spec/type.dd
These sections duplicated much of the grammar and text, implying Function Literals are somehow different from Lambdas, when in fact the only difference is slightly shorter syntax. The PR merges them into one grammar.
> merge Function Literals and Lambda sections

- spec/expression.dd
- spec/lex.dd
This reverts commit afd448739c8650f6d849197fc874c3e22ba0587c.
PR https://github.com/dlang/dlang.org/pull/2960 comes as a companion to DMD https://github.com/dlang/dmd/pull/12252 which hasn't been merged and is still under discussion.
> Revert "spec: add `__MANGLED_FUNCTION__` special keyword"

- spec/arrays.dd
- spec/const3.dd
- spec/cpp_interface.dd
- spec/ddoc.dd
- spec/enum.dd
- spec/expression.dd
- spec/garbage.dd
- spec/interfaceToC.dd
- spec/module.dd
- spec/operatoroverloading.dd
- spec/template.dd
I'm sure you will agree that if you remove you from the text, you will find that the text almost always is shorter and you can see it reads better without it.
> exorcise the word 'you' from the spec

- spec/declaration.dd
Add subheadings for clarity and easier navigation.
Don't call static arrays just 'arrays'.
> spec: Improve declaration syntax section

- spec/type.dd
The new heading groups 4 subheadings together for easier navigation.
GLINK can only be used for relative links.
> spec/type.dd: Fix GLINKs, add Type Conversions heading

- spec/declaration.dd
- spec/type.dd
It's kinda where one would expect to find it.
Didn't change anything else other than adjusting links.
> move Type grammar from declaration.dd to type.dd

- spec/type.dd
The new heading groups 3 subheadings together for easier navigation.
> spec: Add Built-in Type Aliases heading

- spec/version.dd
This is added by the compiler when `-fPIE` is seen on the command-line.
> spec/version.dd: Document the D_PIE predefined version

- deprecate.dd
- spec/expression.dd
- spec/lex.dd
- spec/traits.dd
- spec/type.dd
> Add notes in the spec that complex and imaginary types are deprecated

- spec/expression.dd
so that it matches order of evaluation
> Corrected grammar spec of commaExpression 

- spec/float.dd
This file is very old - the use of the term "internal temporary" could potentially predate the term "CTFE" (Discussion suggests the dates could line up?) so working out what was originally referred to is slightly difficult (Regardless, the - removed - detail as to performance is not really true outside extremely scalar code anyway). I didn't remove the note about x87 (yet, haven't checked whether it actually does this or not at runtime)
> First pass at bringing float.dd up to scratch

- spec/ddoc.dd
Python link was also dead, linked to rust instead.
> Fix Issue 21869 - Invalid hyperlink to doxygen

- spec/expression.dd
D Grammar defines that a `PrimaryExpression` can be a `NewExpressionWithArgs` (instead of just a `NewExpression`). The arguments, however, are optional: `new Class` (without arguments) is a valid expression. The implementation in parse.d also has a single function `parseNewExp` that allows the arguments to be missing.
While `NewExpressionWithArgs` is just wrong for `PrimaryExpression`, I removed `NewExpressionWithArgs` because it has no further use.
> Remove inappropriate NewExpressionWithArgs

- spec/statement.dd
Fix a minor typo in the spec.
The code did compile and worked,
but produced the wrong output before.
> statement.dd: Fix typo, use writefln properly

- spec/struct.dd
Make constructors and comments consistent.
> struct.dd: improve formating of the example

- spec/expression.dd
Pull request #2339 added the grammar rule
FunctionLiteralBody:
SpecifiedFunctionBody
to function.dd, but did not remove the outdated grammar rule
FunctionLiteralBody:
BlockStatement
FunctionContractsopt BodyStatement
from expression.dd. The BodyStatement is gone (dead link), so I propose to change the links to FunctionLiteralBody to point to function.dd.
(Alternatively, the grammar rule for FunctionLiteralBody could be moved from function.dd to expression.dd.)
> Remove outdated definition of FunctionLiteralBody

- spec/expression.dd
Now that Function Literal and Lambda sections have been merged, I took another pass through it to:
1. add necessary examples, such as explaining the role of `ref` in the grammar
2. make the prose more precise
3. draw more equivalences between the various ways to write a function literal
4. point out when function literals become templates
5. show use of function literals as template alias parameters
6. remove some redundant text
7. move clarifications to NOTE
8. explain the peculiar omission of `x { return statement; }` syntax
> improve Function Literal section

- spec/version.dd
This results in the rest of the text on that line out of the table.
> [spec/version.dd] fix comma that should be escaped

- dlang.org.ddoc
- dpl-docs/views/layout.dt
- index.dd
Following most open-source projects, we are moving our official IRC presence from Freenode to Libera.Chat.
Some users have chosen to move to OFTC instead. It is not mentioned here but I updated https://wiki.dlang.org/ to mention OFTC as well.
> Update IRC channel (from Freenode to Libera.Chat)

- spec/errors.dd
- spec/function.dd
- spec/lex.dd
- spec/statement.dd
I wrote a DDoc parser (to extract the grammar) and it choked on the invalid DDoc constructs fixed in this commit.
> spec: DDoc syntax fixes

- spec/cpp_interface.dd
Real mangling of `long` does not currently match the spec. According to a comment at https://github.com/dlang/druntime/pull/3400 , it's the spec that should change.
> Fixed wrong info about `long` C++ mangling

- changelog/pending.ddoc
The original nightlies are no longer maintaned and the current nightlies
are uploaded to GitHub.
---
Unless someone is willing / able to come up with a way to mirror these builds to the website.
> Update nightlies link to refer to the GitHub releases

- spec/declaration.dd
Implementation: https://github.com/dlang/dmd/pull/11846/
> spec: add AliasReassignment

- spec/declaration.dd
> spec/declaration.dd: Update grammar syntax in AliasAssign / AliasReassignment

- spec/iasm.dd
The full set of supported opcodes is probably an implementation detail, so we should at least include definitions for the syntax used to lex them.
> spec/iasm.dd: Add definition for Opcode

- spec/function.dd
Match `ArgumentList` and DMD behavior.
> spec/function.dd: Allow trailing comma in ParameterList

- spec/declaration.dd
According to DMD, @-attributes may occur wherever storage classes are parsed (see `Parser.parseStorageClasses`).
> spec/declaration.dd: Add AtAttribute to StorageClass

- spec/lex.dd
- The optional BOM is mentioned in prose, but not specified.
- Describe the shebang line, which was hitherto undocumented.
The described syntax is what the current DMD implementation does.
- Define that empty source files are valid.
> spec/lex.dd: Describe the source file layout within the grammar

- spec/function.dd
Function types may be `@safe` etc.
> spec/function.dd: Add AtAttribute to FunctionAttribute

- spec/lex.dd
This token is explicitly supported by DMD in this context.
> spec/lex.dd: Allow __LINE__ in #line SpecialTokenSequence

- spec/class.dd
The definitions are identical, and therefore indistinguishable.
> spec/class.dd: Merge SuperClass with Interface

- spec/class.dd
`$(D ;)` is already a possible `FunctionBody` (as `MissingFunctionBody`).
> spec: Remove definitions redundant with MissingFunctionBody

- spec/lex.dd
Use the same approach as `NestingBlockComment`.
NB: `Tokens` and `Token` are not used anywhere in the grammar any more, and are therefore only illustrative.
> spec/lex.dd: Describe TokenString within the grammar

- spec/statement.dd
A `{ }` block after a label does always introduce a scope.
They are also syntactically identical, and therefore indistinguishable.
> spec/statement.dd: Remove PSSEMI from LabeledStatement

- spec/function.dd
const / shared / etc. are allowed before "...", but not required.
> spec/function.dd: Make VariadicArgumentsAttributes optional in ParameterList

- spec/module.dd
- spec/statement.dd
- Semantically indicate that the various occurrences of `$(D ;)` all mean the same thing
- Add explicit counterpart to e.g. `NonEmptyStatement`
- Avoiding mixing leaf and non-leaf nodes makes the grammar more structured in general.
> spec: Add EmptyDeclaration and EmptyStatement

- spec/function.dd
Return-ref parameters don't need to specifically be declared with the exact token sequence `return ref`. For example, `ref return` also works, as does e.g. `return scope int* a`.
> spec/function.dd: Remove "ref" from "return ref"

- spec/iasm.dd
```
The root definition (GccAsmStatement) is purposefully not referred to
anywhere from the rest of the grammar. This allows implementations
(grammar consumers) to opt-in by replacing or augmenting AsmStatement
with GccAsmStatement as appropriate.
```
Adapted from here: https://github.com/CyberShadow/tree-sitter-d/issues/3#issuecomment-873658827
Draft because it seems there still is some code apparently using GCC assembler syntax which does not conform to the grammar added here so far: https://github.com/CyberShadow/tree-sitter-d/issues/3#issuecomment-877692161
> spec/iasm.dd: Add the GDC inline assembler grammar

- spec/struct.dd
> spec/struct.dd: Move incorrect initialization of union to SPEC_RUNNABLE_EXAMPLE_FAIL

- spec/class.dd
This was removed from the parser in [2020-01](https://github.com/dlang/dmd/pull/10727) by @Geod24.
FYI @CyberShadow in-case you were using this in your tree-sitter grammar.
> Remove documentation on class deallocators

- spec/importc.dd
Put a stake in the ground on this so we can add `__IMPORTC__` later.
> ImportC: all about __IMPORTC__ predefined macro

- spec/intro.dd
This used to be specified, but seems to have disappeared.
> specify two's complement math and IEEE-754

- spec/iasm.dd
After adding [the GDC inline assembler grammar](https://github.com/dlang/dlang.org/pull/3062) to [tree-sitter-d](https://github.com/CyberShadow/tree-sitter-d), I noticed an unexpected regression in [parsing the top community D projects](https://github.com/CyberShadow/tree-sitter-d/issues/3): [the following code](https://github.com/dlang-community/dfmt/blob/f6490b31c969e7ec07f57958c2104a2479060b75/tests/issue0251.d#L3-L3), which previously parsed successfully under the grammar with just the DMD inline assembler syntax, now failed to parse.
My first thought was that it must be a bug in tree-sitter. How could adding an additional alternative definition for a rule result in the old definition not working any more? That made no sense. However, DustMite-ing the tree-sitter-d grammar revealed …
> spec/iasm.dd: Improve definition of Opcode

- spec/traits.dd
> spec: traits: add support for function calls when using getParameterStorageClasses

- articles/d-floating-point.dd
- articles/hijack.dd
- dstyle.dd
- foundation/donate.dd
- spec/declaration.dd
- spec/expression.dd
- spec/importc.dd
- spec/interfaceToC.dd
With the help of '(\b.+) \1\b' regex, it was found some incorrect
wording on the spec such as duplicate words or typos such as missing
punctuation.
> treewide: fix duplicate words and typos

- spec/operatoroverloading.dd
`body` is a deprecated keyword, replaced with `do`
> Remove `body` in operator overloading example

- index.dd
body is deprecated and text.txt is not readable on run.dlang.io which is suboptimal
> Update broken examples

- spec/function.dd
Before it said out was for input/output
> fix ordering of "respectively" for in, out, ref

- posix.mak
The addition of the book builder introduced the dependency on a `dmd` / `rdmd` found on the path. This broke multiple CI's:
1. DMD nightlies are built with ldc and hence have no `dmd` installed by default
2. Installer CI has no system-wide rdmd installation
---
```
Use STABLE_DMD building/running book/build.d
Relying on the `STABLE_DMD` release ensures that the book can be built
even if there is no `rdmd` / `dmd` found on the path.
```
> Fix portability of the book builder

- posix.mak
Avoids issues when `GENERATED` resolves to a relative path, e.g. the default.
This adresses the remaining issue outlined in https://github.com/dlang/installer/pull/489#issuecomment-980709464
CC @maxhaton @lionello
> posix.mak: Explicitly call stable rdmd using absolute path

- book/build.d
- posix.mak
Also disable -revert=markdown for the older compiler.
---
Sorry for the PR spam. Apparently messed up with my test setup for these changes s.t. it still found another dmd...
> Ensure that book builder uses the stable dmd algongside rdmd

- spec/declaration.dd
Closing the issue by adding clarifications in the spec. The behaviour mentioned in the issue actually seems reasonable (so it's not a bug), but the docs don't mention this anywhere.
> Fix Issue 18960 - Function parameter requires name with default value 

- spec/abi.dd
Related to the issue #20565.
---
This is needed in order for the LLVM demangler be in sync with the compiler's implementation. See https://reviews.llvm.org/D111415 .
CC @Geod24
> spec: abi: add function-local parent symbols to the mangling grammar

- download.dd
Links to my repo that might be useful for a Nix user who wants to use a different version of DMD compared to what happens to be on NixPkgs repository.
Same as #3133 but this time based on newest master
> Added link to github.com/dukc/oldDDerivations

- spec/function.dd
Reverts dlang/dlang.org#3123
I thought the dmd PR was merged.
> Revert "Fix Issue 22518 - return without scope/ref not specified"

- spec/expression.dd
As per @adamdruppe 's [explanation](https://github.com/dlang/dmd/pull/13387#issuecomment-986288394), I edited the description for `is ( Type Identifier : TypeSpecialization )` in the spec to match `is ( Type : TypeSpecialization )`.
> fix Issue 19136 - is expressions don't work as documented

- spec/lex.dd
Since built-in complex numbers are deprecated now.
> Deprecate complex number keywords

- spec/traits.dd
The new text is based on the error message produced by DMD when
__traits(allMembers) is passed an invalid argument.
> Fix inaccurate __traits(allMembers) spec

- spec/traits.dd
For future reference the Oxford comma is the desired form - this commit message left here so there's something to search for.
> Use an Oxford comma in the allMembers spec

- download.dd
As it says on the tin, OpenBSD users just need to type `pkg_add dub` to get dub these days.
> OpenBSD: the dub package is just named dub now

- spec/expression.dd
- spec/lex.dd
Remove section for bool literals, this info (and more) is already in lex.dd - add links to there.
Move *CharacterLiteral* paragraph to lex.dd so the key info is all in one place. (In general, expression.dd can provide more technical info than a specific page, but the type of a literal seems pretty important to leave out of lex.dd).
Keep old link anchors.
Add link for `$`.
> [expression.dd] (re)move 2 sections to lex.dd

- spec/expression.dd
Move *Expressions* heading to the top with grammar, and add *Comma Expression* heading where it was.
Add *Logical Expressions* heading with *OrOr Expressions* and *AndAnd Expressions* subheadings.
Add *Pointer Arithmetic* subheading for *AddExpression* and move a paragraph above it.
Use some lists instead of multi-part sentences for clarity.
Add *Division* and *Floating Point* subheadings of *Mul Expressions*.
Add table for UnaryExpression.
Add *Multidimensional Arrays* subheading under *NewExpression* and move 2 paragraphs above it.
Add table for PostfixExpression.
> [expression.dd] Improve formatting

- spec/arrays.dd
- spec/expression.dd
- spec/hash-map.dd
Add *Array Literals* section.
Rename *Array Usage* to *Array Assignment* & improve example, link to *Slicing*. Comment out error lines for clarity.
Add example for *Indexing*.
Remove unnecessary variables in *Pointer Arithmetic* example.
[expression.dd]
Simplify literal -> static array example.
[hash-map.dd]
Make first example runnable.
Add AA *Literals* section.
> [spec] Improve array docs

- spec/expression.dd
Add subheadings for each definition, keeping existing anchor names.
Use example blocks for complicated expressions, improving readability and syntax highlighting.
> [expression.dd] Improve formatting for *Definitions and Terms*

- spec/expression.dd
* Fix closing `<p>` tags before `<div>`, lists or code examples to prevent empty lines in HTML.
* Add *Aggregate Equality* subheading under *Equality Expressions* & move paragraph about arrays above it.
* Add *Array Comparisons* subheading under *Relational Expressions*.
* Improve example showing runtime null object equality error.
* Move paragraph about `o1.opCmp(o2)` under existing *Class Comparisons* subheading.
> [expression.dd] Improve formatting for comparison operators

- spec/statement.dd
Move subheading about foreach/break/continue into main foreach section (it doesn't need a separate subheading).
Tweak some examples & make them runnable.
Fix using `size_t` for foreach index type.
Fix wrong heading level for *Foreach Range Statement*.
Qualify `with` equivalency example: 'if `ident` is a member of the type
of `expression`'.
Fix and simplify mixin statement example.
> [statement.dd] Improve docs & examples

- spec/class.dd
- spec/declaration.dd
- spec/function.dd
- spec/garbage.dd
- spec/operatoroverloading.dd
- spec/template.dd
Also tweak those examples:
Move const attribute after parameters.
Fix calling array delegate elements.
Rename 2 eponymous template member functions so they can be called explicitly (this is before the IFTI section). Needed to compile.
Replace some trivial writefln calls with writeln.
> [spec] Make more examples runnable

- spec/module.dd
For better *Contents* navigation. 
'Import Declaration' now has 7 subheadings.
'Static Construction and Destruction' now has 3 subheadings.
Add a 'Module Declaration' subheading for 'Deprecated modules'. This helps separate the notes about best practice for module names from the unrelated deprecated module information.
Minor tweak to `AssignExpression` sentence.
> [module.dd] Use relevant subheadings

- spec/statement.dd
For while, do/while, foreach sections (some other sections to do separately).
Unnecessary GLINKs clutter paragraphs and are repeated from links in the grammar section just above them.
They also make significant links to other sections harder to notice for the reader.
> [spec/statement.dd] Remove some unnecessary GLINKs

- spec/intro.dd
The heading was linking to https://dlang.org/spec/memory-model which does not exist. I guess it should have been an anchor link instead.
> Fix deadlink in heading "Memory Model"

- spec/version.dd
Follow-up for https://github.com/dlang/dmd/pull/13545.
> Follow-up to DMD PR#14892: document version(D_ProfileGC).

- spec/template.dd
Add *Template Declarations* heading:
Add example for template type parameter.
Fix: Value parameters are not limited to int, float, string.
Fix: Alias parameters can take local symbols.
Move paragraph about overloaded templates from *Explicit Template Instantiation* to *Template Declarations*.
Mention eponymous templates & often using short syntax templates instead.
Move sentence about value specialization to *Value Parameters*.
Add *Type Sequence Deduction* subheading of *Sequence Parameters*.
Tweak *Eponymous Templates* wording.
Rename *Aggregate Templates* to *Aggregate Type Templates*.
Move 'IFTI vs static if' section from *Eponymous Templates* to *IFTI* & add *Restrictions* subheading.
Move *Template Constructors* below *Function Templates* section.
> [spec/template.dd] Improve docs

- spec/arrays.dd
Remove redundant example in *Slicing*.
Make example compile.
> [arrays.dd] Move *Array Length* section straight after *Slicing*

- spec/declaration.dd
Define aliases in terms of another symbol, not just another type.
Add subheadings.
Add note about capitalizing non-basic type aliases.
Move paragraph about type aliases being indistinguishable (from other aliases) up to type aliases section.
Move function type aliases example down to function type aliases section.
Make 2 examples runnable.
Simplify aliasing an overload set example - classes A and D are not needed.
Make *AliasAssign* sections child headings of *AliasDeclaration*.
Make *AliasAssign* examples get compiled; add static assert with `staticMap` and `T.sizeof`.
> [spec] Improve *AliasDeclaration* docs

- spec/statement.dd
Follows on from #3175.
Expand PS0 macro (too cryptic).
Expand PSCURLYSCOPE macro (only used for *ScopeGuardStatement*).
Remove unused macros.
> [spec/statement.dd] Remove more unnecessary GLINKs

- spec/template.dd
Remove unused function parameter.
Make `Addable` example runnable & show that the template this parameter is not necessarily the same as the runtime type.
> [spec/template.dd] Tweak 'This Parameter' examples

- spec/expression.dd
Add subheadings for *CastExpression*.
Make more examples runnable.
Add missing *CastQual* anchor.
Remove some unhelpful `GLINK`s when that link is already nearby.
> [expression.dd] Improve *CastExpression* docs

- spec/arrays.dd
- spec/expression.dd
~~Depends on #3162 for anchor link.~~
Document dereference and address of operators with examples.
Mention pointing to multiple elements and how this is not `@safe`.
Add *Pointer Arithmetic* subheading for *Indexing* & add example. This replaces the old section, actually compiles and is simpler.
> [arrays.dd] Improve pointer docs

- spec/expression.dd
* Make IndexExpression docs more generic.
* Mention pointer indexing & slicing.
* `$` is also declared for *ValueSeq* slices and can be for user types - make this paragraph independent of array slicing.
* Don't only talk about slicing arrays throughout, but slicing elements of the *PostfixExpression* instead. This is more generic.
* Mention first and last element expressions for arrays and pointers.
* Add *Slice Conversion to Static Array* subheading, move *ValueSeq* paragraph above it & add a *ValueSeq* link.
> [expression.dd] Improve IndexExpression & SliceExpression docs

- spec/statement.dd
Move `break` statement description above first example.
Fix: `default:` is required - combine info and make consistent. Move info nearer example (it was in the middle of case behaviour paragraphs).
Add *No Implicit Fall-Through* subheading and split example into two.
Make second example runnable using foreach to demonstrate `continue`.
Add *String Switch* subheading.
> [spec/statement.dd] Improve switch docs

- spec/declaration.dd
These were added by:
https://github.com/dlang/dlang.org/pull/664
yet are referenced from nowhere. They appear to be to support C syntax, but the only reason C syntax is recognized is to emit a sensible error message. It serves no purpose to be in the specification.
> remove Alt grammar rules

- articles/lazy-evaluation.dd
- spec/expression.dd
- spec/statement.dd
Updates the grammar rules and moves the documentation from `statement.dd` to `expression.dd`
Also added an example for nested throws and removed the outdated paragraph in the lazy evaluation article.
---
See dlang/dmd#13162
> Replace throw statement with throw expressions (DIP 1034)

- spec/function.dd
This is how they are actually already parsed and tested in DMD, updates the spec to reflect that.
https://github.com/dlang/dmd/blob/52844d4b1e9d6714bfd2e535f25a72074a046209/test/compilable/shortened_methods.d
> add contracts to ShortenedFunctionBody grammar

- spec/attribute.dd
- spec/function.dd
Move simple overriding example from 'Function Inheritance and Overriding' to use as first example. This introduces `override` before the next more complex example about virtual vs non-virtual methods, which also uses `override`.
Explain that `override` is required and that it can catch bugs.
Use list for kinds of non-virtual functions.
Simplify examples a bit.
Move paragraph about Objective-C to end of section.
Add 'Covariance' subheading.
Add 'Calling Base Class Methods' subheading & tweak wording.
Change 'Function Inheritance and Overriding' subheading to 'Overload Sets and Overriding'. Add missing `override` attribute in an example and use `SPEC_RUNNABLE_EXAMPLE_FAIL`.
Add 'Default Values', 'Inherited Attributes', 'Restrictions' subheadings.
'Function Parameters' section:
Add …
> [spec/function.dd] Improve *Virtual Functions* section

- spec/statement.dd
Link to `std.range`.
Add example using linked list.
Add 'Multiple Element Values' subheading.
Fix tuple -> sequence typo.
Fix tuple front example to not infinite loop & make runnable. Show single foreach variable is still legal.
Link to `Tuple`.
> [spec/statement.dd] Improve 'Foreach over Structs & Classes with Ranges'

- changelog/next_version.sh
Fix the next version being calculated as "2.0100.0".
> changelog/next_version.sh: Zero-pad three-digit version properly

- articles/index.dd
- articles/mixin.dd
- articles/template-comparison.dd
- comparison.dd
- dlang.org.ddoc
The term *mixin* should always be qualified, e.g. with *template* or *string*.
Fix `template-comparison.dd` link to *Template Mixins*, not string mixins.
> Disambiguate 'Mixins' everywhere

- articles/ctarguments.dd
Use CONSOLE macro for output.
Use lowercase identifiers for value sequences.
Change 'Assignment' heading to 'Element assignment' and make it a subheading of 'Indexing and slicing'.
Change 'Loops' to 'foreach'.
Change 'Type sequence instantiation' to not be a subheading of type sequences because it's about specific lvalue sequences, which the next heading continues for value sequences in general.
Move `Tuple` sentence to 'Value sequences' heading (it applies to other value sequences as well besides just type sequence instances).
Remove unnecessary 'Aggregate field sequences' subheading.
Mention value sequences can't be returned from functions.
Add symbol sequence example.
> [articles/ctarguments.dd] Various improvements

- spec/traits.dd
The `hasMember` trait made an odd claim — that adding `import std.stdio;` inside a struct S makes `write` a member of that struct. If you run the example, you can see that `write` isn't a member after all.
I left the `import std.stdio;` at the top to show that UFCS doesn't mean any function is a member.
> Correct hasMember trait example

- ddoc/source/preprocessor.d
The first process was started by `pipeProcess` but never interacted with,not even calling `wait` before starting the next instance - with the exact same arguments!
Seems like this line wasn't deleted in dlang/dlang.org#2069 which introduced `execute` and removed the other code interacting with the piped process.
> ddoc_preprocessor: Don't execute dmd twice

- spec/type.dd
See also [issue 7947][1].
[1]: https://issues.dlang.org/show_bug.cgi?id=7947
> Fix issue 15437 - documentation for typeof(someTemplate) == void

- deprecate.dd
- spec/class.dd
- spec/expression.dd
- spec/module.dd
However... this is only half the story, as class allocators still live on in the form of `@disable new();` only.  This is not mentioned anywhere in the spec and should be added as well.
> spec: Remove mentions of custom allocators and deallocators

- spec/template.dd
Under *TemplateDeclaration*:
Move template parameter grammar & info to parameter section.
Add parameter specialization example. (Specialization needs to be defined here as it is mentioned for template overloading).
Add *Template Parameters* heading:
Use 'default arguments' not 'default values' as they can be types.
Make existing headings for template parameter kinds into subheadings.
Rename *Argument Deduction* section to *Parameter Type Deduction* and make it a subheading too. (Later this should be moved to a subheading of *Type Parameters*).
Add *Avoiding Runtime Type Checks* subheading for TemplateThisParameter.
Add *Specialization* subheading for TemplateValueParameter and explain example, make runnable.
> [spec/template.dd] Add *Template Parameters* heading

- index.dd
Fix title: A static array of characters is not a tuple.
Split complex expression `aa[arr[i .. $][0 .. 2]]++;` into 2.
> [index.dd] Tweak character pair frequency example

- spec/statement.dd
Explain the variables declared in `ForeachTypeList` better.
Move paragraph about inferring the type of the `ForeachType` declaration from the `ref` subheading to main foreach section.
Move note about `auto` being redundant from array subheading, along with the example.
Modify the example, make runnable. There's no real need to show `auto` causing an error.
~~Mark resizing/reassigning a container during foreach as undefined behaviour. Tweak example.~~
> [spec/statement.dd] Improve foreach docs

- spec/function.dd
Add grammar for `main` now it can be declared with `auto` and
`noreturn`:
https://issues.dlang.org/show_bug.cgi?id=22419
https://issues.dlang.org/show_bug.cgi?id=22113
(This is for the 2.099.0 release).
Also document `string[]` parameter.
> [spec] `main` can be declared with `auto` or `noreturn`

- articles/ctarguments.dd
- spec/arrays.dd
- spec/attribute.dd
- spec/contracts.dd
- spec/expression.dd
- spec/function.dd
- spec/hash-map.dd
- spec/simd.dd
- spec/template.dd
- spec/traits.dd
- spec/type.dd
- spec/version.dd
It's easy to forget the subdirectory prefix with these macros.
It would be great if the test suite could check that the number of broken links doesn't increase for each pull request.
> Fix broken DDSUBLINKs & code_coverage DDLINK

- spec/declaration.dd
Add *Grammar* heading & subheadings. This helps break up a big block of grammar text for easier navigation.
Add link to *DeclDef* under *Declaration*.
Inline *VarDeclaratorIdentifier* and *ExpInitializer* as they are singletons and not referenced anywhere else. They don't appear in grammar.dd.
> [spec/declaration.dd] Grammar tweaks

- spec/statement.dd
Use BEST_PRACTICE macro to illuminate best practice recommendations.
> annotate opApply() delegates with scope

- spec/arrays.dd
- spec/expression.dd
- spec/operatoroverloading.dd
Make *InExpression* discuss a container, not just an associative array. Use key/value rather than *element*.
Mention result of `in` is a pointer *for AAs* (specifically).
Move sentence about precedence below result type description.
~~Add best practice note about overloading `in` only when there's sub-linear time complexity.~~
Add note about overloading `opBinaryRight`.
> [spec/expression.dd] Improve InExpression

- spec/interface.dd
Add *Interface Declarations* heading & subheadings.
Reparent 2 existing headings.
Tweak examples:
Use `I` instead of `D` for interface identifier - easier to understand.
Make 2 runnable, catching a missing `override` attribute in the 2nd one.
> [spec/interface.dd] Tweak interface docs

- spec/statement.dd
Tweak wording.
Add 2 `case` statement examples, which are equivalent.
> [spec/statement.dd] Tweak switch/case docs

- spec/statement.dd
Mention loop body is statically expanded like `static foreach`.
If given, the type of the element alias must be compatible with the type of every sequence element.
Add index variable in example.
Add ValueSeq example.
> [spec/statement.dd] Improve 'Foreach over Sequences' docs

- spec/statement.dd
Add example.
Fix: The variable types don't have to match key & value types exactly, they just need to be compatible.
Make existing example runnable & move above two sentences.
~~Use UNDEFINED_BEHAVIOR macro for unspecified iteration order.~~
> [spec/statement.dd] Improve 'Foreach over Associative Arrays'

- spec/statement.dd
The variable type can be compatible with the element type, not match exactly.
Mention modifying the element with `ref`.
Move paragraph about index type below example; use type inference.
> [spec/statement.dd] Improve 'Foreach over Arrays'

- spec/arrays.dd
- spec/expression.dd
Split out from #3157.
Improve array concatenation example.
Add heading for *Array Appending*, separate relevant paragraphs.
Make *CatExpression* discuss a container, not just an array.
Mention concatenating a single value.
> [spec] Improve concatenation docs

- spec/function.dd
Improve formatting.
Tweak examples.
Move accessing global state example nearer the top; remove 3 unused function parameters.
Move mutating locals and throwing exceptions nearer the top.
Add subheadings *Special Cases*, *Pure Factory Functions*, *Optimization*.
Explain a pure factory function result can be implicitly cast to any qualifier & show this in the example.
> [spec/function.dd] Improve Pure Functions section

- spec/declaration.dd
- spec/struct.dd
Move `StructInitializer` grammar to struct.dd from declaration.dd. It's not a declaration and the docs for it are in struct.dd.
Add *Initialization* heading and reparent 5 headings.
Minor tweaks.
> [spec/struct.dd] Improve struct initialization docs

- spec/statement.dd
The *loop* must be invariant, not the aggregate.
Improve array example - use 'unspecified' rather than 'error' as it doesn't throw.
Add AA example.
Document resizing or reassigning dynamic/associative arrays is `@safe`.
> [spec/statement.dd] Improve foreach loop invariant docs

- spec/statement.dd
Improve wording of delegate parameter usage.
Add *Template `opApply`* subheading and move paragraph about catching exceptions above it.
Remove repeated *opApply* anchor.
Make template example runnable.
> [spec/statement.dd] Improve opApply docs

- spec/memory-safe-d.dd
Fix omission from https://github.com/dlang/dlang.org/pull/2453#commitcomment-53328593
> specify @trusted functions must have @safe interface

- spec/lex.dd
* Fix missing `\` characters. 7 are missing in the left column on:
https://dlang.org/spec/lex.html#escape_sequences
and there are more errors in the descriptions. This fixes all of those.
* Add two *see also* links to `std.conv`.
* Fix unintended extra column from entity description.
> [spec/lex.dd] Improve Escape Sequences formatting & add std.conv links

- spec/lex.dd
Hex strings have been obsolete since 2.086.
> spec/lex.dd: Remove HexString from grammar

- spec/template.dd
- spec/type.dd
Mention any argument passed to an alias parameter can be passed to a sequence parameter.
Show `AliasSeq` definition.
Link to CT sequences article.
`typeof` can be used on a *ValueSeq* to obtain a *TypeSeq*.
Mention a sequence is automatically expanded when referenced in a declaration or expression.
Split sequence `print` example into 2 - one with ValueSeq arguments, one with TypeSeq arguments.
A *TypeSeq* can similarly be used to declare lvalue variables.
Add *Sequence Operations* subheading & add example.
Explain how to construct a sequence from an existing one.
Mention AliasAssign for iterative construction.
Mention foreach on a sequence.
type.dd:
`typeof` can be used on a *ValueSeq* to obtain a *TypeSeq*.
> [spec/template.dd] Improve TemplateSequenceParameter docs

- spec/declaration.dd
- spec/expression.dd
Rename ArrayInitializer to ArrayLiteral.
* ArrayInitializer is not referenced anywhere else.
* Existing ArrayLiteral grammar was wrong.
Tweak wording of array literal description.
**Update:** 
* Document `[`*AssignExpression* `:` *NonVoidInitializer*`]` syntax.
* Remove slicing from array literal section, just link to it (the example for each is the same).
> Move ArrayInitializer grammar to expression.dd & improve docs

- spec/traits.dd
Previously, several traits were incorrectly classified as "Symbol
Traits".
CC @ntrel
> spec/traits.dd: put traits under correct headings

- spec/abi.dd
Only Win64 targets still use the DigitalMars EH tables support code.
> spec/abi.dd: ELF and Mach-O targets now use DWARF EH

- css/style.css
- spec/expression.dd
Add Basic, Identifier and Parameter List form subheadings instead of an ordered list. Better for navigation and grouping relevant things together. Also use H5 for each kind of `is` expression, for anchors.
Move is(Bar == int) example above `== keyword` forms.
Add some missing docs for `== __vector`.
Add example for is(Type == keyword) and link to spec/traits.
Fix: `is` declaring an identifier also works in StaticAssert.
Make is(Type Identifier) example runnable. Also show that the identifier remains in scope even outside `static if` - see https://issues.dlang.org/show_bug.cgi?id=18609.
Split is ( Type Identifier : TypeSpecialization ) example in two.
Move is(Bar T == int) example above `== keyword` forms.
Explain `Identifier == keyword` form *result* for super, return, __parameters.
Split …
> [spec/expression.dd] Improve IsExpression docs

- spec/traits.dd
The trait now consistently returns the function parameters
See dlang/dmd#13798
> Remove special case of __traits(parameters) in foreach

- spec/iasm.dd
The generated contents table erroneously includes a dead "Other" subcategory because of the "$(COMMENT)" section that follows for DMD-style inline asm.
> spec/iasm.dd: Move GCC syntax to the bottom of the page

- spec/template.dd
Contrary to what was previously stated in the text, the example did not
fail because the template parameter T was specialized. Instead, it
failed because the T used in the template parameter list referred to a
different type than the T used in the function parameter list, and the
former could not be deduced from the latter.
To make the example clearer, the second T has been changed to U, and the
text has been updated accordingly.
> spec/template.dd: correct misleading IFTI example

- spec/function.dd
DMD PR: https://github.com/dlang/dmd/pull/12689
> Fix issue 22027 - `inout` doesn't imply return

- deprecate.dd
This is a really old deprecation that already passed the deprecation period for
more than 5 years.
Reference: https://github.com/dlang/dmd/pull/13823
> deprecate: make unannotated asm blocks error instead of deprecation

- spec/function.dd
For D mains, document that parameter / return types may be qualified and
also can be replaced by enums with appropriate base types.
For C mains, document that it may be used without -betterC and how it
interacts with runtime initialization. Replaced the list of allowed
signatures with a proper grammar and also added a workaround for exotic
main signatures.
> Fix 22959 - Extend documentation for C/D main functions.

- spec/template.dd
Move paragraph about auto-expansion up (as it's not only for homogeneous sequences).
Add link for using sequence as template args.
Add *Homogeneous Sequences* subheading & mention `.tupleof`.
> [spec/template] Improve homogeneous sequence docs

- spec/class.dd
Make `Field Properties` a child heading of `Fields`.
Rename `Class Properties` to `Class Instance Properties`.
List `outer` property under Class Instance Properties.
> [spec/class] Tweak class property docs

- spec/class.dd
Split up examples.
Show static function can't instantiate nested class.
> [spec/class] Tweak nested class docs

- spec/class.dd
- spec/struct.dd
Undo recent change to properties heading as .tupleof is a type property too (oops).
Update template link to more relevant anchor.
tupleof doesn't include static fields.
Show examples of .tupleof on class type.
Expand instance example.
> [spec/class] Improve tupleof docs

- spec/statement.dd
Improve sequence link.
Be more specific about `ref` foreach working on lvalues & mention lvalue sequences.
Use type inference in `ref` example.
> [spec/statement] Tweak foreach sequence docs

- spec/arrays.dd
- spec/template.dd
Add example & remove link to class .tupleof.
Add link from template.dd.
> spec/arrays: Improve static array .tupleof docs

- ddoc/source/assert_writeln_magic.d
- ddoc/source/preprocessor.d
- dpl-docs/source/ddox_main.d
Pass the current file path to libdparse s.t. error messages point to the
actual file instead of `magic.d`.
> assert_writeln_magic: Report filename on error (instead of `magic.d`)

- spec/attribute.dd
- spec/class.dd
- spec/function.dd
Methods of a final class are always final (not by default).
Explain `final` in Virtual Functions section and add anchor.
> [spec/attribute] Document `final` attribute

- changelog/2.098.0.dd
Trivial rename. Keep the old name in the anchor to not break links.
> Fix issue 22503 - Invalid changelog entry for isValidCodePoint

- spec/attribute.dd
Make examples runnable & use .offsetof.
Add link to Struct Layout.
Add GC Compatibility subheading, move scope paragraph above.
Add example showing error assigning to unaligned pointer in `@safe` code.
> [spec/attribute] Improve AlignAttribute docs

- spec/function.dd
This removes the old design where it matters whether the function returns by `ref`, and replaces it with the new design where it matters if `return scope` appears together.
Reference: 
[Issue 22541 - DIP1000: Resolve ambiguity of ref-return-scope parameters](https://issues.dlang.org/show_bug.cgi?id=22541)
[Issue 22790 - ref-return-scope is always ref-return, scope, unless return-scope appear in that order](https://issues.dlang.org/show_bug.cgi?id=22790)
This is not final, like [Paul Backus proposed](https://forum.dlang.org/post/qqfqdsdhqwrrckturpal@forum.dlang.org) and [Walter mentioned](https://issues.dlang.org/show_bug.cgi?id=22541#c4):
> Where I'd like to go is only allow "return ref" or "return scope".
But this brings it up to date with where we are now.
> Update Ref Return Scope Parameters to new design

- spec/class.dd
I think this was brought up by Loara in https://forum.dlang.org/post/bsjqwumagbjqpbozfmxc@forum.dlang.org somewhere, though I can't find the exact spot.
> Mention scope attributes on class `this`

- changelog/release-schedule.dd
There was a large gap between 2.098 (October 2021) and 2.099 (March 2022), but I think we're back on track with 2.100
> Update release schedule for 2022

- spec/attribute.dd
- spec/class.dd
They fit better in class.dd and the final class docs are there (as well as synchronized classes). 
Link to class.dd from attribute.dd instead.
The first commit just moves the paragraphs.
The second commit tweaks the docs and adds examples.
Move abstract class attribute after abstract methods rather than in the middle of them.
> [spec/class.dd] Move abstract class docs to class.dd & add examples

- spec/function.dd
Improve description.
Document that other local symbols besides imports do not match a UFCS call.
Split example & move member function paragraph.
> [spec/function] Improve UFCS docs

- spec/class.dd
This should not be exhaustive (we already have a TOC) but should mention notable things.
Add:
* nested classes
* operator overloading
* item for other declarations - link to [DeclDef](https://dlang.org/spec/module.html#DeclDef)
* links for interfaces, static fields
Remove:
* anonymous metaclass for Objective-C (not D so not that relevant, it is mentioned in member functions section)
* types - covered by DeclDef
* synchronized attribute - this is not a *component* of a class (it's in the TOC)
* static constructors and destructors - these are in the TOC but they don't
seem to be particularly relevant to classes. In another
pull I could merge these sections from class.dd into the module.dd
docs: https://dlang.org/spec/module.html#staticorder, as they are
children of DeclDef.
* unittests - …
> [spec/class] Improve list of class components

- spec/expression.dd
- spec/function.dd
Link to function pointer/delegates section.
Fix some missing semi-colons & typo.
Add 'Type Inference' and 'Short Syntax' subheadings and move note about comparing nested functions with function literals above them.
Simplify delegate loop example.
Tweak `square` delegate example.
Fix wrong link to nested functions.
Add 'Declaration Order' subheading for Nested Functions.
> [spec] Tweak function literal docs

- spec/function.dd
Add anchor.
Move 'Functions without Bodies' section straight after 'Function Bodies' & move MissingFunctionBody grammar too.
Improve ShortenedFunctionBody description.
> [spec/function] Improve function body docs

- spec/expression.dd
- spec/function.dd
- spec/statement.dd
- spec/type.dd
function.dd:
Add anchors for contract preconditions, postconditions (see below).
Move sentence about non-void return type requiring at least one terminating statement from statement.dd to Return Values section. Also mention noreturn statements.
Add link to ref functions.
statement.dd:
Link to function return values.
Uncomment returning a expression when return type is void. This was commented out in 549bdb109 because the expression could be non-void before [this issue](https://issues.dlang.org/show_bug.cgi?id=5399) was fixed (mentioned in commit message). Document that the expression must be void in this case, and that this is useful in generic programming.
Link to `out` contract docs rather than contracts.
> [spec] Improve return docs

- spec/expression.dd
- spec/function.dd
Use SpecifiedFunctionBody instead.
Also:
Remove space before `$(OPT)`.
Mention AssignExpression when there's no SpecifiedFunctionBody to infer Type from.
Add link to ReturnStatement.
Remove links to above paragraph.
Keep a legacy anchor.
> [spec] Remove singleton FunctionLiteralBody

- spec/lex.dd
According to the current definition, `_` is not always allowed but
`6_022_.140_857E+20_` is officially valid. The new definition fix that.
Note: DMD implementation is correct and support this number
> Fix definition of DecimalFloat in the Lexer

- spec/class.dd
- spec/struct.dd
For both class & struct:
Move example under 'invariant form' paragraph.
Move 'if the invariant does not hold' under when invariant *is* called.
Move notes about failed invariant under 'if the invariant does not hold'. This is clearer than putting all notes at the end of the section, plus 'the program enters an invalid state' is begging for immediate clarification.
Class:
Remove sentence about .init value - this is a null reference (this likely came from the struct docs).
Unfortunately the diff is not very review friendly, but I didn't edit any moved text except adding a missing 'and' for this sentence:
```diff
-    $(P Class $(I Invariant)s must hold at the exit of the class constructor (if any),
+    $(P Class $(I Invariant)s must hold at the exit of the class …
```
> [spec] Tweak invariant docs

- spec/statement.dd
This sentence was added to account for a change in the behavior of
return statements in DMD 2.037. That change has long since been
reverted, and the sentence is now false.
See https://issues.dlang.org/show_bug.cgi?id=3478
> Remove outdated clause from ReturnStatement spec

- glossary.dd
Snipped this out of https://github.com/dlang/dlang.org/pull/3328 because DAutoTest produces a log file of thousands of lines but no line indicating where the error is.
> add Associated C Compiler to glossary

- spec/importc.dd
As ImportC has evolved, so should the documentation. This also adds "Associated C Compiler" to the glossary where it can be linked to.
> update ImportC introduction

- spec/statement.dd
As per: https://github.com/dlang/dmd/pull/14269
> Update docs to not allow `scope(failure)` exit with a return

- spec/expression.dd
Clarify that a literal can implicitly convert to delegate without enclosing any variables.
Add links to alias & function templates.
Improve alias example.
> [spec/expression] Improve FunctionLiteral type inference docs

- download.dd
This is a temporary fix for the broken 2.100.1 downloads until someone with access can solve the actual problem.
> Fix issue 23237 - temp force 2.100.0 download

- dlang.org.ddoc
Since druntime has moved to dmd, all the source links are broken.
> Fix source links for druntime

- spec/expression.dd
Add missing `inout, module, package`.
Note: `__parameters, super, return, __vector` were added in a previous PR.
> Fix Issue 22835 - Undocumented type specializations of isExpression

- index.dd
Temporarily fixes the download links in `index.dd` as mentioned here: https://github.com/dlang/dlang.org/pull/3348#issuecomment-1191821963
> Temp fix homepage download links

- spec/expression.dd
_SpecifiedFunctionBody_ allows `do` and contracts.
https://dlang.org/spec/function.html#SpecifiedFunctionBody
> Fix Issue 19869 - `FunctionLiteral` allows incorrect forms

- spec/struct.dd
The docs for a struct literal with a union field apply for non-anonymous unions too.
Fix: Non-overlapping union field data is not default initialized, it is
zeroed.
Fixes Issues 21188, 18855.
> [spec/struct] Add 'Union Literals' & 'Anonymous Structs & Unions'

- spec/function.dd
`final` is not allowed here in D2.
```d
void foo(final int a){} // error!
```
```
finalpar.d(1): Error: variable `finalpar.foo.a` cannot be `final`, perhaps you meant `const`?
```
> Fix Issue 15379 - "final" attribute on function parameter

- spec/hash-map.dd
Replace 5 imported symbols with 1.
Use slide instead of zip to avoid using tuples.
Use GT for shell prompt like betterc.dd, not `%`.
> Simplify AA pair example

- spec/function.dd
Typo `hmtl`.
Introduced here:
https://github.com/dlang/dlang.org/pull/3347/files#r928235301
> Fix inout link

- spec/ddoc.dd
The link was dead, I fixed it to point to the new path.
> Changed the "here" link in Predefined Macros

- spec/arrays.dd
I think this code was left here by mistake: it is invalid because it is missing an identifier name before `=` and I don't think it belongs in that example.
> spec/arrays.dd: remove invalid code in example

- spec/ddoc.dd
Fixes Issue 15476 - DDOC_UNDEFINED_MACRO is undocumented.
Format more inline code.
Mention macros can take arguments *before* example using them.
Tweak generated HTML example and use 'such as' - this is not the exact output.
Improve wording of macro expansions.
Use bullet points.
Mention DDOC_UNDEFINED_MACRO.
Use RELATIVE_LINK2 macro.
Add 'Macro Arguments' and 'Macro Definitions' subheadings.
Add note about literal commas in an argument.
> [spec/ddoc] Improve macro expansion section

- spec/hash-map.dd
- wc.dd
Make hash-map.dd work on `stdin` so it can be run online; link to wc.dd.
Sync hash-map.dd code with newer wc.dd using `splitter` which works with Unicode.
This makes the hash-map.dd example shorter and easier to understand.
Tweak wc.dd example.
> Update word count examples

- spec/expression.dd
Make more examples compilable/runnable.
Use `static assert` instead of `writeln(typeid` for *IsExpression* examples.
Show in more places that `static if` identifiers outlast `static if`.
Use SPEC_RUNNABLE_EXAMPLE_COMPILE for typeif and SpecialKeyword examples that only call `write` and don't throw (speed up tests a bit).
> [spec/expression] Tweak examples

- spec/expression.dd
Move NewExpression to a subheading of PrimaryExpression, not UnaryExpression, following the grammar. Done in separate commit to changes below for easier review.
Make Casting array literals a subheading of array literals.
Add links to GC, scope & `obj.new` syntax for NewExpression.
Make allocating Multidimensional Arrays a subheading of NewExpression.
Make Special Keywords a subheading of PrimaryExpression, following the grammar.
> [spec/expression] Tweak PrimaryExpression docs

- spec/class.dd
- spec/const3.dd
- spec/function.dd
Add links to `this` parameter section in expression.dd.
Mention D-style variadic hidden parameters.
> [spec/function] Add Hidden Parameters section

- js/listanchors.js
These were built in https://github.com/dlang/docarchives.dlang.io/pull/3 and https://github.com/dlang/docarchives.dlang.io/pull/4.
> Bump archive version to v2.099.0

- spec/function.dd
- spec/type.dd
Mention unsafe casts.
List more implicit conversions.
Add Class Conversions subheading.
> [spec/type] Improve Type Conversions section

- spec/expression.dd
- spec/function.dd
Fix - `this` is not a pointer for structs, it's a reference.
Mention `typeof(this)` works anywhere inside an aggregate type, not just member functions.
Fix - assigning to `this` does work for structs.
`super` is only allowed inside a class.
Mention using `super` from Calling Base Class Methods.
> [spec/expression] Improve docs for `this` and `super`

- spec/expression.dd
Make Equality Expressions and Relational Expressions subheadings of Compare Expressions (they have the same precedence).
Add examples for IdentityExpression.
Make Array/Floating Point Comparison subheadings talk about `CmpExpression`, not just relational expressions. Mention using `is` to check for `NaN`.
Make Class Comparison subheading include `EqualExpression`, not just `RelExpression`.
> [spec/expression] Tweak CmpExpression docs

- spec/expression.dd
Also document promotion before unary `-` and `+`.
> Fix Issue 18496 - Complement expressions now actually int promote

- spec/expression.dd
Add link to op-assign.
Use tables for lowerings for readability.
Remove unnecessary `T` in lambda.
> [spec/expression] Tweak increment/decrement ops

- spec/expression.dd
- spec/type.dd
Expands on #3378.
Move integer promotion examples to that section and show `dchar` promotion.
Add rationale for integer promotion.
Add rationale for numeric type conversion rules.
Rename int, uint variables for signed/unsigned example and show long/ulong.
Add floating point example.
> [spec/type] Improve numeric type conversion examples

- spec/function.dd
This adds a table for what various combinations of ref-scope-return mean. Once one satisfies oneself that it is correct, it becomes easier to just check the implementation and code against the table, rather than trying to puzzle out each case over and over.
> add Cheat Sheet for RefScopeReturn

- spec/function.dd
When `return scope` was changed to always mean ReturnScope, the chart was not updated. This fixes it.
> update ref return scope

- deprecate.dd
Deprecation for dlang/dmd#14383.
> Deprecate throwing from contracts of nothrow functions

- spec/expression.dd
Fix mention of pointer index.
Add summary descriptions for index and slice expressions.
Mention overloading of index and slice operations.
> [spec/expression] Improve index and slice docs

- spec/expression.dd
Assignment doesn't always implicitly convert (e.g. assigning an element to a slice).
Use list.
Mention opAssign.
Link to opOpAssign.
> [spec/expression] Improve AssignExpression docs

- spec/expression.dd
Add subheadings for _Delegate Inference_, _Parameter Type Inference_.
Describe _Return Type Inference_ when the context has a different expected return type.
> [spec/expression] Improve FunctionLiteral docs

- spec/arrays.dd
Add *Growing an Array* subheading.
Mention reallocation.
Use list for when a copy is done, mention no spare capacity.
Add asserts to example.
Move `capacity` description to later example.
Add *capacity and reserve* subheading.
> [spec/arrays] Improve resizing section

- spec/arrays.dd
Introduce .ptr property before example using it.
Remove wrong line showing `s = a` as an error.
~~Show assigning a shorter array literal to a static array is OK.~~ It is a runtime error.
Mention slicing produces a dynamic array.
Improve _Array Setting_ example.
Update: 
* Document assigning a dynamic array to a static array.
* Extend Copying example with dynamic array
> [spec/arrays] Improve assignment docs

- spec/type.dd
@schveiguy:
> Also I cannot find "Value Range Propagation" anywhere in the spec.
> [spec/type] Add Value Range Propagation section

- download.dd
- index.dd
[Revert "Temp fix homepage download links](https://github.com/dlang/dlang.org/commit/64b902c76a8f1f75c68a41db365e7eecc0a5405c) (#3351)
[Revert "Fix issue 23237 - temp force 2.100.0 download](https://github.com/dlang/dlang.org/commit/92f05854a43ee059e6e83726f0a450a652108e6d) (#3348)
[Revert "Switch back to 2.100.0, 2.100.1 is not released yet"](https://github.com/dlang/dlang.org/commit/701fb2a266a6748aae8a3cc575ef1f85a10acde7) (#3344)
Reverts the mess people have been making of the mechanical parts of the site pages.
To be merged when I get the SMS from the RM.
> Revert download and changelog version changes

- spec/type.dd
Change `b` to `ubyte` because `int & 0xff` doesn't fit in `byte` (oops).
> [spec/type] Document that constant variables can track value range

- spec/function.dd
Document how `scope` prevents GC allocation.
Add example.
> [spec] Fix closure allocation docs

- spec/expression.dd
Show implicit conversion, not assignment in examples. 
Add link to array assignment.
Hide unimplemented conversions from runtime indexed slice of known length. The docs were merged but the compiler pull was not merged - see: https://github.com/dlang/dmd/pull/4209#issuecomment-74065882
> Fix slice to static array implicit conversion docs

- spec/expression.dd
Add example.
Fix: scope new is only special for class types.
> [spec] Document NewExpression forms

- spec/template.dd
Reparent auto ref section to function templates, not alias templates.
Changes done in separate commit:
Tweak wording.
Improve example to count refs passed.
Make both examples runnable.
> [template] Tweak auto ref docs

- spec/template.dd
> [spec] Tweak template alias parameter docs

- posix.mak
Since the dmd/druntime merger in #3334, `make clean` has been broken in the dlang.org repository.
> posix.mak: Fix make clean recipe

- download.dd
- js/platform-downloads.js
This is using our new downloads bucket, the old s3 bucket is there for archive only (no longer receiving any updates).
> Use downloads.dlang.org for all main download links

- changelog/changelog.ddoc
- changelog/prerelease.ddoc
- download.dd
Can now use https for downloads, as the site now has a new front for its bucket.  Others redirect to https anyway.
> Update changelog and downloads links to use https

- spec/template.dd
So specialization is described first.
Only content change is making _Type Parameter Deduction_ a child of _Type Parameters_.
> [spec/template] Move Type Parameters above Type Parameter Deduction

- js/run.js
- js/run_examples.js
Fix JS to insert `#line 1` so the auto-inserted `import std.stdio`/`void main` don't skew the line numbers.
> Fix Issue 23426 - Example Run button shows wrong line numbers for errors

- spec/expression.dd
making it more explicit that pattern matching is going on in IsExpressions
> pattern matching for Is Expressions

- spec/template.dd
The more common term for type deduction and specialization is "pattern matching". Make clear that pattern matching is happening with template type specializations.
> Template type specialization and pattern matching

- .circleci/config.yml
The circle/ images were [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) in 2021, and no longer receive updates.  As seen by a couple repositories [beginning to fail](https://circleci.com/gh/dlang/dlang.org/4716) due to outdated curl/ca certificates.
> circleci: Migrate to circleci convenience images

- spec/garbage.dd
> chore(spec/garbage): lookups on associative arrays doesn't use GC

- spec/arrays.dd
Remove sentence about appending to a static array. 
Add note about static array capacity being for generic code. 
Mention capacity is zero if not pointing to GC (array) memory. 
Extend example and explain it afterwards.
Explain when array length is reduced, capacity will be zero. 
Mention performance impact of capacity.
Fix Issue 23432 - document when array capacity is zero and capacity performance.
> [spec/arrays] Improve capacity docs

- spec/struct.dd
This change replaces informal language with official terms, adds cross-references, and documents a previously-undocumented requirement.
Fixes [Issue 23382][1] - Non-template requirement for copy constructors is undocumented
[1]: https://issues.dlang.org/show_bug.cgi?id=23382
> Clarify requirements for struct copy constructors

- spec/ob.dd
After a few puzzling minutes, I finally figured out by poking at different preview options that `@live` functions only are enabled with the `-preview=dip1021` switch.
This is not mentioned *anywhere*, not in the DIP itself (which never says anything about `@live` functions), nor on this page, nor in the preview switch documentation (which says it's about Mutable function arguments), nor in the [changelog where live functions were added](https://dlang.org/changelog/2.092.0.html#ob)
Actually, that preview switch doc should be updated to say it enables live functions.
> The `@live` feature is only active with dip1021

- spec/module.dd
- tools/dspec_tester.d
Extract & run the tests (like for dlang.org SPEC_RUNNABLE_EXAMPLE_*) to check the examples actually compile.
RUNNABLE_EXAMPLE seems to have been introduced to phobos in 2018 to std.exception. Recently I added it to std.regex, and I have a pull to add it to std.experimental.allocator: https://github.com/dlang/phobos/pull/8604.
In theory it could be used in druntime too, but as of now it isn't.
---
Depends on https://github.com/dlang/phobos/pull/8611.
Remove RUNNABLE_EXAMPLE from 1 module.dd example where it imported a module that doesn't exist.
Show path of file when printing number of examples found.
> Extract and test RUNNABLE_EXAMPLE tests including Phobos

- dlang.org.ddoc
So people don't get surprised when they are suddenly on a different webpage when searching for something.
> Make clear the search is using google

- dpl-docs/views/layout.dt
Many people, including myself, distrust Google and stay away from it as much as possible. To that end, I propose that search be routed through DuckDuckGo to make sure that everybody can search the site with peace of mind from a privacy standpoint.
> Use DuckDuckGo for search

- spec/statement.dd
* Not everything is convertible to `Object`
* `with` does preserve the value category
> Improve equivalence

- spec/importc.dd
I couldn't find a suitable replacement link for the Clang Preprocessor, so leave it blank for now.
> Fix 23541 - [ImportC] dlang.org contains incorrect links

- spec/struct.dd
Mention union fields use overlapping storage, add example. 
Add *Members* heading and *Union Members* subsection. 
Add recursive types subheading and example.
> Improve union docs

- changelog/release-schedule.dd
Nothing in 2022 went to plan, let's restart the cadence in releases from the New Year onwards.
> Plan release schedule for 2023

- spec/operatoroverloading.dd
The long example should come after opIndex, opSlice and opDollar have been explained.
No content changes other than making example runnable.
> [operatoroverloading.dd] move Array2D example down

- spec/abi.dd
See the function `dmd.toobj.genModuleInfo` for what specifically happens here. The compiler assumes a layout, druntime must match it instead of defining it.
> note that druntime must match compiler, not vice versa

- spec/operatoroverloading.dd
Add opCmp example.
Make opCall example runnable.
Add opOpAssign example.
Make opIndex() example runnable.
Add example for `s.opIndex(s.opSlice(...))`, tweak paragraph.
> [operatoroverloading.dd] Improve examples

- spec/ob.dd
- spec/spec.dd
- spec/windows.dd
The idea is to provide much better information about how Windows executables and dlls work and are constructed.
This is just a skeleton outline of the future page.
> add spec/windows.dd

- spec/version.dd
These got removed a while ago. Didn't do for the debug()  because I'm not sure about if it got removed from debug too.
> Remove version(integer) from docs

- tools/dspec_tester.d
~Currently depends on #3437 (see last commit for now).~
This avoids reading and allocating the contents of the same file 4 times (would've been 3 times before #3437).
> Fix Issue 23467 - `tools/dspec_tester.d` calls `readText` multiple times per file

- download.dd
https://dlang.org/download.html currently links https://downloads.dlang.org/releases/2022/dmd_2.101.2-0_amd64.deb, which is a 404. https://downloads.dlang.org/releases/2023/dmd_2.101.2-0_amd64.deb (`s/2022/2023`) works, however.
> Update download release year to 2023

- download.dd
- js/platform-downloads.js
Doing #3481, #3253,  every year is just silly.
> Use release version-based paths on the downloads page

- articles/regular-expression.dd
Use stdin instead of `argv` as RUNNABLE_EXAMPLE_ARGS doesn't seem to work (it seems it's not used anywhere on dlang.org). 
Tweak formatting & wording.
Mention regex syntax: named groups, lookaround.
Add subheading *Replacing*.
Add some line breaks.
> Improve regex article

- spec/attribute.dd
Fix const example, `const{...}` only works inside an aggregate type.
Add links.
> [spec/attribute] Improve const/immutable/inout docs

- spec/ob.dd
Add ownership, `@live` headings, edit borrowing heading.
Fix typos.
A mutable scope function parameter is borrowed.
Borrowed pointer can borrow from another Borrowed pointer, not just Owner.
Change Borrowed and Readonly pointer states to say they must *be* `scope`, not *have* the scope attribute, as it can be inferred.
Readonly pointer can be from a Borrowed pointer, not just Owner.
Add 3 examples.
> Improve Ownership/Borrowing spec

- spec/expression.dd
I specified the behavior of an associative array literal if pairs with the same key are declared and offered an example.
> Fix Issue 21132 - Duplicate keys in an AA literal

- spec/expression.dd
Added some information and examples about pointers and the casting process
https://issues.dlang.org/show_bug.cgi?id=6583
> Fix Issue  6583 - cast() operation not fully specified

- spec/function.dd
Added documentation for allowance of "new" in `@nogc` functions.
> Fixed issue 18830 - document "new" with "scope" in @nogc Functions

- spec/enum.dd
Added an example of using an opaque enum (and also an error in using it).
> Fix Issue 21178 - It is not explained what is "unknown"

- spec/function.dd
The result of a pure factory function can be converted to `immutable` or `const shared`, and from `shared` and `const shared` to _unshared_ `const`. It cannot be converted to “any qualifier” as the spec currently suggests:
* It cannot be converted to mutable (unless already mutable). This makes sense because a `pure` function may access `immutable` global state, which in turn could be read-only memory.
* Likewise, the result cannot be converted to `inout` because `inout` might become _mutable_ in the caller’s frame; the same argument as above applies.
* It cannot be converted from _unshared_ to `shared`, which might be a general limitation or a local limitation. I don’t really know how `shared` works or is supposed to work to judge that.
All other conversions are possible irrespective of …
> Result of pure factory function

- spec/statement.dd
Issue link: https://issues.dlang.org/show_bug.cgi?id=20997
I added an example to clarify the order of execution when scope() statement interferes with return statement.
> Issue 20997 - Missing example of scope guard executing after return statement

- .circleci/config.yml
We're now hitting 100%, or coming dangerously near to it.
For example, this the resource usage of a succeeding build: https://app.circleci.com/pipelines/github/dlang/dlang.org/2487/workflows/ffc63ff4-3650-48ef-a419-ac05c7f15599/jobs/4987/resources
It's now a coin toss whether we start swapping and get killed or succeed now.
This is the same commit, but the pipeline instead failed: https://app.circleci.com/pipelines/github/dlang/dlang.org/2488/workflows/c1b19d21-2e6c-412c-97b9-4c79cc6cebb6/jobs/4988/resources
By default the containers we're given are a "medium" resource class - 2 vCPUs, 4GB RAM.  The medium+ resource class gives us 3 vCPUs, 6GB RAM.
> circleci: Increase memory allocated to the CI pipeline

- foundation/donate.dd
Our Flipcause account is no more. This removes all references to it and reworks the text somewhat.
> Donation page overhaul

- spec/importc.dd
In C `asm` is a GNU extension, and is rejected by C compilers in strict C11 mode.  In ImportC `asm` is a standard D keyword, and we shared our implementation of `asm` with it.  Document this behaviour of our parser.
> fix Issue 23716 - Document asm extension for ImportC

- spec/traits.dd
Use 'the result is' not 'returns'.
Mention an alias may resolve to the same symbol.
Use static asserts instead of writeln.
Compare `object` instead of `std` so no import needed. 
Add example comparing expressions.
Split up large lambda example.
> [spec] Improve __traits(isSame)

- spec/expression.dd
The docs mention this but it's not clear what it means without an example.
Specify `is` identifier must be used in the first argument to introduce an identifier.
BTW, as a compiler enhancement, shouldn't the identifier still be in scope *after* the static assert statement?
> [spec] Show static assert `is` identifier example

- spec/module.dd
- spec/traits.dd
(You can see the broken links here: https://dlang.org/spec/traits.html#isModule).
Also split module/package grammar into 2 blocks for better formatting.
> [spec/traits] Fix module/package links

- spec/template.dd
Show that the parameter can still behave as a variable alias, it's more capable than just a value parameter.
> [spec/template] Tweak typed alias parameter example

- spec/expression.dd
Describe `== TypeCtor` more precisely and add example. 
Remove `is(i == const)` example as even if `const int i;` was used it would still be false because `i` isn't a type.
Add note to prefer isModule and isPackage __traits (ideally `== module` and `== package` would be deprecated as they only pass when *Type* is not a type, `is()` is for checking types).
Improve wording.
Add example of type implicitly converting to match pattern.
Update `Identifier ==` example and add pattern example.
For `Identifier == Keyword` form, link to non-_Identifier_ form to avoid repeating the same info.
> [spec] Improve `is(Type == keyword)` and Identifier docs

- spec/operatoroverloading.dd
See table in row 3 first column in docs (is **a >b**):
https://dlang.org/spec/operatoroverloading.html#compare
I don't know the doc-gen but the space now matches the first row for **a < b** (4 lines above in the source file)
> Missing space

- spec/class.dd
- spec/expression.dd
- spec/type.dd
`this` can be used in constructors as well as member functions. Make example runnable.
Add see also links for this & super.
Remove sentence about using `super` outside member, this is covered by *identical to `this`* wording and it's a bit complex to repeat correctly including `typeof(super)`.
Add *Base Class Construction* subheading in class.dd.
> [spec/expression] Improve this & super docs

- spec/function.dd
-dip1000 was enabled by default, so this note is no longer relevant
> Remove -dip1000 note from scope function section

- spec/const3.dd
Add subheading with anchor.
Use list to group unique conversions.
Link to pure factory functions.
> [spec/const3] Tweak Unique Expression conversions

- spec/function.dd
The result of a pure factory function must not have any non-mutable indirections.
See https://forum.dlang.org/post/jcwicxhqlulyuktyqgzz@forum.dlang.org.
Also don't create a circular linked list, it's superfluous to the example.
@aG0aep6G
> [spec/function] Tweak pure factory functions

- spec/function.dd
Note: reading `*pz` is not an error, removed.
Add subheading 'Strong vs Weak Purity' with anchor. 
Fix wrong return type of foo.
Add 2 subheadings under 'Special Cases'.
> [spec/function] Make 3 `pure` examples runnable

- spec/function.dd
A pure function must have only *immutable* indirections (or none) in its *arguments* to memoize calls. A parameter declared with const indirections is OK *iff* the argument passed to it has only immutable indirections.
See: https://forum.dlang.org/post/usoahljqoarefnhchpsz@forum.dlang.org
@dnadlinger @aG0aep6G
>  Clarify requirements for pure call memoization

- spec/expression.dd
Remove multi-dimensional array code in main example, link to subheading instead and add asserts there.
Mention that the result is unique and can be implicitly converted to other qualifiers.
Add 'Class Instantiation' subheading.
> [spec/expression] Improve NewExpression docs

- spec/attribute.dd
- spec/declaration.dd
Add links.
Add 2 subheadings.
Use distinct parameter name vs argument name in `ref` example.
Note: In another pull I plan to group together the storage class docs better in declaration.dd. Later possibly also move the core storage class parts of the attribute.dd docs (such as static) to declaration.dd as that's the logical place to look. Currently they are split over each file.
> [spec/declaration] Tweak Storage Class docs

- spec/attribute.dd
Add groups Mutability, Shared Storage, Function.
Note: Safety attributes aren't included in Function Attributes because `@system` applies to variables (not documented in spec yet). 
Add link for `auto`.
Add Class Attributes group, move `override` here.
> [spec/attribute] Group attributes

- spec/attribute.dd
- spec/const3.dd
Follows on from #3494.
Normal initialization of shared vars is OK (see https://dlang.org/changelog/2.093.0.html#shared-init).
Add atomicStore, atomicLoad example.
Add example showing casting *to* shared.
Mention shared globals use common storage not TLS.
> Fix Issue 14932 - spec does not define what shared attribute does

- spec/attribute.dd
Make C++ namespace example runnable.
Make deprecated example runnable.
Add 'Scope Values' subheading for `scope`.
Split scope example and make 2nd part runnable (the first needs -dip1000 or a compiler update).
Make scope new class example runnable.
Make 2 UDA examples runnable and add 'Templates' subheading.
> [spec/attribute] Make more examples runnable

- spec/function.dd
Make ref function example runnable & mention `return ref` parameters. 
Make it clearer Auto functions don't have to use `auto`, and they trigger attribute inference.
Reword auto ref functions.
> [spec/function] Improve ref and auto (ref) function docs

- spec/attribute.dd
Add link for `@live`.
Improve formatting.
Tweak wording for extern, C++ namespaces.
Fix missing `shared` link.
Fix wrong simple assignment link (anchor name must not have leading indentation).
Fix assignment operator link typo.
> [spec/attribute] Tweaks

- spec/expression.dd
Make it clear that an IsExpression checks if a **type** is valid. 
Tweak wording.
Add links.
Use new `alias` function type syntax.
Expand simple examples.
> [spec/expression] Improve IsExpression docs

- spec/struct.dd
Change headings to be independent of Struct Constructor section, because copy ctor section is quite long with subheadings that should be shown in the TOC.
Move sentence up about POD.
Extend example to show useful copy ctor and its effect.
Minor tweaks.
Add Disabled Copying subheading.
Add example for union with field of type struct which has a copy ctor.
> [spec/struct] Tweak Copy Constructor docs

- spec/attribute.dd
Follows on from #3558.
Add subheading for synchronized under Shared Storage Attributes rather than just a link in the grammar. That way it appears in the TOC. 
Rename _Class Attributes_ to _OOP Attributes_ as some of them also apply to interfaces.
> [spec/attribute] Tweak groups

- css/style.css
Otherwise only the text is clickable to show the list of options.
E.g. at the top right:
https://dlang.org/spec/expression.html
> Make version drop-down arrow clickable

- spec/declaration.dd
- spec/expression.dd
Changed wording as not sure all types count as symbols.
Add links.
Clarify only *manifest* constants can be aliased.
Other aliases can be aliased.
Don't use `import` keyword as it's only pseudo-importing.
> [spec/declaration] Tweak `alias` docs

- spec/expression.dd
- spec/template.dd
Add link to template parameter specialization.
`is` can't match an alias template instance _TypeSpecialization_ (see [DIP1023](https://github.com/dlang/DIPs/blob/master/DIPs/other/DIP1023.md)).
Also make 2 IFTI examples runnable.
Document that IFTI doesn't work with a parameter type that is an alias template instance.
Add ElementType alias example.
> [spec/template] Improve alias template docs

- spec/contracts.dd
- spec/expression.dd
Change link to use precondition spec in function.dd (contracts spec is a stub). 
Fix broken anchor in contracts.dd.
Add class invariant link.
Move compile-time evaluated condition paragraph down to its own subheading (avoid distracting from the runtime evaluation docs which are quite complicated).
Add short example.
Move message argument sentence down to its own subheading. 
Reword paragraph about compiler switches. Remove 'continuing execution' list item - that seems to be covered by the first sentence (whether the condition is evaluated or not).
Move best practice section up.
For CT evaluation, avoid mentioning 'release mode' which was undefined.
Add link to static assert.
> [AssertExpression] Improve docs

- spec/statement.dd
Move _CaseRangeStatement_ to its own subheading.
Tighten wording on case expression values.
Add rationale for requiring `default`, mention `final switch`. 
Add general example.
Mention other goto case/default usage.
> SwitchStatement: Improve docs

- spec/struct.dd
Fix old class links after #3498.
A union can have alias this.
Tweak wording.
> [spec] Tweak AliasThis docs

- spec/ddoc.dd
This is the behaviour of ddoc and ddox. (See https://github.com/dlang/phobos/pull/8739#issuecomment-1517971382).
> [spec/ddoc] Macros are expanded inside backticks

- spec/attribute.dd
Put them in sort order, add lnames for them so they can be directly linked to. No semantic changes.
> rearrange Visibility Attributes, add lnames

- spec/statement.dd
#3179 added a string switch subheading but the note applies generally to case statements.
No changes to wording.
> [spec/statement] Move note about case frequency up

- spec/interfaceToC.dd
The key part of the printf syntax relating to this example is essentially: `%{length modifier}{conversion format specifier}`. Some common examples:
* length modifiers:
* (none) -> used for: `int`, `usinging int`
* `l` -> used for: `long`, `unsigned long`
* `ll` -> used for: `long long`, `unsigned long long`
* `z` -> used for: `size_t`
* `t` -> used for: ptrdiff_t`
* conversion specifiers:
* `d`, `i` - signed integer integer to decimal representation
* `u` - unsigned decimal integer to decimal representation
* `o` -  unsigned decimal integer to octal representation
* `x` -  unsigned decimal integer to hexadecimal representation
For reference, see: https://en.cppreference.com/w/c/io/fprintf
The issue was reported here:
https://forum.dlang.org/post/wodeaztcqwxulrfrgjvb@forum.dlang.org
> Fix issue 23872 - Wrong example in Interfacing to C, calling `printf`

- posix.mak
- tools/chmgen.d
Fixes which should allow building dlang.org with parallelism (`make -jN`).
> Parallelism fixes

- spec/attribute.dd
~~Add missing `@identifier` grammar.~~
Fix: UDAs are not just expressions, they can be `@SomeType`. Describe kinds of UDA.
Add comments & show `@constant` in first example.
Describe type instance UDA.
Show function parameter with UDA.
Add subheading for getAttributes.
Use sequence not expression tuple, link to sequence docs, tweak wording. (They can include types not just expressions).
Add newlines for getAttributes example, use lowercase for manifest constant.
Add usage subheading, remove redundant sentence about tuples.
> [spec/attribute] Improve UDA docs

- spec/expression.dd
- spec/function.dd
- spec/template.dd
*Short* function literals are known as lambdas.
Use list for description and add item for omitted lambda parameter types.
function.dd: Merge two variants of _ParameterList_ grammar using OPT.
template.dd: Change alias kind to function literal, (not just lambda).
> [spec] Tweak function docs

- spec/function.dd
Move sentence up about 'dynamic closure'.
Add subheading 'method delegates'.
Describe method delegate syntax.
Show ptr and funcptr fields in example.
Also rename 2 functions.
> [spec/function] Tweak delegate docs

- spec/struct.dd
See DMD PR for rationale: https://github.com/dlang/dmd/pull/15122
> Allow `alias this` to use assignment-style syntax

- spec/attribute.dd
DMD supports this since https://github.com/dlang/dmd/pull/14881
> Change grammar to allow builtin types as UDAs in parens

- articles/RefReturnScope.dd
- articles/index.dd
- posix.mak
This article is intended to be more of an informal tutorial about how ref, return and scope annotations work rather than a formal specification.
This PR is the first part.
The second part will be a tutorial on the various ways pointers can escape.
The third part will be about common problems with it and how to resolve them.
> add article on ref, return, and scope annotations

- spec/struct.dd
because
```d
struct S
{
static struct T
{
}
}
static assert(__traits(isPOD, S.T)); // OK
```
> Specify that nested static struct might also be POD

- spec/template-mixin.dd
Tweak wording.
Add link to template instantiation scope.
Move scope example up.
Add *Mixin Parameters* subheading.
Move mixin virtual functions example to end as it is a specific use.
Move 'a mixin has its own scope' example up and add 'resolving ambiguities' subheading.
> [spec/template-mixin] Improve docs

- articles/RefReturnScope.dd
- articles/dll-windows.dd
- articles/index.dd
- book/dlang.org.ddoc
- css/style.css
- dlang.org.ddoc
- posix.mak
Part of the problems with creating Windows DLLs is caused by the near complete lack of documentation on it. This is a first step.
> Add article on building Windows DLLs

- spec/function.dd
Mention `@safe` is needed to check returning address of `return ref` parameter - the (now default) DIP25 is not enough.
Note -dip1000 *is* still needed to return the address of a `return ref` parameter.
Add example for void function with `return ref` parameter - this needs -dip1000 so can't be made runnable yet.
Note the example compiler is currently 2.102 which needs -dip25, so the example with the mars function errors but pluto always errors anyway so _FAIL is OK.
> Improve `return ref` examples

- spec/betterc.dd
Add 2 headings.
Use DDLINK not `.html`.
Add link for Interfacing to C++.
Tweaks.
Mention slicing pointers.
> [spec/betterc] Tweak docs

- spec/struct.dd
Update following #3638.
Tweak wording.
Document field destruction.
Mention destructor is called at end of scope even after calling `destroy`.
Remove assigning `init` - this doesn't call the dtor if opAssign is defined.
> [spec/struct] More on struct destructors

- deprecate.dd
As of https://github.com/dlang/dmd/pull/15192
> [trivial] [deprecate.dd] `asm @safe` is not allowed

- spec/declaration.dd
- spec/module.dd
This allows to declare them inside functions.
For mixin templates this is supported by DMD since https://github.com/dlang/dmd/pull/14240
Declaring normal templates in functions is also supported by DMD.
> Move Template(Mixin)Declaration to Declaration in grammar

- spec/function.dd
This documents existing behavior. See https://issues.dlang.org/show_bug.cgi?id=23941 for discussion.
> scope does not affect operator overloading

- spec/lex.dd
Condense *FloatLiteral*, *DecimalFloat*, _Suffix_ grammar.
Describe floating literal requirements.
Describe decimal floats with examples.
Add hexadecimal float example.
Move existing examples up.
Underscore is only allowed after a digit.
Use list for suffixes, show more examples.
Formatting tweaks.
>  [spec/lex] Improve floating point docs

- spec/lex.dd
Use list for formatting.
Mention C octal example.
Add examples.
> [spec/lex] Tweak integer literal docs

- spec/arrays.dd
Explain start and end indexes.
Expand example, show `.ptr`, show slicing a slice.
Change Identifier[] to Expression[].
> [spec/arrays] Improve slicing docs

- spec/version.dd
This is Apple's new operating system for their VR/AR device Vision Pro.
DMD PR: https://github.com/dlang/dmd/pull/15371.
> Add predefined version identifier for visionOS

- spec/operatoroverloading.dd
The manual heading links are missing some subheadings, and the automatic TOC is present anyway:
https://dlang.org/spec/operatoroverloading.html
> [spec/operatoroverloading] Remove manual TOC

- spec/enum.dd
Move EnumMember above EnumMemberAttributes in the grammar, as it is mentioned first. 
Split anonymous enums into separate grammar block. 
Add anonymous enums subheading for single member syntax rather than introducing this under manifest constants.
Explain that all enum members are manifest constants. 
Fix Issue 23571 - Discussion of manifest constants in enum documentation is confusing at best.
> [spec/enum] Tweak docs

- spec/operatoroverloading.dd
Add runnable example.
Clarify when implicit cast to bool happens. This does *not* happen whenever a bool type is expected.
Mention result of `opCast` is implicitly converted to the `cast` type.
> [spec] Improve opCast & `opCast!bool` docs

- deprecate.dd
- spec/legacy.dd
Moved it from the deprecate page to the legacy page.
Corresponding code change: https://github.com/dlang/dmd/pull/15394
> add body legacy code

- spec/expression.dd
- spec/importc.dd
In "Parameter List Forms", there is only part of a rule relevant for its particular subsection, the full rule is above at the primary section header.
The importc "FENV_ACCESS" grammar section is describing C11 grammar, not D grammar.
The expression "StringLiteral" grammar section is a redeclaration of "StringLiteral" which occurred previously in the lexer section, which seems to be the primary source.
* assuming I understand `$(GRAMMAR_INFORMATIVE` correctly
> These grammar sections are informative

- spec/declaration.dd
- spec/module.dd
- spec/statement.dd
Explain `Declaration` is the subset of `DeclDef` allowed inside a function body.
Move TemplateMixin from DeclDef and NonEmptyStatementNoCaseNoDefault to Declaration (which they each include).
Remove StaticAssert from DeclDef as it is already included by Declaration.
> [spec/declaration] Improve docs

- spec/lex.dd
There were subsections for the string literal varieties, but their grammar sections were all in the parent "String Literals" section.
> Move string literal grammar into subsections

- spec/function.dd
Fixes Issue 17934 - [scope] scopeness entrypoint for unique/ref-counted missing.
See https://issues.dlang.org/show_bug.cgi?id=17934#c12 for why this feature fixes that issue.
cc @dukc
> [spec/function] Improve `return` struct method attribute docs

- spec/expression.dd
- spec/lex.dd
Link to lex _StringLiteral_ rather than repeating grammar. 
Move semantic sentences about string literals being read-only to expression.dd.
Document that StringPostfix disables implicit conversions.
Document that a string literal can convert to a static array rvalue of same or longer length or lvalue of equal length.
~~Document that the null byte can be used to convert to a static array when necessary.~~
Move EscapeSequence and StringPostfix grammar to their subheadings.
> [spec] Improve string literal docs

- spec/expression.dd
they were not in a `$(GRAMMAR` section, but are grammar rules.
> Move NamedArgument{,List} into `$(GRAMMAR` section

- css/style.css
- dlang.org.ddoc
- spec/expression.dd
I copied the CSS property values from already used values. The `border-radius` being 5px rather than 4px is copied from the `message-box` style. (I think the 4px value is for smaller items like buttons).
Use it for `AssertExpression` docs to group several 'implementation defined' paragraphs and an example together.
https://dlang.org/spec/expression.html#AssertExpression
> Add PANEL macro to visually group certain paragraphs

- spec/attribute.dd
- spec/class.dd
Instead of 'scope object' or 'scope variable' because a reference can be `scope` without being stack allocated. The difference is the instance is *always* `scope`.
> [trivial] [spec] Use 'scope class instance` throughout

- spec/class.dd
Replacement pull for #3668, rebased (github wouldn't update it after a force push for some reason, or allow me to reopen it).
List when dtor called including destroy.
Use list for destructor characteristics.
Minor tweaks.
Change 'auto object' to 'scope class instance'
Whether the GC calls the destructor is implementation defined.
Use 'Important' heading for the order of destructor calls & use PANEL macro to split paragraph in two with grouping.
Fix wording about destroy as it applies to scope instances too.
@dkorpel
>  [spec] Improve class destructor docs

- spec/type.dd
"both" is not being used as a keyword or code here.
> fix font on both in type spec text

- spec/expression.dd
and it reference TypeCtor in the documentation,
so make it reference TypeCtor in the grammar directly.
> `TypeSpecialization` contains all `TypeCtor`s

- spec/arrays.dd
The next paragraph has this note for dynamic arrays, but it was missing for the paragraph on static arrays.
> Copy base-class note to other section.

- spec/expression.dd
The existence of CatExpression makes the expression grammar non-trivially left recursive and is not representative of how it is actually parsed, so merge it with AddExpression.
> Merge CatExpression and AddExpression

- spec/expression.dd
Under _PostfixExpression_ section.
Move _ArgumentList_ grammar here (it didn't especially belong under *NewExpression*).
Describe call expressions and type construction expressions.
@dkorpel This moves the _NamedArgumentList_ grammar, but doesn't describe that.
> [spec/expression] Add Postfix Argument Lists subheading

- spec/lex.dd
Decimal literals having exactly one zero and some underscores after it are accepted by DMD, but currently not allowed by the grammar. Previously they were allowed by the grammar as octal literals, but they have been removed.
> Allow the literal `0_` in the grammar

- spec/enum.dd
- spec/type.dd
enum.dd:
Tweak wording about named enum conversions to base type, link to example in type.dd.
Add *Enum Variables* subheading, remove *Enum Default Initializer* subheading. Extend example.
Add link to enum operations and final switch.
type.dd:
Add _Enum Operations_ subheading and example.
Add *Preserving Bit Patterns* subheading, use list.
> [spec] Tweak enum & type docs

- spec/arrays.dd
- spec/expression.dd
- spec/function.dd
- spec/template.dd
Them being independent expressions in the grammar made PostfixExpression non-trivially left recursive.
A more direct representation of the parser would be to combine indexing and slicing, but I assume the separation was deliberate for reader clarity.
> Move the base of {Index,Slice}Expression into PostfixExpression

- spec/lex.dd
DecimalDigitsNoSingleUS and HexDigitsNoSingleUS previously did not accept underscores at the start and end at the same time, but DMD allows this. For example the hex literal `0x_1_` and the floating point literals `0_1_.0`, `1e_1_` and `0x_1_p_1_` are accepted by DMD, but were not allowed by the grammar. BinaryDigitsNoSingleUS was already correct.
The grammar is also simplified by using optional parts instead of multiple rules.
> Allow underscores at more positions in grammar for numbers

- articles/template-comparison.dd
Besides the line tweaked in the diff below, arguments are used on line 246 and 250. Without this they are silently thrown away.
> [articles/template-comparison] Fix missing arguments to ERROR macro

- spec/enum.dd
- spec/type.dd
Link to it from type.dd instead.
Follow up to #3683.
> [spec] Move enum to base type example to enum.dd

- articles/template-comparison.dd
C++ still cannot do an enum type template AFAIU.
It was actually C++14 (not 11) that introduced constexpr constant templates: https://en.cppreference.com/w/cpp/language/variable_template
C++11 introduced type alias templates: https://en.cppreference.com/w/cpp/language/type_alias 
Mention using a variadic constructor instead of sequence ctor.
Rename row to 'forward declarations' and say they're not necessary in D.
Add row for 'Deducing `this` parameter type'.
Mention using alias param instead of `T&` param.
> Improve template-comparison article

- articles/template-comparison.dd
Fix `static if` example syntax.
Make 2 examples runnable.
Fix & simplify `is` example (the template parameter has to be an alias).
> [articles/template-comparison] Improve D examples

- spec/expression.dd
Change aliasing heading not to be a child of parameter type inference section.
Mention all function literals can be aliased.
Describe template parameters more precisely for a literal with untyped parameters.
Explain that type inference for those literals is done on template instantiation.
> [spec] Improve function literal aliasing docs

- spec/expression.dd
Part of issue 21619.
Also split short syntax section in two.
> [spec] Describe parameter-less function literal

- spec/expression.dd
Also tweak conditional expression note.
> [spec] Bitwise ops require parens in comparisons

- spec/enum.dd
Fix Issue 18578 - First enum value assigned 0 instead of EnumBaseType.init.
Add an example also showing overflow.
@WalterBright suggested fixing the spec rather than breaking existing code:
https://github.com/dlang/dmd/pull/7996#issuecomment-441187130
> [spec] First enum member is converted from 0 to base type

- spec/class.dd
The restriction described no longer exists, and the current D compiler accepts the code in the example without any errors.
> Remove outdated example for class .offsetof

- spec/function.dd
- spec/type.dd
Fix Issue 24210 - Function types are not documented.
Add examples.
Make existing examples runnable.
Use list for kinds of delegate.
Remove C pointer to function syntax as it's no longer supported.
> Improve function (pointer) type docs

- spec/statement.dd
The type of *Expression* does not need to be convertible to boolean when the type of a declared identifier does instead.
Mention `opCast!bool`.
Use PANEL to group identifier form info.
Avoid repetition.
Tweak wording.
> [spec/statement] Improve *IfCondition* docs

- spec/expression.dd
This was deprecated in DMD 2.072.0, but the corresponding spec PR was never merged.
See https://github.com/dlang/dmd/pull/6089
> Document deprecation of 'is' for static arrays

- spec/const3.dd
The rows and columns now list qualifiers and qualifier combinations in the same order, and match the order used in the "Combining Qualifiers" section.
> Use consistent order for qualifiers in conversion table

- spec/declaration.dd
Also add some links.
C-style declarations are illegal, not deprecated.
> [spec] Add rationale for not supporting C-style declarations

- spec/expression.dd
Fix Issue 24177 - Array literal can implicitly convert to an expected type.
Use this feature to avoid casting elements manually in example.
Also extend array literal to static array example.
> [spec] Array literal can implicitly convert to an expected type

- spec/statement.dd
Show grammar for signature.
Don't require `ref` delegate parameter.
Explain non-`ref` _ForeachType_ can match a `ref` _OpApplyParameter_.
> [spec] Improve `opApply` docs

- spec/enum.dd
An enum derived from a struct type bypasses its base type's copy constructor, postblit, and identity opAssign overloads (if any). This behavior is a special case, and does not apply to other operator overloads or special member functions of the base type (e.g., destructors), so it should be documented explicitly.
> Document enum copying and assignment behavior

- deprecate.dd
- posix.mak
- spec/glossary.dd
- spec/legacy.dd
- spec/windows.dd
Also:
`-wo` does nothing after https://github.com/dlang/dmd/pull/15612, comment it out.
Remove non-standard macros.
Fix empty paragraphs.
Fix missing/wrong Previous/Next items.
> [spec] Fix missing legacy.html

- spec/template.dd
Prefer using TypeSeq for variadic template functions. Mention returning `Tuple`.
Add subheading and example for lvalue sequences.
Minor tweaks.
> [spec] Improve value sequence docs

- spec/declaration.dd
- spec/legacy.dd
As of last month the `-wo` switch does nothing, but I think it's still valuable to explain which features shouldn't be used in new code. These can then become errors in future editions (and perhaps revive the `-wo` switch for warnings in an older edition).
Please let me know if there are any other obsolete features that should be listed here.
> [spec/legacy] Add old alias syntax and postblit

- spec/declaration.dd
- spec/type.dd
For https://github.com/dlang/dmd/pull/15805.
~~Remove now deprecated function type aliases with TypeCtor from example.~~
> [spec] Update function type grammar

- spec/declaration.dd
- spec/type.dd
Follow up to #3706.
Link to function types.
Split function pointer type alias example into 2, rename functions. 
Use `GRAMMAR_INFORMATIVE` for function (pointer) types as it's not supposed to be part of the official grammar (i.e. it shouldn't be in `spec/grammar.html`).
Function type grammar is not part of *Type*.
A function type can also be used to declare a pointer target type.
Simplify function pointer/delegate grammar with *Type* .
Show relation between function type and function pointer type.
> [spec] Improve function type (alias) docs

- .circleci/run.sh
- posix.mak
Manually set the number of jobs used by build.d on CircleCI, because the automatically calculated number of CPU cores is too high.
This depends on https://github.com/dlang/dmd/pull/15799.
> Fix issue 24239 - dlang.org tests on CircleCI run out of memory

- spec/enum.dd
DDoc only allows a single whitespace character between macro arguments, so the combination of newline and indentation caused unintended whitespace to be emitted into the HTML output.
> Fix links in "Enum Copying and Assignment"

- spec/class.dd
Before they were mentioned in the middle of the synchronized class docs, but it's easier to understand the latter after explaining synchronized methods.
Explain how they work.
Add example.
> [spec/class] Update synchronized method docs

- spec/function.dd
"d2 is unsafe because it goes beyond a's bounds" is incorrect in the present version of this page, because slice `0..3` is non-inclusive, meaning that the slice is actually valid. (`a.ptr[0..3]` == `a[0..$]`)
This is probably just a minor oversight about the range's end value being non-inclusive.
> Correct mistaken range violation in spec/function.dd

- posix.mak
Use `build.d` instead, via the `bootstrap.sh` wrapper.
> Avoid deprecated compiler Makefiles

- spec/template.dd
Separate template instance grammar from template argument grammar (unchanged).
> [spec] Explain template instance and template argument grammar

- spec/expression.dd
- spec/function.dd
- spec/struct.dd
Follow up to #3744.
Minor tweaks.
Use numbered lists to describe argument matching.
Fix SPEC_RUNNABLE_EXAMPLE_FAIL example syntax (a good example of why using that macro is bug-prone).
Add asserts to examples.
> [spec] Tweak named arguments docs

- spec/statement.dd
This PR changes the specs for SwitchStatement to include that the condition of a switch statement now can also be a declaration. See dlang/dmd#15656 for more infos.
> Change spec for SwitchStatement to include changes introduced in dlang/dmd#15656

- spec/declaration.dd
The second example mentions that aliasing a member of a type instance will be deprecated - that is implemented here: https://github.com/dlang/dmd/pull/15863.
> [spec/declaration] Document field aliases

- spec/lex.dd
Move _OctalDigit_ out of literals section (not used there). 
Format decimal/binary/hex literal grammar separately.
No changes to actual grammar.
> [spec/lex] Tweak integer literal grammar formatting

- js/listanchors.js
Currently, when you view an archived version of dlang.org site via docarchives.dlang.io, you can (1) only go further back in time, and (2) the master/stable options only refer to the current archived version.
This change lays down the foundations to allow going both forwards and backwards between dlang versions, and the master/stable options now point at the main dlang.org site, so you can go from whatever archived version to mainline in one click.
> listanchors.js: Match both dlang.org and docarchives.dlang.io in version selector

- js/listanchors.js
All archives up to 2.106.0 have been generated and uploaded.
https://docarchives.dlang.io/v2.106.0/
https://docarchives.dlang.io/v2.105.0/
https://docarchives.dlang.io/v2.104.0/
https://docarchives.dlang.io/v2.103.0/
https://docarchives.dlang.io/v2.102.0/
https://docarchives.dlang.io/v2.101.0/
https://docarchives.dlang.io/v2.100.0/
> bump currentArchivedVersion to v2.106

- js/show_contributors.js
Druntime now lives in the dmd repository.
We want it to query for example
https://contribs.dlang.io/contributors/file/dlang/dmd?file=druntime/src/object.d
and not
https://contribs.dlang.io/contributors/file/dlang/druntime?file=src/object.d
(which returns an empty list)
> Fix path for querying druntime contributions

- spec/expression.dd
- spec/lex.dd
Hex strings were added back into the language, with new semantics discussed at DConf 2023.
This reverts https://github.com/dlang/dlang.org/pull/3244 and documents the behavior of https://github.com/dlang/dmd/pull/15567 and https://github.com/dlang/dmd/pull/16079
> Document hex strings

- spec/arrays.dd
Add links.
Minor tweaks.
Improve`dup` example.
Use `string` alias first then explain what it means. Don't repeat example.
Make string ops example runnable.
Move UTF-8 etc to Unicode section & make table showing alias names.
Add 3 subheadings.
Move pointer to char paragraphs down to the zero-terminated string info, add example.
>  [spec/arrays] Improve string docs

- spec/importc.dd
Document the addition of function-like macro support.
> ImportC: function-like macros

- spec/istring.dd
InterpolatedTokenStringTokenNoBraces is not defined. Instead use InterpolatedTokenStringToken, so the string can also end with braces.
> Fix grammar for InterpolatedTokenStringTokens

- download.dd
The present link points to my previous project that contains Nix derivations (package descriptions) for different compiler versions (as opposed to the official NixPkgs derivation which gets you what compiler version there happens to be).
However, since then I've joined @petarkirov in developing his project, that has all the same aims as mine and more along the way (such as dub and ldc support, separate binary and source derivations, and support for Nix flakes). I don't have any reason to maintain my old project anymore, so it's better for the link to point to our joint project instead.
I also chose to update the link description a bit. it's not so much about "building various versions yourself" anymore, since the joint project supports cached builds for anyone using Nix flakes.
> Replaced the link to obsolete oldDDerivations with link to dlang.nix

- spec/property.dd
Move examples below descriptions.
Move `.init` values to `.init` section, add values for other types and short rationale.
Add link to enum properties.
Add Wikipedia link for NaN and mention other bit-patterns.
Make examples compilable.
> [spec/property] Improve docs

- spec/declaration.dd
Add *Initialization* heading after *Declaration Syntax*. 
Move *Initializer* grammar here & add legacy anchor.
Move void init section here, change to H3.
Change auto-declaration heading to H3.
Move global init section here, change to H3.
No changes to content *in the first commit*.
---
Describe initializers, add links.
> [spec/declaration] Group Initialization sections together

- spec/function.dd
Fix wrong 'not allowed...: no' double negative.
Casting between pointer types is allowed under certain conditions. 
Use sub-list formatting.
Don't allow accessing `@system` variables (I think these aren't documented yet).
Make array bounds exception a note.
> [spec/function] Improve safe function spec

- spec/class.dd
- spec/property.dd
- spec/struct.dd
Add links to `.init`.
Fix struct `.init` link to *default* struct initialization. 
Specify what happens when a struct member initializer without a specified identifier follows one with an identifier.
Specify that a union member initializer without identifier refers to the first member.
Before these 2 behaviours had to be inferred from the examples.
> [spec/struct] Clarify static initialization

- spec/template.dd
Specify a ValueSeq can be copied, assigned and compared. 
Specify a ValueSeq cannot have its address taken.
Make example runnable rather than just compilable. 
Specify ValueSeq initialization from a single expression. 
Add example showing expression init and tupleof.
> [spec/template] Improve value sequence docs

- spec/class.dd
Use panel for rationale section.
Tweak formatting.
Show example line is an error.
BTW I think the docs for StaticConstructor and StaticDestructor should be moved to module.dd, I might do that in another pull.
> [trivial] [spec/class] Tweak `static this` docs

- spec/expression.dd
Add links.
`.` PostfixExpression *and* Module Scope Operator (using `or` it can read like the latter is an alternative name).
Move operator overloading below built-in operators. 
Fix conditional typo and allow field alias this to be an lvalue too. 
Use *TypeCtors* for CastQual.
> [spec/expression] Tweak lvalue section

- changelog/2.101.0.dd
Fix typo so google finds searches for it.
> [2.101 changelog] Fix `-preview=fixImmutableConv` entry

- spec/interfaceToC.dd
This is one of the first pages new users land on when searching for "dlang c interface" or "dlang c binding", so it's important to point them to the right pragmatic direction instead of going straight into the manual / low-level way. 
https://forum.dlang.org/post/jenrwaimqbwnlzsqnozt@forum.dlang.org
Also shorten the first paragraph, I don't think the point about VMs is very interesting these days.
> Mention ImportC in interfaceToC.dd

- spec/class.dd
- spec/property.dd
- spec/struct.dd
- spec/template.dd
Move class table to class.dd.
Add subheading for tupleof, update links.
Add links to other properties.
struct.dd: Remove struct sizeof as sizeof is for all types, no need to list here as well.
> [spec] Improve built-in property docs (part 2)

- spec/function.dd
1. Mention safe context and globals for preconditions. 
Part of Bugzilla 24098 - Safe variable can be initialized from `@system` static constructor.
3. `@trusted` functions can create unsafe values/aliasing so long as they are not accessible from `@safe` code. E.g. setting a `@system` field.
> [spec/function] Fix Safe Interface definition

- spec/cpp_interface.dd
This PR is to propose an addition for Platform compiler support header to `cpp_interface.dd` file being the interfacing to C++ reference page. Might be verbose but I think it's needed especially for beginners. I remember nearly giving up when I started fresh with C++ interop because I was running my C++ code with g++ on windows and being linked to my D code compiled with DMD. It was a next level headache being a beginner.
so it can just be a simple instruction to let users know that the following documentation works with this compiler1-compiler2 pair on platform A. Ditto for platform B and platform C.
@Geod24
> entry draft for a possible new header for platform compiler support

- spec/cpp_interface.dd
- spec/interfaceToC.dd
Also fix 'preferrably', 'extention' typos.
> [spec] Avoid using 'you'

- deprecate.dd
I'm not sure when they were undeprecated. _Edit_: https://github.com/dlang/dmd/pull/15393, so probably 2.106, though they're not mentioned in the changelog.
E.g. they're mentioned in this changelog:
https://dlang.org/changelog/2.108.0.html#dmd.hexstring-cast
Also fix `asm` attribute error column.
> [deprecate] Hex strings are no longer deprecated

- deprecate.dd
Update with these changelog items:
https://dlang.org/changelog/2.104.0.html#dmd.throw-qualifier
https://dlang.org/changelog/2.106.0.html#dmd.catch-immutable
> [deprecate] Add items for throw/catch object qualifiers

- articles/faq.dd
Link was broken,  original link was old enough that redirect no longer applied.
> Update faq.dd to fix broken link to Kahan's paper on Java floats.

- spec/attribute.dd
The spec has a heading for a '@synchronized Attribute'. No other part of the spec prefixes this keyword with an at-sign, and according to DMD on run.dlang.io:
```d
@synchronized class Test{}
//onlineapp.d(3): Error: `synchronized` is a keyword, not an `@` attribute
```
> [spec] Remove @ from keyword attribute

- spec/type.dd
This is an additional commit to fix the invalid link.
As before, it has not been checked for correct operation.
> Fix invalid link

- spec/expression.dd
Add `.` and `(args)` entries in the operation table. 
List which type instances can be called.
> [spec] Improve PostfixExpression docs

- spec/expression.dd
Refactor PrimaryExpression with LiteralExpression. This makes it easier to read the other rules.
Add table showing key unnamed multiple-token rules.
> [spec] Improve PrimaryExpression docs

- spec/class.dd
- spec/struct.dd
Don't list it under 'instance properties'.
It gives a symbol sequence, which is an lvalue sequence when used on an instance.
Add link to hidden fields.
> [spec] `.tupleof` can be used on a struct/class type

- spec/cpp_interface.dd
This PR is an update to the special function header in C++ inter documentation. 
one direct change was to replace `special function` header to `operator overloading` since we have already talked about constructors and destructors.
this is a preview of how it is looking like now
please let me know any suggested changes, thanks!
https://dtest.dlang.io/artifact/website-5388b9dcb36ee1089914e5d68ff0da5d7a87f9a0-ec4cd8bc11f96e39d04ef037f2f1f3e5/web/spec/cpp_interface.html#operator-overloading
@dkorpel @Geod24
> Update to special member functions ddoc in c++ interop

- comparison.dd
Add items:
* GC: manual invocation, `@nogc`
* Functions: `ref`
Reorder items a bit, indent some.
Move:
CTFE -> Metaprogramming
Aliases -> Generic
UDAs -> Other
Generic:
Add foreach, ranges, algorithms, aggregate templates. 
Rename Template Template parameters to alias parameters.
Change links:
Properties (more direct)
concepts (wrong) -> constraints
raii -> glossary more formal than wiki
80-bit -> vague type.html to float.html
Add links.
Add Metaprogramming group with string mixins and static foreach.
Reliability: immutable, @safe.
Add concurrency group: spawn, fibers, parallel, TLS, shared.
Add Types group with struct, union, pointers, tuples. Move enum, 80-bit, complex to Types.
Compat: C statements, importc, betterc.
Other: `with`, documented unittests.
> Expand & improve `comparison.dd`

- spec/template.dd
Use list of argument kinds, add booleans & characters. 
Use '*valid* template value arguments' for clarity. 
Tweak example to use enum instead of function.
> [spec/template] Tweak template value parameters

- spec/function.dd
Move in/out grammar to respective subheadings, easier to read.
Use list for contract expression arguments.
Fix grammar for invalid state sentences.
Fix wording of postcondition best practice.
Mention postcondition identifier is implicitly const. 
Add anchor for example subheading.
Fix Bugzilla 24565 - out contract variable is implicitly const
> [spec/function] Improve contract docs

- changelog/2.109.0.dd
Using updated git mailmap, in https://github.com/dlang/tools/pull/474
```
rdmd -version=Contributors_Lib changed v2.108.1..origin/stable \
--version=2.109.0 --date="$DATE" --output=../dlang.org/changelog/2.109.0.dd
```
> Regenerate contributors in 2.109 changelog

- spec/expression.dd
The original wasn't clear how the runtime check is done, and how the new length is determined.
> [spec/expression] Reword runtime array cast

- spec/iasm.dd
See https://github.com/dlang/dmd/pull/15192.
> [spec/iasm] `asm` cannot be marked `@safe`

- spec/function.dd
Define when casting a runtime array is safe (for `bool[]` see https://issues.dlang.org/show_bug.cgi?id=24582).
Pointer slicing isn't safe.
Union operations on fields with safe types can be safe. 
Bool union field is not safe (https://issues.dlang.org/show_bug.cgi?id=24477). 
Assembler is OK if marked `@trusted` (see #3843).
Casting immutable is OK for basic data types.
Casting immutable/shared can be OK if safe `opCast` defined. 
Bool void initialization is not safe (https://issues.dlang.org/show_bug.cgi?id=20148).
> [spec/function] Improve `@safe` restrictions

- spec/expression.dd
- spec/type.dd
The following are implementation defined for bool:
* Casting runtime array to `bool[]`
* Reinterpreting a byte as bool (e.g. by union field)
* `void` initialization
Note: Only 0 or 1 are safe values:
https://dlang.org/spec/function.html#safe-values
> [spec] Document unsafe bool operations

- spec/arrays.dd
- spec/garbage.dd
- spec/type.dd
`void[]` can't hold tail immutable arrays - adjust wording.
Indexing a void array is illegal AFAICT (can't have instance of void) - remove from docs.
Mention tail qualified void arrays.
Link to array cast.
Extend & split example - show copying and `new`.
Add links to void arrays.
> [spec/arrays] Improve void array docs

- spec/traits.dd
List should not be in paragraph.
Add link.
Fix some plural forms that should be singular.
Add cast needed with `-preview=fixImmutableConv` (https://github.com/dlang/dmd/pull/16583). 
Add example for `isDeprecated`.
Use static asserts instead of writeln.
Add 1 more example for `hasMember`.
Use NOTE macro.
Fix broken paragraph.
> [spec/traits] Improve docs

- spec/function.dd
Removes the duplication of *empty*/`...`/`=` *`AssignExpression`*
```diff
Parameter:
-       ParameterAttributes? BasicType Declarator
-       ParameterAttributes? BasicType Declarator ...
-       ParameterAttributes? BasicType Declarator = AssignExpression
-       ParameterAttributes? Type
-       ParameterAttributes? Type ...
-       ParameterAttributes? Type = AssignExpression
+       ParameterDeclaration
+       ParameterDeclaration ...
+       ParameterDeclaration = AssignExpression
+
+   ParameterDeclaration:
+       ParameterAttributes? BasicType Declarator
+       ParameterAttributes? Type
```
> Reorganize function parameter grammar

- spec/expression.dd
There is no `FunctionLiteralBody1` or `FunctionLiteralBody`, appending 2 is confusing.
> Rename FunctionLiteralBody2 to FunctionLiteralBody

- spec/arrays.dd
- spec/declaration.dd
- spec/expression.dd
It was merged with ArrayLiteral in #3215 - sorry.
Fixes Bugzilla 24634 - Parse error initializing array from expression with StructInitializer.
Add examples.
Move index initializer paragraph to arrays.dd, add subheading.
declaration.dd: Add initializers subheading, move paragraph about default init above it.
> [spec] Restore *ArrayInitializer*

- book/dlang.org.ddoc
- dlang.org.ddoc
- spec/class.dd
- spec/expression.dd
- spec/grammar.dd
- spec/importc.dd
- spec/simd.dd
- spec/type.dd
Because `GRAMMAR_INFORMATIVE` starts with `GRAMMAR`, there are stray ones included in [the grammar spec](https://dlang.org/spec/grammar.html).
> Replace `GRAMMAR_INFORMATIVE` by `INFORMATIVE_GRAMMAR`

- spec/grammar.dd
The second commit in #3860 ([GRAMMAR_SUMMARY → SUMMARY_GRAMMAR](https://github.com/dlang/dlang.org/pull/3860/commits/15d79f53c150249ec7bb404f91cee0114e7fbda3)) destroyed the [grammar.html](https://dlang.org/spec/grammar.html) page. This should fix it.
> Fix Grammar Page

- spec/arrays.dd
The current description is wrong. Capacity includes the existing elements, so for instance if an int[] is length 3 and has capacity 5, appending 5 elements will reallocate, because it would set the length to 8 which is greater than the capacity of 5.
> Clarify capacity documentation

- spec/statement.dd
As [DIP 1046](https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1046.md) *(`ref` For Variable Declarations)* has been accepted, probably, `ref` (and `auto ref`) should be allowed for the condition in `if`, `while`, and `switch` statements:
```d
int** pptr = …;
if (ref int* ptr = *pptr) …;
```
Of course, the condition tests whether the variable (`ptr` in the example) is `true`-like, not whether the reference is a non-null reference. In the example, it tests `ptr !is null`, and **not** `&ptr !is null` (or, equivalently, `pptr !is null`).
```d
if (auto ref x = mystery()) …;
```
Especially in template contexts, `auto ref` could be used to make `x` be a `ref` if `mystery()` returns by reference, but a value otherwise.
> Allow `ref` and `auto ref` in `IfCondition` declarations

- spec/memory-safe-d.dd
Emphasise that trusted functions have a safe interface - mention this first as people on the forum seem to have missed it sometimes.
Add link to attribute inference.
> [spec/memory-safety] Tweak system/safe/trusted docs

- spec/function.dd
`bool` is only one kind of unsafe value (see https://github.com/dlang/dmd/pull/16625).
`@system` variables never have safe values.
> [spec/function] Update @safe spec for safe values

- spec/function.dd
Group paragraphs in a panel.
Tweak comments of struct method example.
Unfortunately examples can't be runnable as there's no way to include `-preview=dip1000`.
> [spec/function] Add example for `ref return` void free function

- spec/memory-safe-d.dd
Fix Bugzilla 24659 - Memory safe D page lacks information on return ref.
Reword `return scope` docs (before this was just listed as `return`). 
Move sentence about constructor `return` attribute after method attribute.
> [spec/memory-safe-d] Improve `return` attribute docs

- ddoc/source/preprocessor.d
Remove unrecognised `--output` option in usage.
Remove unused `Config.outputFile`.
> [ddoc preprocessor] Update usage

- ddoc/dub.sdl
We only need a single module, and it's totally isolated too - for now.
Besides somewhat speeding up the ddoc_preprocessor tool build, the main advantage is that we lift the dependency on DMD's `dub.sdl`. The build is currently using a stable dub v1.17, and this limits what we can do with DMD's dub.sdl, such as requiring newer dub versions, what I'd need in https://github.com/dlang/dmd/pull/16756.
> ddoc_preprocessor: Don't depend on entire DMD frontend, only include single `dmd.cli` module

- ddoc/dub.selections.json
- dpl-docs/dub.selections.json
Just to fix dub warnings like
```
Selected package dmd >=0.0.0 @../../dmd doesn't exist. Using latest matching version instead.
```
> Remove dub.selections.json left-overs wrt. removed dmd dependency

- spec/expression.dd
In the function literal grammar, it says that after the `function`/`delegate` keyword and optionally `ref` or `auto ref`, there can follow a general [*`Type`*](https://dlang.org/spec/type.html#Type):
<pre>
<i>FunctionLiteral</i>:
function <i>RefOrAutoRef</i>? <i>Type</i>? <i>ParameterWithAttributes</i>? <i>FunctionLiteralBody</i>
delegate <i>RefOrAutoRef</i>? <i>Type</i>? <i>ParameterWithMemberAttributes</i>? <i>FunctionLiteralBody</i>
…
</pre>
The compiler does not support general *`Type`*, which is <code>*TypeCtors*? *BasicType* *TypeSuffixes*?</code>, but only <code>*BasicType* *TypeSuffixes*?</code>.
> Fix `FunctionLiteral` grammar

- spec/traits.dd
Use list, add link.
Mention it works on an aggregate type or instance.
Remove unneeded ctor, dtor.
Tweak example, use `fooOverloads` alias.
Add comments.
Add example of `getOverloads` on a module.
Fix `writeln` `typeid` method output.
> [spec/traits] Improve getOverloads docs

- spec/attribute.dd
Part of Bugzilla 7616 - aggregates don't inherit pure nothrow from outer scope
Add grammar heading.
Fix brace style.
`@nogc`, `nothrow` and `pure` do not propagate inside aggregates. 
Add example.
Add link to `core.attribute`.
> [spec] Improve attribute propagation docs

- spec/version.dd
See also https://github.com/ldc-developers/ldc/issues/4725
cc @TurkeyMan is Xtensa ESP always 32-bit? What to do about Xtensa-S2/Xtensa-S3? I assume they will be specified in the target triple and any information they provide can be done through other means (e.g. `__traits(getTargetInfo)`)
> [spec] Add reserved version for Xtensa architecture

- spec/expression.dd
- spec/struct.dd
List pointer as a valid left operand of dot expression. 
[struct.dd] Add panel explaining access of a member of a struct pointer.
> [spec/struct] Document pointer to struct dot operator

- spec/expression.dd
Add 2 paragraph tags.
Add subheadings and move best practice/implementation defined notes to relevant places.
Add example for prefix/postfix increment.
Use ordered list for function call evaluation.
> [spec/expression] Tweak Order of Evaluation

- deprecate.dd
- spec/type.dd
Also list `std.int128`.
~~Add `TROW_DEPRECATED1` macro (the `<del>` tag of `GDEPRECATED` doesn't work outside of `<td>`).~~
Mark cent/ucent as deprecated in basic types & add note under table.
> Update cent/ucent deprecated docs

- spec/expression.dd
`typeof(expr, expr)` is an error, so remove sentence about result type. 
Add example.
Add rationale for disallowing use of result.
> [spec/expression] Improve CommaExpression docs

- articles/faq.dd
- dlang.org.ddoc
writef replaces printf, not writefln.
Add `RUNNABLE_EXAMPLE`s.
Use monospace for printf specifiers.
Add `stdio` import.
Mention `pragma(printf)`.
Add pitfall about casting string length to int.
Show string literal with `%s`.
Fix Bugzilla 24732 - FAQ article is out of date on calling printf.
> [spec/faq] Improve printf docs

- spec/arrays.dd
Introduce .length property before use.
Tweak array length example.
Link .ptr property to assignment section.
Make properties example compile & demonstrate .dup.
> [spec] Improve array properties docs

- spec/arrays.dd
Clarify that capacity is only for GC allocated *array* memory. 
Explain `reserve`.
The runtime uses the last element in a slice rather than just the number of appended elements to calculate capacity.
Link to Appender.
> [spec] Improve array capacity docs

- spec/arrays.dd
- spec/expression.dd
Allocating an array requires a length argument. 
Split example in 2.
Add asserts.
Add link to NewExpression from array page.
> [spec/expression] Tweak `new` docs

- spec/importc.dd
The new pragma is implemented in https://github.com/dlang/dmd/pull/16820. The documentation is based on the changelog entry.
> Document new ImportC pragma for setting attributes

- ddoc/source/preprocessor.d
- spec/istring.dd
Stop the lexical grammar sections being included in the parser grammar page.
> [spec/istring] Use GRAMMAR_LEX

- spec/importc.dd
Add some inline code formatting.
CCODE shouldn't be inside a P invocation.
Use RELATIVE_LINK2 to support non-HTML targets.
Remove duplicate `__buildins.di` heading (first one is https://dlang.org/spec/importc.html#_builtins).
> [spec/importc] Tweak docs

- spec/expression.dd
- spec/function.dd
- spec/garbage.dd
Add link to scope parameters for array literals.
Add preview caveat for scope slice initialization from array literal. 
Use IMPLEMENTATION_DEFINED for allowing `@nogc` scope arguments.
garbage.dd:
Link to array literal `@nogc` uses.
Mention `@nogc`.
> [spec] Tweak GC allocating operations docs

- spec/template.dd
For template alias parameters, [specialization](https://dlang.org/spec/template.html#TemplateAliasParameterSpecialization) and [default](https://dlang.org/spec/template.html#TemplateAliasParameterDefault) are simply stated as optional, but for template [type](https://dlang.org/spec/template.html#TemplateTypeParameter) and [value](https://dlang.org/spec/template.html#TemplateValueParameter) parameters, the optionality of specialization and default are given in 4 different lines. That is inconsistent and unnecessary. Parsing the optional constructs is simple as each has its own specific introducer, `:` for a specialization and `=` for default.
> Simplify template parameter specialization and default

- spec/template-mixin.dd
I haven't checked with the compiler source if this actually holds true, but when trying it out with the compiler I get
```
a.d(10): Error: template instance `foo!()` mixin templates are not regular templates
```
which makes me believe this is how it works. Please correct me if I'm wrong here.
> Spec: specify what a TemplateMixinDeclaration is

- spec/traits.dd
Complement to https://github.com/dlang/dmd/pull/14711
> add __traits(fullyQualifiedName)

- spec/enum.dd
Move enum variables up as they were already used in the implicit conversion example, and remove subheading (keeping anchor).
Move link to `final switch` up too.
Add *Enum Member Values* subheading.
> [spec/enum] Tweak named enum docs

- spec/expression.dd
Tweak cast to struct wording.
Add relative links.
List static opCall as a postfix expression.
Add subheading for expressions that can be called.
> [spec/expression] Tweak postfix/callable expression docs

- spec/expression.dd
Also avoid newline with *See also*.
> Fix Bugzilla 24876 - Undocumented cast from slice to static array

- spec/abi.dd
- spec/struct.dd
Also list empty struct size and add example.
> Fix Bugzilla 14945 - unions are missing from the ABI page

- spec/statement.dd
`if (a)` is not always the same as `if (a.ptr)`.
See https://issues.dlang.org/show_bug.cgi?id=4733#c43.
Note: I'm also working on adding a comparison section for arrays.dd, for another PR.
> Fix wrong info on array boolean condition

- spec/expression.dd
- spec/lex.dd
This adds documentation for `__rvalue(PrimaryExpression)`. Once it is merged, I'll add documentation for move constructors.
> add RvalueExpressions

- spec/class.dd
- spec/function.dd
- spec/struct.dd
- spec/template.dd
Fixes #4101.
I think this is more natural - as a prototype does not have a body, so why would it be grouped under something called _FunctionBody_.
Changing the definition resolves an inaccuracy in the spec here:
> A disabled default constructor may not have a FunctionBody.
https://dlang.org/spec/struct.html#disable_default_construction
Which becomes valid with this pull.
I also noticed that [AutoFuncDeclaration](https://dlang.org/spec/function.html#AutoFuncDeclaration) seems to be the only kind of function declaration that gives a parse error on a _MissingFunctionBody_ - `static this()` doesn't (I suppose the body definition could be added at link time).
> [spec/function] Remove MissingFunctionBody from FunctionBody

- spec/attribute.dd
Fix TOC for C++ namespaces.
Improve `@disable` example.
Don't group `ref` and `return` under function attributes, because they also apply to parameters.
> [spec/attribute] 3 Tweaks

- spec/struct.dd
> add move constructor documentation

- spec/property.dd
Make `stringof` example runnable.
Show `stringof` on a symbol - module name.
Make it clearer `stringof` on expression doesn't evaluate expression. 
Simplify `sizeof` example and make runnable. Add assert for class reference size.
Add link to `classInstanceSize` trait.
Add link to `align` example for `alignof`.
> [spec/property] Improve stringof/sizeof/alignof docs

- spec/property.dd
Separate symbol properties (`stringof` & `mangleof`) from common type properties. 
Add numeric properties heading for integer and floating point types.
Explain how the common type properties apply to expressions. 
Separate derived type properties and user-defined type properties & add subheadings.
> [spec/property] Add headings

- bugstats.dd
> Updated bugstats.dd to reference GitHub Issues

- spec/function.dd
Or [will be](https://dlang.org/changelog/2.111.0.html#dmd.deprecation-typesafe-variadic-class) anyway.
> [trivial] [spec/function] Variadic class parameters are deprecated

- changelog/prerelease.ddoc
I have trouble uploading the new index of downloads.dlang.org to backblaze, so the link to that doesn't work. In the mean time, point to the website's download page instead, which does work.
> Fix pre-release download link

- spec/expression.dd
The text of the warning pretty much says it all. `mixin(__FUNCTION__)` is an unreliable way to get a function's symbol and should not be used - but it seems to be a common solution to the problem given that we don't currently have a way to get at the symbol directly. So, this adds a warning against using `mixin(__FUNCTION__)` and explains how to do it in a reliable way instead.
As might not be obvious from the diff, the warning is added at the end of the section describing `__FUNCTION__`, `__FILE__`, `__LINE__`, etc.
> Fix issue #4191: The spec should warn against using mixin(__FUNCTION__)

- spec/struct.dd
Until https://github.com/dlang/dmd/issues/20970 is fixed, we need to be warning against the use of copy constructors rather than warning against the use of postblit constructors.
So, I fixed the warning and put both it and the description of what happens when mixing postblit constructors and copy constructors together on both the section for postblit constructors and the one for copy constructors.
I suspect that move constructors merit a similar warning, but I'm not sure what their current state is, so this just fixes the warning for postblit constructors and copy constructors.
> Fix issue 4184: The spec should warn about using copy constructors.

- spec/function.dd
Switch the terms "former" and "latter" around. Currently the spec sets "former" to variadic delegate array element access causing evaluation of the other array elements, and "latter" to the lazy variadic array element access only evaluating that element. This is contrary to the example code so we just need to switch the positions of "former" and "latter" in the sentence.
> Update function.dd (Lazy Variadic Functions)

- spec/class.dd
Also qualify that only *initial* hidden fields are skipped for `.tupleof`. (Perhaps we should specify that the context pointer is included in it).
> [spec/class] Add links to ABI and context pointer in Hidden Fields section

- articles/ctod.dd
Add a simpler example for dynamic array extension. The given example is confusing by its verbosity.
> Add simpler example in C to D page

- spec/class.dd
Make Constructors a subheading of Class Instantiation instead of the reverse, because:
* `new Object` is valid and `Object` has no constructor (declared anyway)
* Explaining how to create a class instance before the details of e.g. delegating constructors etc helps with reading the section from top to bottom.
* Field initialization was listed under Constructors, but also applies for `new C` when there isn't a constructor.
Explain when arguments to `new` are required, and how constructors are matched.
Add relative link to class invariants.
> [spec/class] Improve construction docs

- articles/ctod.dd
Add another example of string lookup using associative array. It allows to introduce AA type that a pure C developer would not expect as a builtin in language.
> Add example of associative array

- articles/ctod.dd
In the example the element was wrong.
> Fix typo in ctod.dd

- spec/expression.dd
- spec/operatoroverloading.dd
Fixes #4217.
Add summary with correct info for class references. 
Add subheading for structs.
Move best practices macro down a bit.
Remove text about needing `is` to compare against null.
Tweak `is` docs for comparing class reference to null. 
Add operatoroverloading.dd link to struct equality best practices.
> [spec/expression] Improve EqualExpression docs for classes

- spec/operatoroverloading.dd
Also fix wording on selecting better `opEquals` overload.
Fixes #4220.
> [spec/operatoroverloading] Add class `opEquals` example

- spec/expression.dd
- spec/operatoroverloading.dd
Fixes #4224.
Also briefly describe struct comparison.
Update example - comparing null is not a runtime error.
> [spec/expression] Document class comparison with `object.__cmp`

- spec/function.dd
Make it clearer that `in` does have meaning without the preview switch.
Remove unnecessary COMMA use.
Add link to scope params.
Add example.
Use list for defined pass-by-reference behaviour.
> [spec/function] Improve `in` parameter docs

- spec/attribute.dd
- spec/function.dd
Also make an example's method `@safe` that mentions inferred scope.
> [spec] Add notes for `scope` attribute/parameter about `-preview=dip1000`

- spec/expression.dd
- spec/operatoroverloading.dd
Fixes #4222.
Use RelExpression instead of 'inequality operators', as inequality is used to mean `!=`.
Clarify that the compiler only generates a default `opEquals` for structs.
> [spec/operatoroverloading] Fix comparison docs wording

- keywords.ddoc
- posix.mak
While ddoc will color keywords as keywords in code examples, it won't do so with `$(D )` or \`\`. To highlight them as keywords, you need to use `$(D_KEYWORD )`, but typing out stuff like `$(D_KEYWORD typeof)` or `$(D_KEYWORD @property)` gets pretty verbose, especially if the keyword is mentioned several times in a paragraph.
So, this adds macros for the keywords so that you don't have to type all of that out to get the same effect. So, instead of `$(D_KEYWORD typeof)`, it would be `$(K_TYPEOF)`. Instead of `$(D_KEYWORD @property)`, it would be `$(K_PROPERTY)`. Etc. Each keyword has a similar macro and is thus similarly shortened.
> Add macros for keywords.

- spec/template.dd
First state that an element can be modifiable.
Clarify that the elements only need to be compatible (not equal types) in a binary expression. 
Update example.
> [spec/template] Improve lvalue sequence element docs

- spec/operatoroverloading.dd
Fix formatting.
Fix comment about `opSlice` lowering.
Fix `opDollar` example.
> [spec/operatoroverloading] Improve examples

- spec/lex.dd
Fixes #4149
I've added the missing fourth form to the HexFloat grammar definition,
`
HexFloat:
HexPrefix HexDigitsNoSingleUS . HexDigitsNoStartingUS HexExponent
HexPrefix . HexDigitsNoStartingUS HexExponent
HexPrefix HexDigitsNoSingleUS HexExponent
HexPrefix HexExponent
`
This change documents the existing behavior of the D compiler, which already accepts the 0xp1 syntax. The value of a hex float literal in this form is interpreted as zero (0) shifted left by the exponent value. Also, rather than deprecating the syntax, I've updated the specification.
> Fix for Issue #4149, Added undocumented HexFloat syntax to the specification

- spec/version.dd
Add short description sentence.
Use list formatting.
Use *element 'variable'* instead of just _variable_. 
Tweak whitespace in examples.
Make 2 examples runnable.
Link to sequence foreach.
Change `switch` examples to only generate 5 case statements (reducing test overhead).
> [spec/version] Improve static foreach docs

- spec/statement.dd
Improve wording.
Explain that `front` can be `ref`, add example. Fixes #4241.
Rename node variable.
Also don't include OpApplyDeclaration in `spec/grammar` page.
> [spec/statement] Improve `foreach` for ranges docs

- spec/version.dd
Adding a bit more structure helps with understanding them.
> put predefined version identifiers into categories

- spec/class.dd
- spec/expression.dd
> [spec/class] Inside non-static method, member vars are in scope

- spec/function.dd
Forbid optimizations which assume a null dereference will not occur. `ldc2` does use those optimizations with `-O2` - see:
https://forum.dlang.org/post/vv6o31$ac9$1@digitalmars.com. Fixes #4240.
Cc @tgehr @WalterBright.
Specify that the code generated must detect null dereferences if the system (by default) does not.
Specify that the code generated must detect when any expression causes a null pointer to be indexed outside the protected first page. Include warning that `dmd` does not implement this yet - see https://github.com/dlang/dmd/issues/17776.
> [spec/function] Specify null dereference behavior for `@safe` code

- spec/type.dd
Use GDEPRECATED macro like for cent, ucent.
Add link.
> [spec/types] Tweak docs for deprecated complex types

- spec/version.dd
Reorder grammar more usually.
Add link to _ForeachType_ for variables. Fixes #4109.
> Tweak static foreach docs

- spec/arrays.dd
Closes #4263
It's not a best practice and only confusing, see issue
> Remove confusing 'best practice' of 0 size arrays

- 404.dd
- book/d.en/404.d
- book/dlang.org.ddoc
- dlang.org.ddoc
Fixes #4266.
I also added a space after the square brackets in the pre-filled bug title, ready for people to type more.
> Fix BUGZILLA_NEW_BUG_URL macro to use github

- spec/statement.dd
> static foreach is not the same as foreach for sequences

- areas-of-d-usage.dd
As described here: https://news.ycombinator.com/item?id=44724714
the link for Quantum Break is broken. I updated for the new link.
> Update areas-of-d-usage.dd for broken Quantum Break link

- spec/pragma.dd
The .stringof property attempts to mangle the type as the string literal "MyClassA!(int)", which isn't what the example expects.
> spec/pragma: Fix example for pragma(mangle)

- spec/function.dd
One `return` is required *per execution path*. Fixes #4295.
~~Don't mention `assert(0)` as that is covered by the `noreturn` case.~~
Add missing return example.
Clarify return value being an rvalue.
> [spec] Improve Function Return Values section

- spec/expression.dd
- spec/type.dd
- The type of `assert(0)` is noreturn.
- Also clarify note about CTFE not being attempted.
- `noreturn.init` lowers to `assert(0)`.
- A function returning type `noreturn` is covariant with a function returning any other type.
See also `throw`.
Fixes https://github.com/dlang/dlang.org/issues/4297.
> [spec] Improve `noreturn` docs

- spec/type.dd
Explain usage, mention *PrimaryExpression*.
Make example compilable & extend.
Mention `typeof(null)`.
Add subheading for special cases.
> [spec/type] Improve `typeof` docs

- spec/statement.dd
Make 2 examples runnable.
Add `writeln` calls to show `switch` execution path. 
`goto` cannot skip *within its scope*. Fixes #4310. 
Add *Best Practice*.
> [spec/statement] Improve `goto` docs

- spec/function.dd
Move `core.stdc.stdarg` sentence to where it's actually used. 
Make examples runnable, add `writeln` calls.
Add links.
Fix link to typesafe variadics.
Remove `void*` from `_argptr`. Fixes https://github.com/dlang/dmd/issues/21884. 
`_argptr` is a pointer, not a reference.
Print the class member variables in last d-style example (the old output wasn't the class reference address anyway).
D-style variadics can be `@safe` if they don't call `va_arg` (though not very useful).
A typesafe variadic parameter must be last.
> [spec/function] Improve variadic function docs

- spec/template.dd
Show inferred template parameter types for recursion.
Mention *deduced from the parameter list*.
Add simpler example.
Simplify `partial` example.
> [spec/template] Improve type sequence deduction docs
