dlang/dlang.org

expression.dd

https://issues.dlang.org/show_bug.cgi?id=3652
Even if a poor D compiler does not support any const-folding, `arr[1 .. 3]` should be convertible to `T[2]`. This PR will add the minimum requirement for the feature.

Issue 3652 - Allow explicit and implicit casting of dynamic array slices of known size to static array

---

win32.mak

Note: `posix.mak` already uses it - see https://github.com/D-Programming-Language/dlang.org/pull/733/files#diff-8.

Use needed dlang.org.ddoc for HTML generation on Windows

---

latex.ddoc
lex.dd

A couple small changes:
1) Remove extra comma, and add a + for a U+0000007F
2) Change the link color from red -> blue
3) Make sure that table headers are on the same page as their tables.

Formatting fixes to PDF generation

---

posix.mak

- pre-3.8.2 make uses first matching pattern rule
- since 3.8.2. best match is used

fix order of pattern rules

---

dlang.org.ddoc

In a recent PR for Phobos (https://github.com/D-Programming-Language/phobos/pull/2817) I was advised not to use LINK2 for a link and that FULL_XREF would be better. Unfortunately, I borked the syntax. After figuring out where all the relevant macros are defined, I learned that FULL_XREF isn't what I want anyway. It simply passes its arguments on to XREF as-is. XREF creates a link to $2, also using $2 as the link text. In the context of my PR, I don't want $2 as the link text (i.e., I want the text to be "forward range" rather than "isForwardRange.") To avoid going back to LINK2, which is easily broken, I've added the macro XREF2 which takes three args like this:
```
$(XREF2 range, isForwardRange, forward range) 
```
And gives me the format I want.

Add XREF2 macro

---

garbage.dd
index.dd
overview.dd

https://issues.dlang.org/show_bug.cgi?id=13547
Supercedes https://github.com/D-Programming-Language/dlang.org/pull/666 - I squashed those commits together, then made the suggested edits in a separate commit. I also weakened some of the wording on downsides of GC in the 3rd commit, because:
* AIUI, the GC only collects when making an allocation (it doesn't interrupt).
* A D GC could do partial collections, preventing long pauses.
* Threads not managed by the runtime do not necessarily have to be paused when collecting garbage.

Fix Issue 13547 - "D is a fully garbage collected language"

---

css/style.css
dlang.org.ddoc
js/listanchors.js
posix.mak
std.ddoc

https://issues.dlang.org/show_bug.cgi?id=5136
Show only top-level symbols in the main module jump-to links, with remaining symbols shown in separate jump-to lists before their respective parents.
Show non-top-level jump-to links even when `inhibitQuickIndex` is set.
Show all jump-to links with same background color as symbol declarations.
Note: std.typecons, std.stdio and std.container.rbtree are nice modules to test this with.

Use hierarchical Jump-to links

---

css/style.css

When using `min-width` with `60em`, some users that use large fonts would have a very unpleasant time because the site has a horizontal scroll bar at about 950px width, which is almost the half of 1920px, which in turn is one of the more common horizontal resolutions out there. This means users who use their browser window on one half of the screen and something else (like a code editor) on the other half would have to deal with a horizontal scrollbar when none was needed.
Please let me know if this change would break someone's workflow who relies on horizontal scrollbars on dlang.org.

Remove min-width to improve look on some devices

---

index.dd

It's currently stall and could be misleading to users.

Remove comment about a beta testing on the front page

---

function.dd

Thanks for the expalanation given by H. S. Teoh at http://forum.dlang.org/post/mailman.1476.1415061701.9932.digitalmars-d-learn@puremagic.com

Add a explanation for function templates that is missing

---

abi.dd

https://issues.dlang.org/show_bug.cgi?id=6574
Improve mangling scheme to distinguish instantiations with specialized template parameters.
If a template argument matches to specialized template parameter, the argument is mangled with prefix 'H'.

Issue 6574 - Erroneous recursive call in template instantiation

---

posix.mak
std.ddoc

Target `verbatim` generates for each ddoc-generated file a corresponding verbatim file, i.e. the file with all macros as they are seen and expanded by ddoc. The '.verbatim' extension replaces the '.html' extension, e.g. http://dlang.org/phobos-prerelease/std_algorithm.verbatim coresponds to http://dlang.org/phobos-prerelease/std_algorithm.html.

Verbatim ddoc generation

---

ddoc.dd

This is current with both of my recent dmd pull requests.

Document the new backticked inline code feature in ddoc

---

dlang.org.ddoc

This helps us weed undefined macros by just grepping through the generated content.

Add DDOC_UNDEFINED_MACRO as a comment in the generated file

---

declaration.dd
grammar.dd

https://issues.dlang.org/show_bug.cgi?id=13325
1. Rename `Vector` rule to `TypeVector`
2. Fix `BasicType` rule in declaration.dd to be consistent with grammar.dd

fix issue 13325 - Supplemental change for the pull 774

---

declaration.dd
grammar.dd

https://issues.dlang.org/show_bug.cgi?id=13941
- Fix `Type` rule by using `BasicType2`
It should be consistent with parseType() in dmd code.
- `BasicType2` should handle repetition
It should be consistent with parseBasicType2() in dmd code.

Issue 13941 - NewExpression grammar is insufficient

---

enum.dd
grammar.dd

https://issues.dlang.org/show_bug.cgi?id=10285
This cleans up the enum declaration grammar and makes it more closely match DMD's implementation. Some rules that consisted of a single token were removed, and a new AnonymousEnumDeclaration rule was added to ensure that the "type identifer = assignExpression" syntax cannot appear in non-anonymous or typed enums.

Issue 10285 - Enum grammar documentation is incorrect

---

posix.mak

This will allow nicely documented css files without passing the overhead to the users of dlang.org.

Css minify

---

css/cssmenu.css.dd
js/cssmenu.js
latex.ddoc
std_navbar-2.066.1.ddoc
std_navbar-prerelease.ddoc

Better menus

---

js/cssmenu.js

When you expand one submenu and it collapses another, it can have particularly annoying results. For example, when in the standard library docs, and you want to expand multiple sections (std and core), you cannot. In addition, the following sequence is quite annoying:
1. expand std.
2. expand core.
So when you expand std, it has many entries, scrolling core off the screen. You must scroll down to reach the core menu. As soon as you open core, it collapses std. core has very few entries in it, so the overall size shrinks tremendously. This makes the menu suck itself up off the screen, and now you have to scroll up to get at the submenus.
This fix simply avoids collapsing the already-open menu.

Remove collapse of already-open menu.

---

CONTRIBUTING.md
README.md

Details about contributing should go into CONTRIBUTING.md; README.md should just explain what this repo is about.

Split off CONTRIBUTING.md from README.md.

---

js/run.js

- fix class d_code matcher to ignore additional classes

reenable run example

---

grammar.dd

Currently some links in grammar page jump out from grammar page.
e.g. The `Type` under [EnumBaseType](http://dlang.org/grammar.html#EnumBaseType)
They should be internal links instead.

Directly replace GLINK2 with GLINK in grammar page

---

code_coverage.dd

[Trivial] Remove useless macro

---

css/style.css

With position:fixed lower elements would end up unreachable below the
screen on smaller screens.
body{position:relative} makes it so that #navigation and
#navigation-cancel extend all the way down to the bottom of &lt;body&gt;.

allow scrolling of the mobile navigation

---

css/style.css

before: ![iconscreenshot1](https://cloud.githubusercontent.com/assets/9287500/5846945/5983c0d0-a1c8-11e4-8d48-d1c8c073a3fb.png) after: ![iconscreenshot1](https://cloud.githubusercontent.com/assets/9287500/5846946/5b527122-a1c8-11e4-8085-a5008a735f67.png)

(follow-up to #819) mobile menu: make shadow and cancel area go all the way down, too

---

css/style.css

- drop shadow of logo isn't visible on dark background
so shift the logo down by that amount so it's optically
aligned with the text next to it

align D logo with text

---

css/style.css
index.dd

Integrate forum activity summary into dlang.org front page

---

std_navbar-2.066.1.ddoc
std_navbar-prerelease.ddoc

This appears to have been missing since the previous release, so update both navbars.

Add missing navbar links to std.csv.

---

css/style.css
index.dd

Latest iteration of forum integration

---

dpl-docs/views/ddox.overview.dt

This is not exactly pretty, rather a proof of concept. I think there is more discussion needed.
Also, in order to build it, I need to do
`rm -rf ~/.dub/packages/ddox-0.10.0/.dub; rm web/library-prerelease/sitemap.xml; make -f posix.mak apidocs-prerelease`, which does not seem appropriate either.

Add template for library index

---

css/style.css

This way, the layout is switched not only based on window size, but also
based on the set font-size. E.g. when a user has set the font-size to be
twice as large as usual, the 'mobile' layout will be used for window
widths up to 1600px.

change media query units to em

---

css/style.css

Should be pretty much invisible. Avoids weirdness with extraordinary user-set font-sizes.

px to em for #tool's position

---

css/style.css
index.dd

It slipped through CSS, because it's not an &lt;h1&gt;.
Before/after:

remove margin top from the home page heading

---

std_navbar-2.066.1.ddoc
std_navbar-prerelease.ddoc

Had trouble rebasing.  This is a redo of #827.

Redo #827: Remove first prefix from submenus in library reference

---

css/style.css

Before/after:
As @CyberShadow said in #831, it's somewhat "inconsistent to do it selectively in the main content". So I'm not sure about this.
Phobos modules with manually maintained jump link tables will need to add a class to be affected by this. PR is on the way.

un-underline jump links

---

std_navbar-prerelease.ddoc

Apparently one of the recent PR's accidentally overwrote the new std.algorithm submodules in phobos-prerelease's navbar. Note that this PR only affects phobos-prerelease, the current release still has the original unsplit std.algorithm without submodules.

Add std.algorithm submodules to navbar.

---

grammar.dd

This change synchronizes the AamPrimaryExp grammar between grammar.dd and iasm.dd.

Supplemental fix for issue 13308

---

css/cssmenu.css.dd

Split off from #812.
Before/after:

menu: cast text shadows down, not up

---

doc.ddoc
index.dd

It's the current standard.
http://forum.dlang.org/thread/ju9uin$1g5n$1@digitalmars.com

#d_lang -> #dlang

---

css/cssmenu.css.dd
std.ddoc
std_navbar-prerelease.ddoc

Introduces CSS support for level 4 nesting (sigh).
Supersedes #864.

navbar for std.experimental.logger

---

std_navbar-prerelease.ddoc

Reverts D-Programming-Language/dlang.org#866
#866 and #865 are mutually redundant, and #865 sounds like a better idea.

Remove redundant separate "std.experimental" menu

---

CONTRIBUTING.md
doc.ddoc

I needed to do it to build apidocs-... maybe others will need it too.

Add note to install 'libevent.a' on OSX 

---

html.ddoc

The styling was introduced in #776. I don't know if it was supposed to fix anything or if it's just been a mistake. Anyway, it hit a lot of links that really shouldn't be styled that way.
Exemplary before/after shot of grammar.html:

don't style ALOCAL as permalink to self

---

function.dd

The recent blog post on D as a native python had [a comment saying that they didn't initially get that UFCS enabled function chaining and pipeline programming](http://bitbashing.io/2015/01/26/d-is-like-native-python.html#comment-1818018598).  I've seen this mentioned a handful of times, would be good to explain it a bit in the docs, as it's [a feature that gets people excited](http://www.kr41.net/2013/08/27/uniform_function_call_syntax_in_d.html).
Also, would be good to start moving Walter's Dr. Dobb's articles to dlang.org, as that article's webpage started reloading repeatedly in my browser for some reason.

Mention function chaining as a benefit of UFCS

---

statement.dd

Today `opApply` is preferred than range primitives. The documentation was too old.

Fix foreach doc for the precedence between opApply and range primitives

---

doc.ddoc
getstarted.dd
posix.mak
win32.mak

https://issues.dlang.org/show_bug.cgi?id=14088

add "Getting Started" page to dlang.org

---

doc.ddoc

Assuming someone's around, IRC is a nice medium for a quick Q&A, so I think it's worth featuring it on the website.

Add IRC link to Community menu

---

posix.mak

This does help ddoc generation, but not the ddox stuff. How to I pass a dmd flag to dub? Thanks! cc @MartinNowak

Add -conf= to dmd invocations

---

css/ddox.css
dpl-docs/views/layout.dt
js/ddox.js
win32.mak

Updates layout.dt to the latest dlang.org layout and cleans the dpl-docs executable (and intermediate build files) on `make -f win32 clean`. It also currently forces a rebuild of dpl-docs to work around D-Programming-Language/dub#331. The Posix makefile still needs to receive some fixes/improvements, which is subject to a separate pull request.

Fix DDOX page layout and improve building dpl-docs on win32

---

css/style.css
std.ddoc

This addresses the odd small fonts for the function names in http://dlang.org/phobos-prerelease/std_algorithm_package.html.

Move font selection for links to css

---

css/cssmenu.css.dd
std.ddoc

- missing styles for nested packages without package.d
- added MODULE5 styles for core.sys.posix.sys.*

update style rules for deeply nested packages

---

dlang.org.ddoc

This PR fixes link text generation, e.g. the 2nd paragraph of http://dlang.org/arrays.html#strings-unicode.

Fix PHOBOS macro

---

dpl-docs/dub.json
dpl-docs/dub.selections.json

This pull upgrades to the latest version of DDOX, which fixes the crash. The root cause was a missing termination condition for recursive macro instantiations.

Issue 14258 - SIGSEGV in dpldocs

---

changelog.dd

- we have a link on the download page to the release archive
and the one in the changelog always points to the bundled zip
which is the least suitable download
- use permalink anchors instead
- also cleanup the anchor names (#2.066.1 instead of #new2_066.1)

remove download links from changelog

---

dlang.org.ddoc

- makes the search box the first entriy in the tab order
- use index 1000 to leave room for other tab orders

tabindex for search box

---

changelog.dd

Note: after a couple of hours of trying I didn't manage to get the docs building so these are untested.
First I moved dlang.org alongside the dmd repository (even though it seems to download DMD anyway??), then I fixed DOS newlines in dub's build.sh, then I changed STABLE_DMD_VER in posix.mak to 2.067.0 because I got DMD errors about unrecognized `return`, then curl complained because it tried to look for it in the 2014 subdirectory... am I doing something basic horribly wrong?

Add std.range.enumerate and std.exception.handle to the changelog

---

posix.mak

- output dir might not yet exist in parallel builds

fix parallel builds of dlang.org

---

operatoroverloading.dd

See discussion here: http://forum.dlang.org/post/mfano2$2uuc$47@digitalmars.com

Add D1 style for operator overloading to spec

---

dcompiler.dd

switches are supposed to be in sorted order

move -boundscheck into sorted position

---

getstarted.dd

- it's pretty pointless to link from the
getting started page back to the root

remove self-reference to dlang.org

---

download.dd

https://issues.dlang.org/show_bug.cgi?id=14428

Fix for 14428. Add epub and chm download buttons for the language spec.

---

deprecate.dd

Reasoning:
- Cast T[] to integral type
- The error given is the same for all invalid casts.
- Using length in index expressions
- The error given is "undefined identifier length" and not "use '$' instead of length".
- Variable shadowing inside functions
- This will always be invalid code, and no changes to parsing/semantic will make this anything but.
- Upper case 'I' suffix for imaginary literals
- This will never be gone until complex types leave the language.  Which is as good as never at this point.

Update deprecated features table to reflect errors that are infact also gone

---

function.dd

Fix of issue 14418 ( https://issues.dlang.org/show_bug.cgi?id=14418 ) and an undefined identifier bug in the "C-style variadic function in D" example I found while testing the fix of 14418. I did not fill a bug report for the later.
This is my first pull request. I read http://wiki.dlang.org/Pull_Requests, but I perhaps something important. So any comments are welcomed.
I updated the extern(C) example only for consistency, so 'foo' is void in all examples - the extern(C) example does compile with 
extern (C) int foo(int x, int y, ...);
too, so that change is not important.
An alternative fix would be:
- foo returns int
- add something like "return 42;"
I think that would be rather confusing than helpful.

Fix Issue 14418

---

statement.dd

Reasoning:
```
while (1)
{
try {
break;
}
finally {
goto label;   // Compiler error
return 1;     // Compiler error
}
}
```

Fix a note that no longer reflects how D works

---

deprecate.dd

Overriding without override: https://github.com/D-Programming-Language/dmd/commit/ddead63bc3502113f683dc855afac5bc03777a71#diff-43282ebf5a2de5fdbcb3b5083ddf949dR287
Warn on .sort and .reverse: https://github.com/D-Programming-Language/dmd/commit/dbb24f8ecd31c8e5a03af9008ecd05ba1ec89cb5

More deprecations that were missed/not updated.

---

version.dd

description for the predefined version `D_Warnings`, needed with [https://github.com/D-Programming-Language/dmd/pull/4619](#4619).

added ddoc for #4619

---

posix.mak
win32.mak

- to avoid breakage by broken upstream package descriptions
- workaround for https://github.com/D-Programming-Language/dub/issues/564

update dpl-docs dependencies manually

---

unittest.dd

1. specify order
2. fix link to switch
3. remove redundant `-version(unittest)` doc
4. make statement a bit nicer

minor improvements to unittest.dd

---

glossary.dd

This also seems to clean up some trailing whitespace.

Add 'UDA' to glossary

---

css/cssmenu.css.dd

cssmenu.css.dd was pulling in two extra fonts (carried over from [the original version](http://cssmenumaker.com/menu/modern-jquery-accordion-menu)). I'm not convinced we need them - they're used only for navigation, and thus are a mostly pointless gimmicks that increase page load time.
Before  | After
------------- | -------------

Don't load two additional fonts used solely for site navigation

---

version.dd

Reverts D-Programming-Language/dlang.org#982
The compiler change was already reverted in: https://github.com/D-Programming-Language/dmd/pull/4670

Revert "added ddoc for #4619"

---

posix.mak

Previously, posix.mak assumed libphobos.a inside ../phobos was built and usable with dmd -L-L. As there is no rule in the makefile to enforce this dependency, a clean build of dlang.org would always fail.
This change causes the stable rdmd (which is downloaded and unpacked to /tmp) to be used instead.

Use stable rdmd instead of assuming libphobos.a is built

---

arrays.dd
dlang.org.ddoc
latex.ddoc
std-ddox.ddoc

A PR for phobos follows that uses to this to fix all the broken package links.
A generic XREF variant for arbitrary package depth would be nice. But the best I could think of has a weird parameter order:
```d
XREF_DEEP=$(XREF_DEEP_NAMED std$(XREF_DEEP_PREPEND_DOTS $+,$1),$1,$+)
XREF_DEEP_NAMED=$(SPANC libref,$(AHTTP dlang.org/phobos/$(XREF_DEEP_FILE $+).html#$2,$1))
XREF_DEEP_FILE=std$(XREF_DEEP_PREPEND_UNDERSCORES $+)
XREF_DEEP_PREPEND_UNDERSCORES=$(UNDERSCORE)$1$(XREF_DEEP_PREPEND_UNDERSCORES $+)
XREF_DEEP_PREPEND_DOTS=.$1$(XREF_DEEP_PREPEND_DOTS $+)
```
So I went with another hard-coded version instead.

new XREF variant for sub-packages: XREF_PACK

---

posix.mak

This way changes in druntime/phobos are properly picked up when building
dlang.org. When druntime/phobos haven't changed, their make just does
nothing.

always call make on druntime and phobos

---

changelog.dd

See https://github.com/D-Programming-Language/phobos/pull/3363

Document getUDAs in the changelog

---

posix.mak

- avoids race condition for parallel builds

d.tag depends on druntime/phobos-release

---

abi.dd
dcompiler.dd

Complimentary to  https://github.com/D-Programming-Language/dmd/pull/4732

[dwarf] Remove documentation on outdated dwarf extensions

---

arrays.dd

I've removed the deprecated postfix array explanation and example. The removed example also threw lots of warnings and errors.
A preview of the new page can be seen here:
http://nomad.so/misc/d/dlang.org/issue_14522/arrays.html
Bugzilla:
https://issues.dlang.org/show_bug.cgi?id=14522

Issue 14522 - Postfix array declaration examples should be removed from arrays.html

---

enum.dd
grammar.dd

https://issues.dlang.org/show_bug.cgi?id=13327
This also fixes a DDOC macro usage issue introduced by https://github.com/D-Programming-Language/dlang.org/pull/775/

Issue 13327 - Clarify manifest constant grammar

---

posix.mak

cc @MartinNowak 
Sadly the dependency of `dmd` on `.clone` does not work out.
Consider a user who wants to build `dlang.org` and has a preexisting `dmd` created by other means (i.e. there's no `../dmd/.cloned` directory) and built properly. Then, trying to make dlang.org will follow an unpleasant sequence of events:
1. There's no `../dmd/.cloned` so it will execute the rule for it. The rule uses `touch` to create a `../dmd/.cloned` that is NEWER than the prebuilt `../dmd/src/dmd`. 
2. Following that, the rule attempts to build `../dmd/src/dmd`. The rule will issue `make` in `dmd`'s directory, which in turn requires that either dmd had been installed so it's usable for bootstrapping, or AUTO_BOOTSTRAP=1 is used in the command line (which isn't).
It's nice to have the build of dlang.org …

Remove dependency of dmd on .cloned

---

changelog.dd

https://github.com/D-Programming-Language/druntime/pull/1147

changelog for "allow GC API profiling with --DRT-gcopt=profile:2"

---

portability.dd

This can be asserted at compile time, and that is generally want you want.
(should I open a bugzilla issue before submitting these kinds of changes?)

portability.dd: assert should be static assert

---

ctarguments.dd
doc.ddoc
posix.mak
win32.mak

This is a followup to https://github.com/D-Programming-Language/dlang.org/pull/986 specifically to @andralex's [request](https://github.com/D-Programming-Language/dlang.org/pull/986#issuecomment-119320721)
The purpose of this pull request is simply to fix some minor grammar issues and wordsmithing.  There is currently a [discussion taking place on the forum](http://forum.dlang.org/post/mnhfhs$2b9o$1@digitalmars.com) and a [Phobos pull request](https://github.com/D-Programming-Language/phobos/pull/3463) which may result in different terminology, but I don't think they should prevent this PR from being pulled.  Rather a separate PR should be created when that discussion reaches a conclusion. 
While creating this pull request I also found that the ctarguments.dd/html file was not added to …

Compile-time Argument Lists - Wordmithing, Grammar, and Makefiles

---

doc.ddoc

- and rename dub tool download to package manager

use "official" copy for code.dlang.org link

---

tuple.dd

This is what was in #1052 (closed) but not in #1038 (merged).
https://issues.dlang.org/show_bug.cgi?id=14879

fix 14879 - tuple documentation broken link

---

simd.dd

A few changes to SIMD.dd, mainly continuing my earlier attempt to provide some additional details on getting it to work in practice with compiler flags. In addition, I fixed an issue with one of the examples not compiling (at least for me). I also fixed some minor spelling issues.

Minor updates to SIMD.dd documentation

---

posix.mak

Reverts D-Programming-Language/dlang.org#1050
Fixes [issue 14915 - [REG2.068.0] can't build phobos-release](https://issues.dlang.org/show_bug.cgi?id=14915)
I don't know how to do properly what #1050 aimed for. In the short term, I think it's more important to get a working build again.

Revert "Remove dependency of dmd on .cloned"

---

posix.mak

- that's what actually gets created when cloning
- will always be older than the content

use folders instead of /.cloned dependency

---

changelog/2.068.0.dd

The jump link is already in the proper section.

Changelog 2.068: move "Many phobos functions were rangified" to Library Changes

---

std.ddoc

Thankfully, the HTML spec specifies that a `rowspan` value of `0` will do exactly this.
This affects ddoc tables wider than 2 columns, for example the container primitives table in `phobos/std/container/package.d` (see: http://dlang.org/phobos-prerelease/std_container.html).

LEADINGROW should extend across entire table, not just 2 columns.

---

download.dd

- makes the signatures downloadable by default
instead of showing them in the browser

use binary gpg signatures instead of ASCII armored ones (.asc -> .sig)

---

changelog/changelog.ddoc
dlang.org.ddoc

It's only available on changelog pages. And there it's the default.

add a search option for the changelog

---

std_navbar-prerelease.ddoc
std_navbar-release.ddoc

https://issues.dlang.org/show_bug.cgi?id=14808

fix Issue 14808 - phobos sidebar "D Lib" link is back to homepage

---

posix.mak

- so that the tool must not be updated during a release

use stable dmd for chmgen

---

const3.dd

Related discussion: http://forum.dlang.org/post/riiehqozpkyluhhifwha@forum.dlang.org
I think there's a consensus now that casting away const and then mutating is always undefined behaviour.
Drive-by style fixes: title case, "immutableness" -> "immutability"

state that casting away const and then mutating is undefined behaviour

---

version.dd

The new 64-bit architecture is called System z. IMHO we should
use this name instead the cryptic S390X.

Introduce SystemZ version identifier and deprecate S390X.

---

intro-to-datetime.dd

Eventually, intro-to-datetime should be updated/rewritten/removed, as it
references the long obsolete std.date throughout. For now, just fixing dead
links.

unlink references to the long gone std.date

---

changelog/changelog.ddoc

This fixes the link to core.runtime on <http://dlang.org/changelog/2.068.1.html>.

fix COREMODREF

---

dcompiler.dd

It was decided even before XP went EOL that we're not going to
officially support it anymore. It was decided that we officially support
Windows 7 and later, but the download page was not updated, and it still
says XP.
http://forum.dlang.org/post/ktfgps$2ghh$1@digitalmars.com
So, this fixes it so that it says Windows 7.
This just came up in D.Learn, and folks are giving the incorrect answer thanks to the current state of the download page: http://forum.dlang.org/post/uxqojxjkuarkaowpyrzz@forum.dlang.org

Update the version of Windows that we support.

---

version.dd

These identifiers are defined for some time but I did not update
the documentation.
ELFv1 is defined on most systems using ELF.
ELFv2 is defined on Linux/PPC64le.

Document the ELFv1 and ELFv2 version identifiers.

---

changelog/2.069.0_pre.dd
changelog/changelog.ddoc
changelog/prerelease.ddoc
posix.mak
win32.mak

- fix links in pre-release changelog
- fix curl anchor
- add note about self-hosted ddmd

changelog 2.069.0

---

win32.mak

- Removes excluding format.d which used to fail compilation, but works now
- Removes the workaround for D-Programming-Language/dub#331, which has been fixed for a few releases now

Remove dpl-docs build workarounds on Windows.

---

changelog/2.069.0_pre.dd
function.dd

Also put a note on the spec page stating that @property is not implemented
and that its details may change.
I'm targetting the stable branch here. Is that right? Do we do that with the dlang.org repository?

[2.069] mention @property in the changelog

---

objc_interface.dd

Also, there was a statement that some "characters" were not valid symbol characters, but then listed only one character, the colon. The way this looked in the docs was very confusing (I wasn't sure if there was something missing after the colon).

Fix some typos

---

arrays.dd

I removed the two occurrences of Phobos since the relevant property/function is actually in druntime.

arrays.dd: clarify intended meaning of reserve function and append operator with example

---

changelog/2.069.0_pre.dd
declaration.dd
grammar.dd

https://issues.dlang.org/show_bug.cgi?id=12421
Corresponding compiler change: D-Programming-Language/dmd#3638

Issue 12421 - Allow simpler syntax for lambda template declarations

---

lazy-evaluation.dd

Fix a small bug in a code example, so that the code matches with the given console output.

Fix small bug in lazy-evalution.dd

---

cpptod.dd

typedef is deprecated (http://dlang.org/deprecate.html#typedef) and so this text needed updating.

Advise std.typecons.Typedef instead of typedef

---

grammar.dd
iasm.dd

https://issues.dlang.org/show_bug.cgi?id=13301

Issue 13301 - Inline ASM documentation does not allow string literals

---

dpl-docs/dub.selections.json
dpl-docs/views/layout.dt

The version "2.067.1" stayed hard-coded since the new website layout was converted to Diet format.

Fix version number in DDOX based navigation section.

---

doc.ddoc

It doesn't fit there and I don't understand why that example is in the menus at all. wc.dd is still there, so a link can be added elsewhere if desired.

Remove wc example from Books & Articles submenu

---

css/style.css

I know that discussing styling decisions on the internet is a road full of personal opinion and flame wars, so I want to keep this discussion purely practical by stating this: justified text is harder to read on the web than left aligned text.
A good summary of the problems and the evidence behind them can be found here: https://kaiweber.wordpress.com/2010/05/31/ragged-right-or-justified-alignment/. TL;DR is that it makes little difference for people who can read well, but for people with dyslexia or other reading disabilities, justified text is much harder for them to comprehend.
Also, the reason that most books are justified is they are done by hand or reviewed and edited by someone after a automatic process is finished. Automatic justifying software is just not up to the task in most …

Left Align Text

---

std-ddox.ddoc

DDox generates a nested directory structure, so a relative ROOT_DIR, as is
used for /phobos/ pages, doesn't work.
This fixes links on http://dlang.org, but not in local mirrors (releases,
git clones). There it actually even breaks some links that happened to
work before.

set ROOT_DIR=/ for DDox pages

---

bugstats.php.dd

I've regularly noticed that the graph image linked to from bugstats.php
would not display - however, it would start displaying for a while when
you visit the page it links to. Since the image URL seems to link to a
static file, I guess that the graphs are generated by the CGI request,
and the static files are cleaned up periodically. Thus, to have the image
display on another website (dlang.org), we also need to regularly trigger
its generation, one way being to make the CGI request to generate the
image at the same time as when requesting the image.

bugstats.php.dd: Add hidden iframe to trigger generating the image

---

spec/lex.dd

All the other rows clearly show inclusive ranges, while uint decimal shows an exclusive range (i.e. `uint.max + 1` as the top value)

Fix typo in docs for number literal ranges

---

spec/hash-map.dd

https://issues.dlang.org/show_bug.cgi?id=15471
FWIW: The extra whitespace was auto-removed by my setup, I checked and it does not change the rendered html page.

Issue 15471: Associative Arrays: add example of static initialization

---

migrate-to-shared.dd

On top the variable is defined as "flag" but on the bottom, it is used as "flags" while both of them should have been same.

Wrong variable naming in the example

---

index.dd

The example on dlang.org's index page which rounds floats currently crashes when ran. If you dump out `args` you can see that for some reason it's getting an empty string as `arg[1]`: `["./f347", ""]`
To "fix" this, I just removed support for reading from args.
```
std.conv.ConvException@/opt/compilers/dmd2/include/std/conv.d(2402): Floating point conversion error for input "".
----------------
??:? pure @safe bool std.exception.enforce!(bool).enforce(bool, lazy object.Throwable) [0x4b57ee]
??:? pure @safe real std.conv.parse!(real, immutable(char)[]).parse(ref immutable(char)[]) [0x4c8eee]
??:? pure @safe real std.conv.toImpl!(real, immutable(char)[]).toImpl(immutable(char)[]) [0x4ca1b9]
??:? pure @safe real std.conv.to!(real).to!(immutable(char)[]).to(immutable(char)[]) [0x4c8ea3]
??:? …
```

Fix crash in index sample code

---

std-ddox.ddoc
std.ddoc

Usage: `$(MREF std,algorithm,searching)` or `$(MREF std,file)`. Returns a link to the given module. Unlike the existing cases of `$(LINK2)`, this also works in ddox as well as ddoc.

MREF macro for linking to modules

---

spec/function.dd

`nothrow` correctly rejects throwing of `Throwable`s; if it didn't, `Exception`s could be thrown through base class references.

Update specification on nothrow

---

dlang.org.ddoc
macros.ddoc
std-ddox.ddoc
std.ddoc

Usage is like:
```
$(REF File.writeln, std, stdio)
$(REF splitter, std, algorithm, iteration)
$(REF_ALTTEXT forward range, isForwardRange, std, range, primitives)
```
Added to dlang.org.ddoc because that's where XREF is defined. Can be used to link to symbols rooted in `std`, `core`, `etc` or any other root package.
Implementation is a bit messy. I don't know quite why, but using TAIL instead of those helper macros didn't work. Commas showed up in the output.
Will implement for DDox output ASAP.

Add new macro REF, a variadic and more general XREF

---

posix.mak

This is a first stab at fixing: https://issues.dlang.org/show_bug.cgi?id=14972
This is probably a rather crude way of doing things, and I probably overlooked some issues this may cause, but it's just to get the ball rolling on making Windows-specific docs show up on dlang.org.
*Note:* Please also see the corresponding Phobos PR (https://github.com/D-Programming-Language/phobos/pull/3593) to actually generate docs for `std.windows.*`, otherwise this PR won't do very much.

Issue 14972: Include std.windows modules in navbar.

---

posix.mak

- avoids issues w/ libcurl
- quite some new deprecation warnings due to libdparse

update dmd and dub used for dpl-docs

---

posix.mak

- mainly affects Ubuntu which uses as-needed by default

use no-as-needed to workaround dmd's link order issues

---

rationale.dd

Documentation refers to `cmp` i.o. `opCmp`. Corrected that. Also provided `opBinary` example which also well illustrates usefulness of `op*` system rather than `operator?` system.

correct cmp to opCmp and add example for opBinary

---

css/style.css

Forgot this when I added the border-left.
Before/after:

remove .subnav's border-left in narrow layouts

---

posix.mak

- meant for the https://dlang.org/install.sh script

don't overwrite install.sh/install.sh.sig when rsyncing

---

css/style.css
images/dlogo.svg

Also made the logo white (#fff); it was almost white before (#eeeeec).
And smoothed out two rough edges in the D shape. Shoutout to WebFreak001
for spotting that.
Forum thread: http://forum.dlang.org/post/n7rqki$pqo$1@digitalmars.com
Screenshot:
And in a narrower window, when the logo is pushed to the window border:
Before/after shots of the D shape fixes (magnified a lot):
Outside, bottom left: ![diff-a-before](https://cloud.githubusercontent.com/assets/9287500/12536992/c97d9740-c2b4-11e5-9477-158d387092fa.png) ![diff-a-after](https://cloud.githubusercontent.com/assets/9287500/12536993/c97d9bf0-c2b4-11e5-9a27-e667a7a36663.png)
Inside, top right: ![diff-b-before](https://cloud.githubusercontent.com/assets/9287500/12536995/c97f66d8-c2b4-11e5-9b7e-7fb74e978b1e.png) …

new logo variant: no borders, less effects, wide planet arc

---

download.dd

~~Only missing [the Android logo](https://commons.m.wikimedia.org/wiki/File:Android_robot.png), would appreciate if someone would process that image as needed and submit a PR with the Android logo.  I've used the openSUSE logo as a placeholder for now.~~ No logos needed anymore, much simpler.

Link to alpha mobile compiler releases

---

dlang.org.ddoc

Stumbled over REF missing the leading dot when using it in the phobos changelog: https://github.com/D-Programming-Language/phobos/pull/3964

add leading dot to anchors generated by REF/REF_ALTTEXT

---

spec/attribute.dd

I find it clearer to explicitly state that `abstract int foo() { return 0; }` renders the encompassing class un-instantiatable, even though all function bodies are available.

Add clarification for abstract function bodies.

---

dpl-docs/dub.json
dpl-docs/dub.selections.json
dpl-docs/views/ddox.overview.dt
dpl-docs/views/layout.dt
posix.mak

- title variable is now defined in views/layout.dt

update ddox to 0.12.0

---

index.dd

This changes the script to use // for the protocol to fix issues like the script being ignored by Chrome and warnings being displayed in Edge / IE.
Recreated pull after changing wrong link originally. I didn't test locally, so will need to wait for the documentation bot to generate it, I'll update the pull when checked.

Fix issue 15697 - The TWID script is always served over HTTP

---

css/style.css

Fixes issue 15696 - The website logo overlaps the Learn tab when using
Microsoft Edge

make logo width explicit

---

spec/module.dd

Existing explanation and example of `import` vs `public import` was not so clear. Clarified it.
BTW change of ABCD to WXYZ in the example wasn't arbitrary but to avoid conflict with previous two paras. I also marked it as "another example".

clarifying wording of import vs public import

---

spec/contracts.dd
spec/errors.dd
spec/float.dd
spec/function.dd
spec/garbage.dd
spec/template-mixin.dd
spec/template.dd
spec/version.dd

add more missing anchors, from "functions to "Embedded Documentation"
following the order in the site menu is remaining to do:
-  operator overloading: DAutotestfailure because ?
-  Const and Immutable: const3.dd, need rewritting to allow LNAME, paragraphs are surrounded with $(SECTION ...), the markup style is not super friendly
-  _Interfacing to C_ to _Vector Extensions_.
-  maybe the pages that are not located in the spec folder.
If acceptable, this PR can be merged as it or you can wait for the remaining pages to be processed.

add missing anchors from "functions" to "Embedded Documentation"

---

dpl-docs/views/layout.dt

If I currently visit https://dlang.org, I get the following error:
```
Mixed Content: The page at 'https://dlang.org/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://google.com/search'. This endpoint should be made available over a secure connection.
```
Btw since 2014 Google is [preferring HTTPS sites](https://googlewebmastercentral.blogspot.fi/2014/08/https-as-ranking-signal.html), so why not make SSL the default?

use https for google search

---

latex.ddoc
std-ddox.ddoc

It looks like DDox detects and handles module references in the same way it detects symbol references. This fixes module references in `/library-prerelease/` and removes `<a>`-inside-`<a>` shenanigans.
DDox doesn't appear to detect module references if they appear the end of a punctuated sentence, like `see std.algorithm.`; I'll file that over at the DDox repository.

Let DDox handle module references

---

latex.ddoc
spec/cpp_interface.dd

* Removes old assumptions
* Specifies the new type and template stuff, with examples
* Updated memory allocation section
* Updated data type table
Depends on: [issue 15372](https://issues.dlang.org/show_bug.cgi?id=15372). The template example doesn't link.
The first commit contains only the tabs to spaces changes, so it's probably easier to review using the diff for the second commit.

Update cpp_interface.dd for recent developments

---

spec/cpp_interface.dd

The "COM interface" link is broken. There is no point in fixing it at the moment, though, since there is no actual content at the wiki page it's meant to target. Instead, I just removed the link.
The "C interface" link works on **dlang.org**, but wasn't on my local build because it was missing the `spec/` prefix. So, I fixed that too.

Link fixes for C++ interface

---

dlang.org.ddoc

why don't we use `https` for the links within phobos's documentation?

use https for internal documentation links

---

std-ddox.ddoc

For DDoc,
```
$(REF_ALTTEXT writeln, File.writeln, std, stdio)
```
expands to
```
<a href="std_stdio.html#.File.writeln">writeln</a>
```
which relies on the fact that `File.writeln` is part of the URL. To provide identical functionality for DDox, it would have to expand to:
```
a href="/library/std/stdio/File/writeln>writeln</a>
```
`REF` handles this by expanding to `std.stdio.File.writeln` and letting DDox recognize it as a symbol path, but I'm not aware of an equivalent feature in DDox that works like `REF_ALTTEXT`.
This patch makes it expand to:
```
writeln (std.stdio.File.writeln)
```
It's not ideal but it's an improvement over the broken output it currently generates.

Implement REF_ALTTEXT macro for DDox

---

dlang.org.ddoc
posix.mak

Works in conjunction with https://github.com/D-Programming-Language/dmd/pull/5352.

html doc build for dmd

---

spec/declaration.dd

ref2.d
```d
import std.stdio;
ref int func2()
{
static int y = 0;
writeln("y \t" , y);
return y;
}
void main()
{
func2() = 2; // The return value of func2() can be modified.
assert(func2() == 2);
auto x = func2();
pragma(msg, typeof(x));
static assert(is(typeof(x) == int));
static assert(typeof(x) == int); // why not work ???
x++;
writeln("x \t", x);
assert(x == 3);
assert(func2() == 2);
}
```
```
dmd ref2.d
ref2.d(19): Error: found ')' when expecting '.' following int
ref2.d(19): Error: found ';' when expecting identifier following 'int.'
ref2.d(21): Error: found 'x' when expecting ')'
ref2.d(21): Error: found '++' when expecting ';'
```

fix compile error

---

dlang.org.ddoc
dpl-docs/views/layout.dt
getstarted.dd
index.dd

for spec.html we can see contents of spec and download link to *.pdf and *.mobi

all language reference should link to spec.html NOT intro.html

---

index.dd
js/run-main-website.js

`.sort` is deprecated property. In the same time `.sort()` looks weird.

Fix example on the front page

---

css/style.css
dpl-docs/dub.json
dpl-docs/dub.selections.json
posix.mak
std-ddox.ddoc

Fixes:
- Types now have some CSS styling
- Cross references within backtick code work again
- Fixed invalid nesting of HTML elements in some cases
- Function attributes are highlighted
- Automatic cross-referencing outside of D code is now disabled
- `@...` built-in attributes are now highlighted as keywords
Still missing: sometimes keywords are not recognized as such, seems to be [a bug](https://github.com/Hackerpilot/libdparse/issues/94) in libdparse.

Upgrade dpl docs dependencies

---

dpl-docs/dub.selections.json

- Fixes parsing function with auto return type and this modifiers
- Fixes duplicated symbols being output to doc pages and to the file system
- Fixes lookup of variadic template arguments

Upgrade to DDOX 0.15.1.

---

dlang.org.ddoc
dpl-docs/views/layout.dt

Since the new website layout now has distinct menus for each category, the menu entry can be moved to the other documentation sections, where it logically belongs, without occupying premium space, which was the reason to put it under "Resources" initially. This should increase the visibility considerably.

Move "NEW Library Reference Preview" menu entry to "Documentation".

---

js/run.js

Currently if you try to evaluate code examples on the https://dlang.org the xhr request goes via plain http to dpaste - causing fails on some browsers like safari
DPaste supports https.

Fix runable examples when running dlang via https

---

spec/template.dd

Alias works for *user-defined* types.
Fix location of AliasSeq.
Fix capitalization: print, write.
@CyberShadow @adamdruppe

Tweak template docs for alias & sequence parameters

---

dcompiler.dd

Update requirements for OS X now when native TLS is used. Also some minor adjustments to the install instructions making them compatible with El Capitan.

Update requirements for OS X

---

posix.mak

It had been excluded because of ["random compiler errors"](https://github.com/dlang/dlang.org/pull/267#issuecomment-21374478). That doesn't seem to be an issue anymore. Works for me at least.

DDOX: don't exclude std.format

---

spec/function.dd

AFAIK this has never been true. And for why it shouldn't ever become true, see the discussions on the mentioned bugs.

Fix erroneous function spec statement

---

spec/function.dd

This should fix the link from the contents mini-menu at the top.

Fix HTML link to "Nested Functions" section.

---

css/style.css
js/listanchors.js

I was missing anchors at the declarations for a long time. Turns out, while it's pretty difficult to do with DDoc, it's very easy to do so in JS :)
It will add an anchor at the top right.

add anchors to declarations

---

spec/statement.dd

Coming from a background in C++ its natural to expect that the foreach loop within D should take an auto specifier. Because D doesn't need these specifiers a simple note in the documentation can help people understand the difference.

Add note to range based for about implicit type attribute.

---

spec/lex.dd

This just extends the existing examples to show how " can be used in backquoted strings.

Give some examples of " used in backquoted strings.

---

dlang.org.ddoc

The digital mars page was last updated on "Tue May 28 11:53:30 2013" and I hope we can do better.
The review queue is also usually hopelessly outdated and unmaintained. Imho it's besser if we just remove those two links and let the reader explore the wiki.

remove menu link to review queue and digital mars

---

posix.mak

http://forum.dlang.org/post/ptnoowrvpsliwtxcmfoi@forum.dlang.org

posix.mak: Update MOD_EXCLUDES lists

---

spec/class.dd

See: https://issues.dlang.org/show_bug.cgi?id=15839
Issue 15839 - this.outer is of wrong type

Update spec to follow .outer property behavior change introduced in 2.071

---

spec/function.dd

The portable syntax has been supported on the main platforms since 2.067 or earlier.

Update obsolete varargs example that uses `__va_argsave`

---

dlang.org.ddoc
foundation.dd
posix.mak

AFAIK it's already registered and official - e.g. the D foundation is hosting this year's GSoC.
Unfortunately I don't know much about the D foundation (that's the reason why such a page should exist), but I tried to put all the information in here.
Ping @WalterBright @andralex @CyberShadow @MartinNowak 
1) How far are you with applying for non-profit status
2) Do you already have a bank acocunt?
3) Is there more known?
Other pages:
https://www.python.org/psf-landing/
https://www.mozilla.org/en-US/foundation/
http://www.linuxfoundation.org/
http://www.fsf.org/

add D Language Foundation page

---

dstyle.dd

Having a space before and after the colon for selective imports seems to be an informal rule and has been critized in many PR's. 
I personally prefer `import std.range: zip` instead of `std.range : zip`, but the point is to make it a rule and standardize it, so we can automatically check it & no further time is wasted about such nitpicks.

add whitespace in selective imports to dstyle

---

css/style.css
std.ddoc

The old `<br><br>` would result in more whitespace after block elements
than after plain text. A `<div>` doesn't have that problem.
Exemplary before/after shot:

use <div> for DDOC_BLANKLINE

---

dpl-docs/dub.selections.json

- Removes per-enum-member pages and instead displays the full enum member documentation inside of a single table
- Adds template arguments and constraints display for composite types and enums

Upgrade to DDOX 0.15.4 - Fixes the DDOX part of issue 14608.

---

posix.mak

Should fix "Non-optional dependency vibe-d:web of ddox
not found in dependency tree!?." errors.

Use stable DUB version for building dpl-docs.

---

intro-to-datetime.dd

Replacing the custom macros XREF and CXREF with a custom REF_SHORT which
has the same syntax as REF and may prove useful generally.
The custom macro FULL_CXREF is replaced with REF.
Replacing raw HTML with MREF in definitions of CORE_TIME, STD_DATETIME, and
STD_FILE.
FULL_XREF does not have a custom definition here. It's going to be replaced
in a repository-wide purge.
sed commands:
XREF -> REF_SHORT:
arg='\s*([^(),]*)'
from='\$\(XREF\s'$arg','$arg'\)'
to='$(REF_SHORT \2, std,\1)'
sed -i -r "s/$from/$to/g" intro-to-datetime.dd
CXREF -> REF_SHORT:
arg='\s*([^(),]*)'
from='\$\(CXREF\s'$arg','$arg'\)'
to='$(REF_SHORT \2, core,\1)'
sed -i -r "s/$from/$to/g" intro-to-datetime.dd
FULL_CXREF -> REF:
arg='\s*([^(),]*)'
from='\$\(FULL_CXREF\s'$arg','$arg'\)'
to='$(REF \2, core,\1)'
sed -i -r …

modernize macros in intro-to-datetime

---

deprecate.dd

As we are finally getting rid of the comma operator, how about adding it to the "Future" list. Once the [PR](https://github.com/dlang/dmd/pull/5737) is merged, more infos can be added?
Ping @Geod24 @yebblies

add comma operator to the deprecated list

---

dlang.org.ddoc

Is there any special sorting mechanism of the menu? Should I sort the links alphabetically?
Ping @JackStouffer @mdparker
Btw
1) the font-size for the menu on http://dlang.org/blog/ should be `15px` and your menu seems to be outdated (e.g. #1303 is missing)
2) have you tried the blog on your phone yet? The D menu doesn't seem to be responsive anymore :/

Add Official D Blog to menu

---

orgs-using-d.dd

Follow-up to #1312
CC @liranz
Is the size of Weka's codebase something that should be mentioned or should I better remove that?

orgs using d - update weka's description

---

posix.mak

Somewhere is a carriage-return hidden. The sitemap `sed` puts that into the HTML.
This PR avoids matching the carriage return symbol:
Before:
http://dlang.org/sitemap.html
After:

Remove carriage-returns from sitemap

---

html.ddoc

The old method would mess with surrounding links.
Hit recently in <https://github.com/dlang/phobos/pull/4410>.

use <span id="foo"> for anchors instead of <a name="foo">

---

index.dd

1) adds a link to the official dlang blog CC @mdparker 
2) removes the link to the empty/outdated review queue
The best replacement I could find for 2) were the DIPs, better ideas are welcome.

Update community section on frontpage

---

index.dd

At the moment TWiD uses four lines:
this shortens it to three lines so that's more similar to the height of the Learn section:
Btw Both links redirect (This week in D, "June 5") redirect to the same page - so we could remove one?
CC @adamdruppe 
Btw @adamdruppe now that @CyberShadow's auto-deploy is there, you could think about dropping your custom js ;-)

Shorten TWiD frontpage text

---

index.dd

as @leandro-lucarella-sociomantic suggested, this PR puts the short description of the companies and their DConf Link onto the frontpage.
before:
after:
Unfortunately imho adding the quote and more links makes it to messy for the frontpage, see:
After experimenting with this, I am not sure anymore whether it's a good idea to add Links
@aG0aep6G @CyberShadow - what do you think?

Add description and dconf talk to frontpage companies

---

cpptod.dd
d-array-article.dd
deprecate.dd
intro-to-datetime.dd
spec/arrays.dd
spec/hash-map.dd
spec/lex.dd
spec/template.dd

With this, dlang.org doesn't use any macros of the XREF variety anymore.
The definitions stay in place, because the stable docs still use them. Thanks @wilzbach for noticing this. There's a separate pull request to remove the definitions: #1355. It should be possible to pull that after the 2.072 release.

XREF variants -> REF (sed)

---

css/style.css
dlang.org.ddoc

Thanks @qznc for pointing this out. We have to be a bit careful about not adding too much to the menu, but I recently purged to items from the menu, so I guess we are good.
Moreover I took the liberty to sort this alphabetically (it's easier to parse for the human eye).
Btw there are many other great pages that are currently hard to find, see e.g. http://dlang.org/sitemap.html

Fix issue 16141 - Organizations page should have a menu item

---

dlang.org.ddoc

follow-up to #1358
- I removed "The" because it seemed rather foreign to the prevalent style (e.g. it isn't"The Sitemap") and it destroy the point of sorting
- there was a bit of grouping, but this shows us that "Acknowledgment", "Sitemap" don't fit entirely into this menu?

Menu: Sort resources alphabetically

---

dlang.org.ddoc

- rename DMD Manual to Command-line Reference (it currently links to DMD for Windows, there will be a follow-up fixing that)
- add divider after Command-line Reference
- removed "New" from Library Reference Preview (afaik it's more than two years old - there will be a follow-up to remove that entirely in favor of displaying a button within the documentation)

Documentation menu: add divider + rename DMD manual

---

dlang.org.ddoc

short follow-up to #1365 as this could be a bit controversial.
- changes the link for "Tools" to the D wiki
- renames them to "Tools" as they are no longer "D-specific"

redirect tools to D wiki

---

changelog/2.070.0.dd
dlang.org.ddoc
doc.ddoc
modlist.d
orgs-using-d.dd
spec/function.dd

https://github.com/dlang/phobos/pull/4411 (see this for more info)
In the manual cleanup after the usual `sed`'s (see git log) I found a github link to `D-Programming-Language`. 
Also note that this PR doesn't remove the `WEB`, `HTTP` and `HTTPS` macros, but I will submit a follow-up PR once the sister PRs https://github.com/dlang/phobos/pull/4411 and https://github.com/dlang/druntime/pull/1585 are merged.

Kill WEB, HTTP and HTTPS macros

---

dlang.org.ddoc
std_navbar-prerelease.ddoc
std_navbar-release.ddoc

Imho it's very confusing to have "Library Reference" and Library Reference Preview" - how about linking it directly from the docs?
stable:
pre-release:
(for pre-release I thought people are familar with D and know about the difference between ddoc and ddox)

Remove 'New Library Reference' from menu

---

css/style.css
js/show_contributors.js
posix.mak
std.ddoc

This adds a list of all contributors to a module at the end of the documentation.
The [backend](https://github.com/wilzbach/phobos-contribs) queries the Github API for commits to that file / folder and reduces this to Github user + their avatars. Every query is cached for 24h.
That being said yes - the backend could maintain [it's own git repo](https://github.com/wilzbach/phobos-contribs/issues/1) and map the commits to Github avatars, but so far this approach is also working.
The contributor avatars are sorted alphabetically and only enabled for "std" modules.

show list of contributors per module

---

.htaccess

It seems that we broke the link to http://dlang.org/rdmd.html, should be fixed with this.

Fix broken link to rdmd

---

areas-of-d-usage.dd
dlang.org.ddoc
index.dd

FontAwesome is amazing, so how about using it at a very important part of our frontpage?
before:
after: 
(screenshots are taken at 50%)

Add icons to 'Why D'

---

dpl-docs/dub.selections.json

This change avoids discarding the doc comment of either the parent template or the template member when merging eponymous templates to a single declaration.

Fix issue 16152 - Fix merging of eponymous template doc comments.

---

.htaccess

Seems the change to `/` didn't work, `^` matches the beginning.

Fix dmd.html redirects

---

areas-of-d-usage.dd

from @yannick:
> i would remove (or push down) XOmB. its bad if the first link is a very outdated project (yes there is a branch that had some activity this year, but still).
powernex is much more interesting since its under active development.
XOmB still has a lot of Github stars, so I went for pushing it down.

Push down reference to XOmB

---

spec/ddoc.dd

The text is supposed to literally say "$(BACKTICK) macro" there, not
"` macro".
Also putting it in backticks for code styling.

fix accidental use of BACKTICK macro

---

spec/version.dd

They were introduced with https://github.com/dlang/dmd/pull/5850.

Add reserved version identifiers for PlayStation and PlayStation4.

---

changelog/2.071.1.dd

The issue was repurposed and the name was confusing to readers:
https://forum.dlang.org/post/nl2bgi$2oim$1@digitalmars.com

Fix issue 15925 name in changelog

---

spec/function.dd

Because scope has no meaning apart from indirections.
Implementation:
https://github.com/dlang/dmd/pull/5897

ignore 'scope' for parameters with no indirections

---

spec/abi.dd

abi: add mangling for 'scope' and 'return'

---

areas-of-d-usage.dd
dlang.org.ddoc
dpl-docs/views/layout.dt
index.dd

:tada: the tour supports now secure HTTP - how about redirecting to it by default?
CC @stonemaster
https://github.com/stonemaster/dlang-tour/issues/45

Use secure HTTP for the Dlang Tour

---

dlang.org.ddoc

- @p0nce suggested to move the more successful resources at the top (e.g. Blog, Orgs using D)
- I fixed the alphabetical order
- I renamed "Bug Tracker" to "Issues", because 
- bugs has a very negative connotation
- it's called issues.dlang.org too
- it should be last on the list (and with "Issues" we achieve this without breaking the alphabetical order)

Restructure community menu - move successful resources to the top

---

dmd.dd
posix.mak

There's a redirect in place that detects the user's operating system and
goes to dmd-{windows,linux,...}.html. The redirect is fine and on the
online dlang.org it completely hides the dmd.html file that's being added
here. The file is needed, because dlang.org is also distributed as a bunch
of .html files as part of the dmd releases.
Not putting links to dmd-windows.html, etc into the file, because they'd
only be forgotten there.

add dmd.html

---

dstyle.dd

Based on the discussion at #4585, here a couple of items that are part of the "unofficial" Phobos style guide, but probably should be documented.
CC @DmitryOlshansky

Improve Phobos style guide

---

spec/arrays.dd

The documentation didn't clearly specify that `dup` removes immutable/const, and that if the operation would violate const/immutable guarantees, it doesn't compile.
There was also a needless note that `idup` is D2.0 only.

Fix dup/idup documentation

---

spec/expression.dd

https://en.wiktionary.org/wiki/nonidentity
http://www.oxforddictionaries.com/definition/english/nonidentity

fix typo: not-identity -> nonidentity

---

download.dd

- i.e. use https when dlang.org is loaded via https

use protocol relative URLs for nightly downloads

---

spec/expression.dd

this documents the behaviour more clearly, addressing issue 10549

default opEquals does not compare object contents

---

spec/expression.dd

in IdentityExpressions, float types are compared with memcmp. See: [e2ir.c#L2391](https://github.com/dlang/dmd/blob/398719f1725ab86435e604682fbe8f41b91f708f/src/e2ir.c#L2391)

IdentityExpression for floats

---

CONTRIBUTING.md

As proposed on #1401, here's a proposal for a small writing guide to clarify common rules for contributors.
CC @AndrejMitrovic

Add a small writing style guide

---

README.md

- The tag badge will automatically show the latest git tag
- The issue stats badge is intended as a positive motivator for contributors.

Add tag & stats badges to the README

---

faq.dd

>Why is the D front end written in C++ rather than D?
This shouldn't be frequently asked any more, since it's no longer true.
Also why is this entry named "dogfood" ?

FAQ: D frontend is not C++ anymore

---

deprecate.dd

I was now annoyed a couple of times by the lack to be able to link directly to a deprecation page (or only with manually replacing spaces with `%20`, so here is a fix for it.
It's a shame DDoc doesn't allow function execution / CTFE :/

Fix relative links in deprecate page

---

spec/function.dd

The previous paragraph became misleading since inlining can be controlled and checked.

Mention the pragma inline in function.dd

---

dcompiler.dd

Changed links that redirected to Amazon with official Microsoft MSDN documentation
https://msdn.microsoft.com/en-us/library/dd831853(v=vs.100).aspx

Change Visual Studio 10 link to MSDN docs

---

html.ddoc
std_consolidated.ddoc

removes the last bit of the `WEB` macro - shouldn't be pulled before 2.072

[don't merge before 2.072] Remove last standing WEB macro

---

changelog/2.062.dd
changelog/2.063.dd
changelog/2.064.dd
changelog/2.065.0.dd
changelog/2.066.0.dd
changelog/2.066.1.dd
changelog/2.067.0.dd
changelog/2.067.1.dd
changelog/2.068.0.dd
changelog/2.068.1.dd
changelog/2.068.2.dd
changelog/2.069.0.dd
changelog/2.069.1.dd
changelog/2.069.2.dd
changelog/2.070.0.dd
changelog/2.070.1.dd
changelog/2.070.2.dd
changelog/2.071.0.dd
changelog/2.071.1.dd
changelog/2.071.2_pre.dd

Done by:
```
rdmd '--eval=
foreach (f; dirEntries(".", "2.*.dd", SpanMode.shallow))
{
auto replaced = readText(f)
.replaceAll(regex(`\$\(P\n((\$\(LI[^\n]+\n)+)\)\n`), "$1");
std.file.write(f, replaced);
}'
```

remove wrong `P` around `LI`s

---

posix.mak

- avoids dependency on system dmd which can have any version (even newer
than latest release), and might fail to build a correct compiler
- fixes auto-deployment of dlang.org which uses master dmd

use defined bootstrap compiler to build dmd

---

index.dd

index.dd: Don't hyphenate company descriptions

---

cpptod.dd
ctod.dd
spec/lex.dd

The target output is not always HTML.
Fixes HTML comments visible in the PDF.

Convert HTML comments to DDoc comments

---

latex.ddoc

The option seems to be gone in the 2016 edition of the listings package.
This should fix the documentation CI.

latex.ddoc: Remove breakatwhitespace

---

changelog/2.072.0_pre.dd
spec/module.dd

Also modifies spec to identify new switches.
See DRuntime pull request: https://github.com/dlang/druntime/pull/1668

Changelog for new cycle detection behavior switches.

---

spec/garbage.dd

Not sure if any other information should be added. It might be a good idea since a manual implementation was added, but I wasn't sure where to add that bit in the documentation.

Added druntime's runtime gc switch to documentation

---

deprecate.dd
spec/lex.dd

Please do not merge until dlang/dmd#6155 is merged.

Set comma expression deprecation release and implicit string concatenation

---

changelog/2.072.0.dd

- Remove cruft, make clearer.
- Add link to comma bug examples.
Original PR: https://github.com/dlang/dmd/pull/5737

[changelog] Refine comma expression examples

---

changelog/2.072.0.dd

It won't be present in 2.072.0 in any form (2.072.1 will remove last traces
of it), thus mention in the changelog only spreads confusion.
See also https://github.com/dlang/dmd/pull/6251

Remove all mentions of -transition=safe from changelog

---

css/style.css
dlang.org.ddoc

Makes them visually consistent with other code (monospaced font).
Carries more meaning that can be picked up by screen readers and such.

put auto-highlights in <code> tags

---

spec/abi.dd

This documents what I found in the current implementation. Not everything seems desirable, though...

name mangling: bring documentation closer to actual implementation

---

dlang.org.ddoc
dlangupb-scholarship.dd
donate.dd
foundation.dd
index.dd
posix.mak
win32.mak

Add donate to D Language foundation page

---

js/run.js
js/run_examples.js

(incorporating the [forum feedback](http://forum.dlang.org/thread/o3969r$2qed$1@digitalmars.com))
- Put outputbox below the example
- Don't hide code during compilation
- Use "auto" width for the output box
- Use "All tests passed" as default output text

Improve runnable examples

---

css/style.css
js/run.js

Two more small improvements:
-  Keep the correct editor/source code open if it's open on evalation
- use automatic height for CodeMirror boxes
The second commit (use automatic height for CodeMirror boxes) is important as it affects the main example as well. Hence, here are two examples of how its result:
(https://dlang.org/phobos-prerelease/std_algorithm_comparison.html#.among)
dlang.org frontpage before:
------------------------
dlang.org frontpage after:
---------------------
See also the [CodeMirror docs](https://codemirror.net/demo/resize.html).

Improve runnable examples (v2)

---

spec/template.dd

```D
int x;
template Foo(alias X)
{
static int* p = &X;   
}
void main()
{
alias bar = Foo!(x);  // <-- "Error: cannot take address of thread-local variable x at compile time"
}
```
Also change "test() => main()" to allow user can copy/paste/run.

[examples bug fix] template.dd

---

changelog/2.072.0.dd

I added a useful information for the drt-oncycle topic with reference to the D language specification. When upgrading my project to DMD 2.072 I had a hard time preserving the application from the user perspective. So having a reference on how to instruct linker to ignore (harmless) module dependecy cycles in order to avoid additional command line arguments is valuable in this change description.

Improvement for drt-oncycle library change description

---

spec/statement.dd

As discussed on the forum, add explanation about exception handling inside opApply, and their interaction with exceptions thrown from within the opApply delelgate.

Add caveat for opApply and exceptions.

---

spec/function.dd

This is in keeping with the current implementation and tightens the spec to ensure no future shenanigans.

Improve and tighten pure functions specification

---

dstyle.dd

Based on this discussion: https://github.com/dlang/phobos/pull/4964#discussion_r93830907

DStyle: Constraints on declarations should have the same indentation level

---

changelog/2.072.2_pre.dd

It needs to be in the changelog for sure, but we had no bugzilla issue for it.

Add message about issue 16211 update

---

changelog/2.072.2_pre.dd
download.dd

- moved the manually added Bugzilla entry (the list is generated automatically
from the commits) to a proper changelog entry, also see #1531.

download and changelog for 2.072.2-b2

---

language-changelog/README.md
language-changelog/mcpu_avx.dd
posix.mak

Single file allow to enforce that every PR comes with a changelog as one can't run into a merge conflicts.
For DMD the idea was to move the language changelog directly to dlang.org, s.t. the DMD repo only contains the compiler changes.
For more details, see dlang/tools#186

Move changelog to a folder and use single file entries

---

cpptod.dd
ctod.dd

Also expand factorial example.

Tweak D for C, C++ programmer pages

---

posix.mak

If the files are passed to DMD in a different order, Phobos fails to
compile. For example, this happens when the Phobos source code is on a
tmpfs, but not on ext4 or btrfs. Work around this by sorting the
Phobos source file list before passing in to DMD.

posix.mak: Work around DMD bug manifesting on certain filesystems

---

dpl-docs/views/layout.dt

If there are multiple declarations, the source code link should go to the first declaration - not to the header of the file. 
Example e.g.: http://dlang.org/library/std/algorithm/comparison/among.html

Ddox: Show exact source code links for multiple declarations

---

js/run_examples.js

With 2.073 released we could flip the switch and enable the runnable examples for the released doc pages.
Would be nice to get #1550 and #1551 as well.

Use runnable examples for released docs

---

faq.dd

There's been a question about this in D.learn recently:
http://forum.dlang.org/post/apoqhsoqksuwieklcnjj@forum.dlang.org
If I remember correctly the final decision from 2012 was that shared variables do not automatically cause any memory barriers, but we never documented this:
http://forum.dlang.org/post/k7pn19$bre$1@digitalmars.com
http://forum.dlang.org/post/mailman.1904.1352922666.5162.digitalmars-d@puremagic.com
ping @WalterBright @andralex

Update FAQ: Shared does not cause memory barriers

---

dpl-docs/views/layout.dt
std_navbar-release.ddoc

Turns out that I have added another protection which didn't even add the JS for the runnable examples. So this finally adds `js/run_examples.js` to the released docs.

Enable runnable examples on releases docs

---

js/run.js
js/run_examples.js

There's already some very naive support to rewrite `assert`'s statements to `writeln` function calls for the ddoc build.
This just adds extend the RegExp for `ddox`.
This approach itself is pretty limited and of course it would be better to do this during compilation (e.g. as a plugin for ddox) and not via RegExp in Js. Moreover, the RegExp itself might catch some false positives and also doesn't support other common operations like `equal` or a plain assert.
So this is intended as temporary solution until someone has more time to invest into a proper solution.
Btw another reason which makes this complicated is that there are two code boxes (the editor and `code` highlighted produced by ddoc/ddox) and one can only edit the plain source code of the former. At the moment "reset" hides the …

Ddox: support assert to writeln rewrite

---

spec/hash-map.dd

Based on [forum feedback](http://forum.dlang.org/post/osbkmrvyqqjjsxyzgcyd@forum.dlang.org).

Point user to std.array.byPair if compatibility with Tuple is desired.

---

spec/module.dd

Do not merge until dlang/druntime#1765 is merged. I'm assuming this doesn't affect the web site, as this is NOT correct behavior for the current release (2.073). If so, this shoudn't be merged until 2.074 is ready.
I also reworded the descriptions a bit.

Update documentation to reflect new defaults for cycle detection

---

spec/version.dd

Adding documentation for the new version identifiers that will hopefully be added by dlang/dmd#6526

Add RISCV32 and RISCV64 version identifiers

---

css/style.css
js/run.js
js/run_examples.js

As of http://forum.dlang.org/post/enjjesmilghothyjlfid@forum.dlang.org
1) the Regex doesn't seem to handle all cases of `assert` -> removed
2) `textarea` shouldn't be used for a readonly output -> `pre`
3) For consistency I also moved the separated CSS up into its group

Improve runnable: disable assert to writeln transformation + make output a pre element

---

dstyle.dd

(follow up to https://github.com/dlang/phobos/pull/5169)
- Use H4 sections instead of nested lists
- Applied better grouping
- Moved unittest requirement to own "Template" group
- Created a group "Brackets" for "Braces" and "Parentheses"
- Added:
- avoid unnecessary parentheses
- space between binary operators, cast or lambdas
- no space after unary operators, assert and function calls
- Fixed function declaration in the style example
CC @andralex

Extend and beautify the Phobos style guide

---

foundation.dd

According to http://forum.dlang.org/post/nq1pt6$1mba$1@digitalmars.com the exact type is (3). This change adds that to the foundation page.

Specify exact type of 501(c) organization

---

posix.mak

@CyberShadow - do you need anything more than this target to display a preview of the upcoming changelog on your `DAutoTest`?
CC @MartinNowak

Add pending_changelog target

---

dpl-docs/source/app.d
dpl-docs/views/layout.dt
posix.mak

Follow-up to https://github.com/dlang/tools/pull/222 and https://github.com/dlang/dlang.org/pull/1537/
>> Btw as this could also lead to unrelated diffs, should we disable the Bugzilla query for bugs for the changelog builder in "nightly mode"?
> Hmm, yeah, changes that shouldn't result in documentation changes should not have documentation changes indicated in the status line, because then inadvertent documentation changes will get through. I guess with this and https://github.com/dlang/dlang.org/pull/1537 we should expand `NODATETIME` to something more generic.

Better diff mode (DIFFABLE=1)

---

.gitignore
assert_writeln_magic.d
posix.mak

Okay this is a more "sophisticated" approach towards rewriting the AssertExpressions in the runnable examples than the initial regex.
I think we all now the problem: "All test passed" is a quite boring output and not so much than being able to directly change a single character.
The objective of this tool is to be conservative as a broken example looks a lot worse than a few statements that could have potentially been rewritten.
For now:
- only EqualExpressions are "transformed"
- static asserts are ignored
- only single-line asserts are rewritten
- this is only enabled for the prerelease pages
However
- that's still >12K automatic `writeln` transformations
- as `ddoc` is used to generate the documentation, it's ensured that no invalid transformations happened.
@CyberShadow I am not sure …

Add assert -> writeln transformation magic for runnable unittest examples

---

modlist.d
posix.mak

tl;dr: this is a first dependency to expose the built documentation DMD on dlang.org's menu and makes this creates usable independently from dlang.org.
* Accept arbitrary number of directories
* Replaced hard-coded tree dumping of Phobos and DRuntime with a --dump flag
* Detect the source folder of a directory automatically
* Use std.getopt as arg parser

Make modlist.d generic

---

posix.mak

Allows working around issues such as /tmp filesystems mounted noexec,
or conflicts due to multiple users building D on the same machine.

posix.mak: Use TMP environment variable for temporary directory

---

posix.mak

- Adds `std.concurrencybase` and `std.stdiobase` to the menu blacklist
- Removes the deprecated stream modules from the menu blacklists

Fix Issue 17115 - Remove std.concurrencybase and std.stdiobase from the Doc's menu

---

README.md

I think the wiki entry is poorly referenced - I couldn't find a single link here.
(in general I think that the wiki entry should be merged with the `CONTRIBUTING.md`).

Mention the DWiki entry in the README

---

assert_writeln_magic.d
osmodel.mak
posix.mak

- only regeneration when real changes happen
- removes the ugly `rsync` workaround

Use Makefile's pattern rules for the intermediate assert/writeln translation

---

css/style.css

Just a small improvement. I think the links can use a little breathing room.
CC @wilzbach

Added padding to links in Phobos book table

---

posix.mak

I excluded the DDoc release build because it would be directly added to the menu (of the release build) and there's still a lot that isn't documented properly or shouldn't be exposed publicly.
However, as a quick preview here's a screenshot the Ddox menu (prerelease!):
And ddox's awesome auto-completion:
To enable dmd on the menu for the prerelease pages, https://github.com/dlang/dlang.org/pull/1580 is needed

Enable Ddoc DMD release + Ddox prerelease build of DMD docs + verbatim target for DMD

---

osmodel.mak

- The `osmodel.mak` files weren't in sync
- Since a couple of weeks the `tools` and `dlang.org` repo use the same file
Btw this manual sync seems very error-prone and labour-intensive.
Why can't we do an `include $(DMD_DIR)/src/osmodel.mak`?

osmodel.mak: Mention tools + dlang.org repos in the update reminder

---

ctod.dd

Small changes in the "Programming in D for C Programmers" page.

Fixed issues in C code examples and added modern C standard idioms (C99 & C11).

---

.gitignore
changelog/changelog.ddoc
posix.mak

It seems like we are stuck with the `VERSION` macro.
The best solution I found is to overwrite temporarily it with `NIGHTLY_VERSION`, however this depends on https://github.com/dlang/tools/pull/221
To make it "stable" (aka without the nightly information), the easiest way is to set `BUILD_NIGHTLY=0`

Use nightly changelog theme

---

posix.mak

I saw there is also the variable $(DMD_STABLE_DIR) which is used for $(DMD-REL) that uses the hierarchy dmd/src/dmd. I didn't modify that one to point to generated/.../dmd since I assume that the changes in [1] are not stable yet.
[1] https://github.com/dlang/dmd/pull/6562

Updated makefile to use dmd/generated/os/release/model/dmd

---

posix.mak

Change the DUB invocation to rely on `STABLE_DMD`
CC @MartinNowak

DUB: use stable DMD

---

index.dd

The Call for submissions is closed and we need a replacement "news". I shamelessly copy/pasted from last year.

Remove "Call for submissions" from news

---

css/style.css

The old rule was too general and cause silly looking spaces as Andrei
described here:
http://forum.dlang.org/post/ohjurtkzhvufqsahmimj@forum.dlang.org
This makes it only happen where I believe it was intended to happen:
on the hand-written index replacement, such as here:
https://dlang.org/phobos-prerelease/std_algorithm.html
where we have a long list of links all right next to each other under
the quickindex div.

Make link padding only apply to more specific cases

---

posix.mak

The makefile had a redundant variable : $DMD_GEN which stored the same path as $DMD. I erased it and replaced it's occurences with $DMD. 
CC @wilzbach : regarding the other matter, I think it would be best to add dmd to the list of dumped modules after the switch: ddmd -> dmd

Removed redundant DMD_GEN variable and replaced it's occurences with DMD

---

errorpage.ddoc
posix.mak

Fixes display of 404 pages for any non-root URL (e.g. http://dlang.org/phobos/nonexisting.html).
There's more than one way to skin this cat, such as to use full URLs (set `ROOT` to `//dlang.org`) or convert `404.html` to a PHP file, but this is probably the simplest.
For some reason putting the `ROOT_DIR` / `ROOT` macros in the `404.dd` file itself didn't work.

Make links in 404 pages absolute

---

changelog/2.073.2.dd

Fixes "LATEST" appearing instead of a version number in the 2.073.2 changelog.

changelog/2.073.2: Fix VER

---

spec/function.dd

Just to prevent any report tagged "reject-valid" after this D front-end change: https://github.com/dlang/dmd/pull/6570

documents the limitation of attributes on overridden functions

---

posix.mak

- see 9ed394e457eb3483792b0ae38b8909c569cfbde3

prefer creating changelog verbatim from _pre.dd

---

errorpage.ddoc

- caused chmgen to fail
- no nice idea how to get the real root from arbitrary
path/to/nonexistent

fix empty href for 404.html dlang logo

---

spec/abi.dd

FuncAttrs is already optional, so FuncAttr does not need to contain an empty clause.

Remove gratuitous "empty" clause.

---

spec/abi.dd

A function can have no arguments.

make Parameters optional in TypeFunction

---

spec/abi.dd

An example of a QualifiedName found in a TemplateArg can be seen when dump the symbols of this compiled program: https://github.com/dlang/phobos/blob/31e1b462d2311f9d8cecb33172b28eab587b255d/std/parallelism.d#L43-L77
Also symbol parameters are prefixed with their symbol length, as per bugzilla 3043.
Implementation and Notes: https://github.com/dlang/dmd/blob/15b3ee1603b7dcc0317ba63c54f77ee9718f90e4/src/ddmd/dtemplate.d#L8323-L8331

abi: Template symbol parameters are either Qualified or Mangled.

---

posix.mak

This file is now shared for all platforms after the Objective-C integration refactoring: https://github.com/dlang/dmd/pull/6679.

Remove special casing for `objc.d` from the Posix makefile

---

spec/abi.dd

Nested symbols encode the function arguments of the outer function, similar to template arguments.
Continuation of https://github.com/dlang/dlang.org/pull/1626

Allow function parameter types in QualifiedName

---

spec/grammar.dd

As observed [here](https://forum.dlang.org/post/odoqjn$17eh$1@digitalmars.com), one of the rule is incomplete.

synchronize grammar for ModuleDeclaration with module.dd

---

spec/declaration.dd

There should not be a colon at the end of a NonVoidInitializer.

Remove invalid colon

---

spec/grammar.dd

I *think* this would fix:
http://dlang.org/spec/grammar.html#CppAggregateType
and
http://dlang.org/spec/grammar.html#copyright
Would have to double check that though.  Does the build-bot allow previewing the documentation?

grammar: Remove dangling closing parenthesis

---

download.dd

Android is now in beta, and armhf is well-supported.

Update LDC platform info

---

posix.mak

The default target of a Makefile is usually the first defined
non-pattern target. The intended default target of dlang.org's
posix.mak is the 'all' target, however this was broken in
44dd86f9a22bffbc057e76a2cf861037f8f34760 by introducing a non-pattern
target among the pattern targets (in order to specialize building
error pages as necessary to fix relative links to resources).
Move the non-pattern rules block (which includes the intended default
target, 'all') above the pattern rules block to fix the intended
default target.

posix.mak: Fix default target

---

dlang.org.ddoc
dpl-docs/views/layout.dt

For Ddoc we have the problem that `ddoc` is run in the `src` directory, which means the `SRCFILENAME` starts with `ddmd/...`
For `druntime` this worked before as `ddoc` is run outside of the `src` directory.
My simple solution is to add a `PROJECT_SOURCE_DIR` variable to the `project.ddoc` file at `dmd`.
@RazvanN7 as you would need to update these files anyways, I was nice and already set them to `dmd` (nobody uses the online documentation of dmd at the moment anyways).

Fix dmd source links for DDoc and DDox

---

deprecate.dd

Deprecation: set .sort and .reverse props are 'Error' starting with 2.075

---

spec/version.dd

Also known as SH5 - no one supports this anymore.

Remove SH64 predefined version condition.

---

.gitignore
posix.mak

It just felt wrong to put generated files not into the `$(GENERATED)` folder.
As on the DMD Makefile I used `$G` to avoid the visual noise.
CC @CyberShadow @s-ludwig

Move generated docs{,-prerelease}.json to $GENERATED

---

css/style.css

It's needed in the  forum, sometimes the subnav doesn't snap to the page bottom, eg here https://forum.dlang.org/post/yjpgswjigrenryplyvji@forum.dlang.org

Set bottom subnav to a single pix

---

spec/expression.dd

Labels are nice and necessary if you want to direct a reader to a specific spot at the D spec.

Add labels to spec/expressions.dd

---

assert_writeln_magic.d
dpl-docs/dub.selections.json
dpl-docs/views/layout.dt

Due to [17131](https://issues.dlang.org/show_bug.cgi?id=17131) a DUB dependency upgrade was necessary. I discovered that the assert-rewrite pipeline doesn't like empty files like the ones generated from the `publictests` target. A proper solution is to make the assert_writeln pipeline more selective, but the first commit should is a simple solution for now.

Fix 17469 - View source code for object.d is broken

---

posix.mak

The naming here is quite confusing - everything else is named `_STABLE`.

Rename DMD_REL to DMD_STABLE

---

posix.mak

A simple fix to solve the problem of a non-existent stable Phobos directory as introduced in https://github.com/dlang/dlang.org/pull/1590.
The current repository layout assumes that the latest, stable phobos
(e.g. ../phobos-2.074.0) exists. For now, this is automatically ensured
before the Makefile targets are evaluated.
A similar trick is used at the [DMD Makefile](https://github.com/dlang/dmd/blob/master/src/posix.mak#L48) and we would use `git clone` anyways.

Ensure that the phobos-stable directory exists

---

.gitignore
posix.mak

Revert some PRs, fix master

---

.gitignore
posix.mak

Due to https://github.com/dlang/dlang.org/pull/1682

Move generated docs{,-prerelease}.json to $GENERATED v2

---

posix.mak

Ideally this should cleanup our Ddoc variables mess. It's noteworthy that Druntime uses completely different ones, so the idea is to change the build files at Druntime afterwards.
If I did it right, _no_ changes should be detected by DAutoTest.

Unify DDoc Makefile build variables

---

spec/struct.dd

Companion for https://github.com/dlang/dmd/pull/6816

Explain behavior of member=expr inside constructors

---

spec/version.dd

These are supported by existing compilers (i.e: `gdc -mmusl` or `configure --target=i386-linux-musl`), but there's currently no way to express that in D code.
https://github.com/dlang/dmd/pull/6885

Add documentation for uClibc and musl C libraries.

---

spec/statement.dd

Labels are nice and necessary if you want to direct a reader to a specific spot at the D spec.

Add labels to spec/statement.dd

---

.travis.yml
assert_writeln_magic.d
changelog/2.072.0.dd
changelog/2.073.0.dd
foundation.dd
posix.mak
spec/statement.dd

@CyberShadow are you okay with enabling Travis here, s.t. we can easily run `test` on a CI?
It works on my fork:
https://travis-ci.org/wilzbach/dlang.org
(I also wanted to revive the PR in which we build dlang.org from scratch on Travis, but that would be another step).

Fix Issue 17501 - Runnable unittest problem with AST rewrite

---

.travis.yml

Follow-up to #1693
There's no point in testing with many compilers as we download and use `STABLE_DMD` anyhow.

Use only one instance for the Travis build

---

faq.dd
forum-template.dd

Seems like we should really check for such errors automatically ...
Discovered in https://github.com/dlang/dlang.org/pull/1694#issuecomment-308663796

Fix invalid undefined Ddoc macros

---

code_coverage.dd
index.dd
spec/pragma.dd
spec/unittest.dd
spec/version.dd

We have added the `.htaccess`-based a long time ago, it's time to get rid of these OS-dependent links.
Example that the redirects work nicely:
dlang.org/dmd.html#switch-cov

Use a OS-independent link to the DMD manual

---

spec/struct.dd

- as we're going to revert it temporarily for 2.075

revert/comment out #1658 for now

---

spec/abi.dd

We really need someone going over the spec/website regularly ... - there's so much room for improvement ;-)
CC @ibuclaw

Fix Issue 17305 - [SPEC] ABI page still has references to D1 Phobos

---

posix.mak

Follow-up to https://github.com/dlang/dlang.org/pull/1694
I had to exclude the stable branches as the fixes are only on master yet (and if we ensure that master has no undefined macros, then stable should safe as well).
@CyberShadow what's the best way to run this on all repos? As post hook to DAutoTest?

Search for undefined macros

---

spec/declaration.dd

@CyberShadow any smart idea on easily verifying that all links are valid?
The ugly way would be to parse the generated HTML, create name/id lists for each file and then check all links ...

Fix link to FuncDeclarator

---

posix.mak

Follow-up to https://github.com/dlang/dlang.org/commit/4129e45951a56c90a7245b41d0ca01c23fa8206d
> The term `DDOC_VARS_STABLE` doesn't relate to `DDOC_VARS_HTML` and `DDOC_VARS_VERBATIM`.
Following the existing naming schemas, it prolly should be named `DDOC_VARS_HTML_STABLE`, 
OK (see this PR).
> or maybe you just use 2 variables `DDOC_VARS_HTML` and `DDOC_VARS_STABLE` (for the compiler) here.
I am already proud that I reduced them from being spread everyone to one common place ;-)
Do I understand you correctly that instead of:
```
DDOC_VARS=\
DMD="${DMD}" \
DRUNTIME_PATH="${DRUNTIME_DIR}" \
DOCSRC="$(PWD)" \
VERSION="${DMD_DIR}/VERSION"
DDOC_VARS_HTML=$(DDOC_VARS) \
DOC_OUTPUT_DIR="${DOC_OUTPUT_DIR}/phobos-prerelease" \
STDDOC="$(addprefix $(PWD)/, $(STD_DDOC_PRE))" …
```

Renname DDOC_VARS_STABLE -> DDOC_VARS_STABLE_HTML

---

index.dd
js/dlang.js

From https://github.com/dlang/dlang.org/pull/1757#issuecomment-310889979
> OK, so, as I understand, this PR does three things right now:
> Fix the JS roulette
> IMO these should be separate PRs, or at least commits
Well #1757 removes this bit completely (hence no separate commit), but as the discussion seems to take a bit longer, there's no reason why we couldn't fix the roulette in the meantime.

Temporarily fix the example roulette

---

changelog/2.075.0_pre.dd

During the review of GitHub dlang/druntime#1698, the "END OF FIBER" marker data
was removed to avoid dirtying the guard page. Hence, the corresponding
comment in the release notes doesn't apply anymore.
See dlang/druntime#1821

Fix the changelog for the Fiber's guard page.

---

changelog/changelog.ddoc
changelog/update_nav.sh

Depends on (and includes) #1766 (due to an unavoidable merge conflict otherwise).

 Add pre-release version changelog to version list 

---

index.dd
js/dlang.js

"Meh" solution instead of https://github.com/dlang/dlang.org/pull/1757
CC @CyberShadow

Fix redraw flashes at the JavaScript example roulette

---

deprecate.dd

From https://github.com/dlang/dmd/pull/6821
CC @UplinkCoder

Deprecation: Issue 6227 - Comparison of different enums

---

js/run.js
js/run_examples.js

Proof of concept PR (it's ugly!) to switch over to the DLang Tour as code executor for the executable blocks on dlang.org
However, unfortunately DLang Tour doesn't support `STDIN` nor `ARGS`, so it would only work for the runnable code block in the documentation.

Test tour.dlang.org as alternative backend

---

js/run_examples.js

> BTW, I noticed something a little weird - the "Reset" button is visible by default, but it goes away after you click it once.
If all PRs could be as simple as this one ;-)

Hide the resetButton by default for Phobos examples

---

posix.mak

Hi. Just getting started with D and decided to build a local copy of the docs for myself. I noticed a small makefile bug.
At least on my system (Debian), you need `=` and not `==` here. I believe some (but not all) shells accept both.
Thanks.

Fix small makefile bug affecting string comparison in some shells

---

js/run.js

Putting this in the queue, s.t. once https://github.com/dlang-tour/core/pull/507 is deployed (there are currently some issues with the auto-deployment), we can simply flip the switch.

Documentation examples: send JSON as text/plain to avoid an additional preflight OPTIONs request

---

index.dd

From http://forum.dlang.org/post/oij5t5$14tq$1@digitalmars.com:
While D isn't a "scripting language" as stated in the thread, it can be used literally anywhere and for anything nowadays and thus imho "general-purpose" is a better description than "systems"
FWIW C++ is a "general-purpose" programming language as well. From [Wikipedia](https://en.wikipedia.org/wiki/C%2B%2B):
> C++ is a general-purpose programming language. It has imperative, object-oriented and generic programming features, while also providing facilities for low-level memory manipulation.
CC @aG0aep6G

Explain D as a general-purpose programming language

---

css/style.css

Followup to #1765.
I don't know if it looks like this for everyone, but for me (Firefox, Ubuntu) the new text doesn't break nicely. Luckily, adding just 1em fixes it, and the box still fits in the layout.
Before/after:

adjust .pitch's width to avoid excessive hyphenation

---

css/style.css
index.dd

Marking this as "needs work" as I will to rebase this once we agree on #1775

Allow to select an example on the front page

---

index.dd

Shamelessly adapted from http://dlang.org/blog/2017/06/05/compile-time-sort-in-d/

Add example; Compile-Time Sort in D

---

posix.mak

Follow-up automation to https://github.com/dlang/phobos/pull/5523
Can be enabled after https://github.com/dlang/phobos/pull/5526

Add check for broken Ddoc

---

css/style.css

Bigger viewpoint:
-----------------------
- the tip is still visible
Once the tip isn't visible anymore, use full width:
----------------------------------------------------------------
Currently:
Smaller viewport
-----------------------
Currently:

Use full width for examples selector on mobile devices

---

spec/contracts.dd

Saw this by accident:
In general, the PDF spec has rotten quite a bit and is in serious need of cleanup.

Remove image tags from the generated PDF spec

---

.htaccess
bugstats.dd
dlang.org.ddoc
dpl-docs/views/layout.dt
index.dd
posix.mak
win32.mak

bugstats hasn't used any PHP code in a long time (though it invokes `fetch-issue-cnt.php` via an `iframe`).

Rename bugstats.php.dd to bugstats.dd

---

dstyle.dd

As discussed in https://github.com/dlang/phobos/pull/5529#issuecomment-312391460
>> FWIW at some point we might want to agree on an idiomatic ordering on the attributes 
> Alpha

Add attributes ordering to the DStyle

---

spec/module.dd

I've eliminated all $P macros in modules.dd and reflown the text a bit. No content changes. I don't plan to convert all of the spec right now, but this should serve as an example and field test.

Look ma, no $(P ...) - a test drive of <p>-less pages

---

dlang.org.ddoc
macros.ddoc
spec/const3.dd

I noticed a spurious comma at the top of the table in section http://dlang.org/spec/const3.html#implicit_qualifier_conversions. At first I thought it's a trivial oversight so I pushed https://github.com/dlang/dlang.org/commit/432b8dc44a20d12dbb4b512f65e4cf8788ab97da directly. But then I realized LaTeX does need separate arguments for the header and the body. This pull requests solves the problem the right way by defining and using a CONCAT macro that glues all of its arguments together.

Fix TABLE_10 macro

---

js/run.js

I didn't account for the fact that DPaste would throw errors with the new invocation example.
Let's use the DTour then whenever possible.
The tour works fine: https://is.gd/DTFINJ
For reference STDIN/ARGS support for the tour is already in the queue: https://github.com/dlang-tour/core-rdmd/pull/9

Only use DPaste as backend if absolutely necessary (example as STDIN or ARGS)

---

css/style.css

Just noticed this little defect. I guess it has been like this from the start. Wasn't meant that way.
Before/after (zoomed in):

fix border-radius for "Why D?" boxes

---

posix.mak

Noticed that our frontpage got broken:
This will make the regex more error-tolerant - apparently the last time the article got edited and I wrongly made this part of the regex.
I will directly merge this as a hotfix frontpage. We can always talk later about better approaches.

[Hotfix] - Fix DBlog regex

---

js/run.js

The DTour now allows to select the compiler (e.g. https://github.com/dlang-tour/core/pull/575, https://github.com/dlang-tour/core/pull/574, https://github.com/dlang-tour/core/issues/548).
This means that we can use `dmd-nightly` for the prerelease pages, e.g.
Details:
- The Docker images are built & updated daily
- There weren't many new symbols in Phobos since 2.074.0, but one is in `std.digest.crc`

Use dmd-nightly for prerelease docs

---

css/style.css
index.dd
js/listanchors.js
std_navbar-prerelease.ddoc
std_navbar-release.ddoc

From the [NG](http://forum.dlang.org/post/niuatqnkrygvunacwjti@forum.dlang.org):
> IMO there should be a link under the "switch to pre-release." link in the current docs.
> Maybe replace it with a dropdown to select the version from 2.066 to pre-release?
CC @JackStouffer @CyberShadow 
It's not perfect yet (e.g. I need to detect the current version automatically and add the same for the Ddox build), but I wanted to get your opinion on this before I invest more work.

Add a version chooser to DDoc pages

---

spec/version.dd

also see https://github.com/dlang/dmd/pull/6977
Arguably the D_ prefix doesn't make much sense here, but that's how it was done for D_AVX and there is little point in changing that.

add D_AVX and D_AVX2 to version identifier docs

---

spec/lex.dd

Labels are nice and necessary if you want to direct a reader to a specific place of the D spec.

Add labels to spec/lex.dd

---

spec/function.dd

```d
void main(string[] args)
{
union U {
int a;
double b;
}
enum u = U(1);
enum c = u.b;
}
```
```
> rdmd foo.d
foo.d(8): Error: reinterpretation through overlapped field b is not allowed in CTFE
```
CC @UplinkCoder

Fix Issue 17159 - Behavior of unions at compile time is not documented

---

dstyle.dd

Linking to sections of the DStyle can be useful. Observed here: https://github.com/dlang/phobos/pull/5581#discussion_r126316833
CC @JackStouffer @CyberShadow

Enable section links to the DStyle

---

index.dd

In https://github.com/dlang/dlang.org/pull/1763 `EXTRA_EXAMPLE` aren't runnable by default, but instead `EXTRA_EXAMPLE_RUNNABLE` are.
https://github.com/dlang/dlang.org/pull/1763 forgot to update the new CT sort example after a rebase.

Make the CT frontpage example runnable again

---

.gitignore
changelog/changelog.ddoc
changelog/update_nav.sh
posix.mak

Regarding https://github.com/dlang/dlang.org/pull/1814#issuecomment-313988447
A simple solution is to use `_pending` for the automatically generated changelog. (@MartinNowak) doesn't seem to use the Makefile target here anyways.
Regarding the changelog menu: I wasn't really sure how we should handle the case when a prerelease is progress, so I simply renamed them "Nightlies" as this actually is exactly what the page depicts.
CC @CyberShadow

Use _pending for the latest changelog entries

---

css/style.css
dlang.org.ddoc

After [my intent](https://github.com/dlang/phobos/pull/5488) to move outdated modules to undeaD failed, here's [the suggested way](https://github.com/dlang/phobos/pull/5488#issuecomment-309288716) of documenting old modules.
> Great, I think starting with documentation should be the official way of implementing all deprecations.
tl;dr: This generalizes the deprecation warnings (and makes them look nicer than for [std.xml](https://dlang.org/phobos/std_xml.html)).
[As suggested](https://github.com/dlang/phobos/pull/5488#issuecomment-309288716) this is heavily inspired by the way NodeJS [marks their modules](https://nodejs.org/api/assert.html), but why not learn from successful ideas?
The overview page:
In practice:
Deprecated
---------------
```
$(COMPATIBILITY_BOX_0)
```
Experimental …

Add compatibility index for modules

---

index.dd

Add example about std.parallelism

---

js/listanchors.js

As I need to do this [manually](https://github.com/wilzbach/dlang.org-archives/commit/65d2e519acfe6f976f4c16460bd6b42dedf61bc1), it's better if I bump it once I have pushed  a snapshot to git.

Bump currently archived version to 75

---

index.dd

Full credit for this example goes to @JackStouffer https://github.com/dlang-tour/english/pull/137 - I merely reformatted it and added `@nogc` to prove the point ;-)
While adding the example, I realized that the existing roulette mechanism was broken.
CC @CyberShadow @ZombineDev

Add example from the DLang Tour to the example roulette

---

posix.mak

Follow-up to https://github.com/dlang/dlang.org/pull/1701, https://github.com/dlang/phobos/pull/5484 and https://github.com/dlang/phobos/pull/5485
It's quite silly that this logic is here and isn't part of a file at Phobos.

Hide std.typetuple from the menu

---

spec/template-mixin.dd

Before, the spec didn't actually allow `mixin template foo() {} mixin foo!();`.

clarify that MixinTemplateName can refer to a TemplateMixinDeclaration

---

posix.mak

Cherry-picked eb71f714990a474718e1dd10463e873d8bea1f7d from https://github.com/dlang/dlang.org/pull/1830#issuecomment-316405165

Fix stable (remove ddmd/objc.d from the exclude list)

---

posix.mak

See also: https://github.com/dlang/dlang.org/pull/1839 and https://github.com/dlang/dlang.org/pull/1830#issuecomment-316405165
Cherry-picked eb71f71 against `stable`.

Fix stable: Remove ddmd/objc.d from the exclude list (take 2)

---

spec/contracts.dd

https://github.com/dlang/DIPs/blob/master/DIPs/DIP1003.md
As per https://github.com/dlang/dlang.org/pull/1818#pullrequestreview-49478344, I changed the examples to use the new `do` contract syntax. I also changed all references to the function body from "body" to "function body" to avoid any confusion with the old syntax.
I also submitted a PR for the grammar: https://github.com/dlang/dlang.org/pull/1829

Change the contracts spec page to reflect DIP1003

---

spec/grammar.dd

https://github.com/dlang/DIPs/blob/master/DIPs/DIP1003.md
As per https://github.com/dlang/dlang.org/pull/1818#pullrequestreview-49478344, I updated the grammar to reflect that either `body` _or_ `do` is now allowed as a marker for the function body.
I also submitted a PR for the spec page on contracts: https://github.com/dlang/dlang.org/pull/1828

Change the grammar spec page to reflect DIP1003

---

index.dd

From @CyberShadow's [comment](https://github.com/dlang/dlang.org/pull/1577#issuecomment-282944600):
> So, not sure about this example's illustrative powers. D arrays are awesome too!
I really liked the example and imho it makes a good fit for the frontpage.
(this temporarily includes the first commit from https://github.com/dlang/dlang.org/pull/1755 to fix the roulette picker, s.t. it can be previewed)

Add hashmap + D arrays example

---

.gitignore
posix.mak

It's starting to get annoying that I have to re-download the stable_compiler after every reboot - even if that's not very often...

Store DMD into .generated instead of $(TMP)

---

const-faq.dd

Parameters of pure functions need not be immutable

Remove outdated pure function limitation

---

js/run.js

Before:
After:
ParseHTML goes down from to 1.24s to 264ms
Once we managed to switch to Ddox, avoiding the JS tricks should be a lot easier.

Fix Issue 17702 - codemirror hangs firefox for several seconds

---

spec/expression.dd

* Use proper capitalization, e.g. Type, len
* Remove unused function arguments
* Tweak `Tup : Template!Args` example

[trivial] Make IsExpression examples clearer

---

spec/expression.dd

The spec says that an `IsExpression` returns an int with value 1 or 0, but it actually returns a boolean with value true or false.

Document the proper return value of IsExpression

---

spec/expression.dd

That is not only a spec thing. In the real world, most `op=` overloads return `void`, while built-ins return the result of `a op b`.

Need to distinguish buint-in and user-defined op=

---

changelog/2.075.0.dd

The fix for [ssue 14246](https://issues.dlang.org/show_bug.cgi?id=14246) was reverted, it is not included in 2.075.0
(see bugzilla page for details), and the issue has been reopened.

Remove wrong changelog entry

---

posix.mak
spec/betterc.dd
spec/footer_gen.d
spec/simd.dd
spec/spec.dd
spec/spec.ddoc

I couldn't find much about `-betterC`, the best resource was Ilya's guide:
https://github.com/libmir/mir-algorithm/wiki/BetterC-for-Mir
CC @WalterBright @andralex: would be great if we could document the current behavior.

Fix Issue 17581 - Document behavior of -betterC

---

spec/lex.dd

https://issues.dlang.org/show_bug.cgi?id=9958

Fix Issue 9958: Integer FloatSuffix is not a valid FloatLiteral

---

posix.mak

posix.mak: Pass DMD_DIR to Phobos makefile for stable build

---

index.dd

This reverts commit bc93f7c0c7e7d734f635e580ec0797f72007434d.
Follow-up to #1848

Revert "Use AliasSeq instead of static foreach for now"

---

download.dd

Now that all my Android patches for ldc have been pushed upstream, I don't put out Android cross-compiler builds anymore, so better to link to the wiki page that shows how to use the official ldc release to build for Android.
As for iOS, Dan hasn't had time to work on it and it has fallen behind.  He'd like for someone else to pick up the torch, but in the meantime better not link to such an old build.

Update mobile links for LDC

---

spec/traits.dd

The description of `__traits(identifier)` alone is rather difficult to understand if you don't already know what it means.

Add example for __traits(identifier).

---

spec/declaration.dd
spec/grammar.dd
spec/statement.dd
spec/version.dd

Note: I was not able to build stable with `make -fposix.mak`. Therefore this is _untested_.

fix Issue 17798 - [2.076] "static foreach" not documented

---

spec/function.dd

Document https://issues.dlang.org/show_bug.cgi?id=17927 behavior.

'inout ref' parameters imply 'return' attribute

---

orgs-using-d.dd

I'm sorry that I haven't been able to invest much time into D lately, so this change slipped through.
The problem here is that Ddoc was never designed to be used as a markup language, so it's pretty easy to mistakes :/
Before:
After:
I wasn't sure about the text of the label as the existing linked video to the Excel-D lightning talk is the analog to the D blog article.
CC @laeeth @jmdavis

Fix Symmetry Testimonial

---

spec/spec.ddoc

Just a little visual tweak.
Exemplary before/after:

tone down spec heading/paragraph numbers a bit

---

spec/contracts.dd

New comers might be confused by the specs, not matching the D code they can read here and there so a note about the syntax explains the situation.

fix issue 17925 - Mention the old body keyword

---

js/run_examples.js

With 2.077 all public examples in Phobos are runnable and thus we can
finally remove the blacklist.
As 2.077 is around the corner, this can be merged fairly soon :)

[2.077] Remove runnable examples blacklist

---

index.dd

I also increased the output limit at the DTour server (see e.g. https://github.com/dlang-tour/core-exec/pull/11), but imho it doesn't make sense to dump everything to the user anyhow.
I reduced it to 14 columns because I had issues with scrolling.

Fix Issue 18032 - [Home] Print hex dump example doesn't run

---

posix.mak

Discussion from https://github.com/dlang/dlang.org/pull/1844
> me: The `tar.xz` balls has about half the size of the zip archive and apart from making the CI generate less traffic on the AWS bucket, it's quite noticeably faster on slower connections.
If there's consensus about this, I would propose to do the same for the DMD bootstrapping.
> @CyberShadow: I wonder, how likely is it that `xz` won't be available on users' machines (and it would be too onerous to install it)?
> me: I thought about the same, but then I guessed that if I didn't include the fallback, chances of complaint / rejection would be high. I actually think that `zip` is less frequent than xz-utils

Use .tar.xz balls if supported

---

spec/statement.dd

This PR was created in response to comments on https://github.com/dlang/dmd/pull/7356.  However, it is not dependent on that PR.  This PR is not introducing any new rules; it is only clarifying the existing implementation.
https://github.com/dlang/dmd/pull/7356 was submitted to bring `opDispatch` in compliance with these rules and the existing implementation.

Clarify WithStatement scope resolution rules

---

spec/contracts.dd

* Non-void functions can use `out` without result variable too
* Replace HTML tags.
* Minor tweaks.

Fix spec for `out` contracts without identifier

---

download.dd

Update to the new "dmd-compiler" deb package name.

"d-apt" deb package name

---

.gitignore
changelog/next_version.sh
posix.mak
test/next_version.sh

Extracted from https://github.com/dlang/dlang.org/pull/1907, s.t. we can move forward bit by bit.
Moving the `next_version` computation to a script seemed like sth. that could easily be a separate PR, s.t. the complexity of #1907 is reduced.
For now I kept things simple and used `changelog/pending.dd` instead of `changelog/${NEXT_VERSION}_pre.dd` (as Martin will do in #1907 too). As this page isn't linked to anywhere we can use any name and not using the version in the filename makes things easier as we now (1) don't depend on `../dmd/VERSION` and thus cloning `dmd` every time and (2) don't need to call the `next_version.sh` on every Make invocation.

compute next version from ../dmd/VERSION

---

spec/hash-map.dd

This is a modified version of my favorite DLang example for Associative Arrays because:
- shows iteration through arrays and associative arrays
- uses tuples (!)
- has real world use cases (e.g. DNA sequencing)
- it's very concise and "beautiful" (-> easy to understand)
Hence I think it could be worthwhile to list this as an example to the reader.
(Follow-up to https://github.com/dlang/dlang.org/pull/1573)

Hashmap: add example for iteration and tuple counting

---

circle.yml
circleci.sh

For some reason CircleCi doesn't immediately run the PR (maybe because there's no `appveyor.yml` on the target branch yet), so I had to setup it for my fork:
https://circleci.com/gh/wilzbach/dlang.org/84
Anyhow, we are all green now.

Enable RELEASE=1 testing on CircleCi

---

circle.yml
circleci.sh

Looks like this is the reason for CircleCI failing at https://github.com/dlang/dlang.org/pull/1945
```
+ git remote add upstream https://github.com/dlang/dlang.org.git
fatal: remote upstream already exists.
```

Disable cache for CircleCi

---

spec/cpp_interface.dd

Probably quite helpful to people who don't know that much about linkers or just want to copy/paste.
I wasn't sure whether we should recommend the dynamic or static library.
BTW the final example seems to be broken:
```
foo.o:foo.d:function _Dmain: error: undefined reference to 'void increment<int>(Foo<int>&)'
foo.o:foo.d:function _Dmain: error: undefined reference to 'void increment<char>(Foo<char>&)'
foo.o:foo.d:function _Dmain: error: undefined reference to 'void printThreeNext<char>(Foo<char>)'
collect2: error: ld returned 1 exit status
```

spec/cpp: Add compile instructions

---

download.dd

Cherry-picked from #1694 as this was controversial:
> Not sure about making the platform name a link to the documentation. I'd think that being on the 
download page, clicking it would take me to all Windows downloads.
We could also add a link "Docs", but I though that this is the leaner way to do it.

Link to release description on downloads.dd

---

index.dd

I recently (-> https://github.com/dlang-tour/core-exec/pull/12) fixed the automatic Docker image deployment toolchain for run.dlang.io, which means that DMD 2.077(.1) is available for the first time since a couple of days.
So let's better fix our examples sooner than later.
Note that the examples which depend on `stdin` also don't work, because of DPaste's poor availability.
The docker image used for the Dlang-Tour already [supports `stdin` input](https://github.com/dlang-tour/core-exec/blob/master/entrypoint.sh#L22).
They just need to passed to Docker image [here](https://github.com/dlang-tour/core/blob/master/source/exec/docker.d#L127).

Fix Issue 18067 - Benchmark example is broken on the frontpage

---

js/run.js

This can be merged once https://github.com/dlang-tour/core/pull/619 has been deployed.
At the moment we use DPaste only if absolutely necessary (e.g. examples contains stdin or args).
See also: https://github.com/dlang/dlang.org/pull/1799
https://github.com/dlang-tour/core/pull/619 adds support for the `args` and `stdin` parameter in the request object, s.t. we can finally migrate off DPaste.

Use run.dlang.io for all examples

---

latex.ddoc

The listings LaTeX package allows code formatting and highlighting in various languages. Previously we hacked the D language keywords on top of listings' C++ definition. This PR defines D as a distinct language.

[EASY] [PDF] Define D as a distinct language for the listings package

---

latex.ddoc
spec/operatoroverloading.dd

[TRIVIAL] [PDF] Fix table Overloadable Index Unary Operators

---

spec/ddoc.dd
spec/operatoroverloading.dd

Code macros straddling the end of a line are problematic.

[TRIVIAL] [PDF] Minor adjustments

---

spec/lex.dd

The table Escape Sequences was overflowing in the pdf, fixed to look nice.

[PDF] [TRIVIAL] Fix table Escape Sequences

---

CODEOWNERS

Similar to Phobos an attempt to define ownership and help contributors figuring out whom to ping. 
CC @andralex @WalterBright @acehreli @s-ludwig @CyberShadow @MartinNowak 
This is far from complete, but hopefully this files adapts gradually over time.
Or maybe you already have an improvement suggestion?

Add an initial CODEOWNERS file

---

posix.mak

Required for https://github.com/dlang/dmd/pull/7135
One of the various Makefile changes broke the transition stage.
The idea is that once we switch to `dmd`, `stable` (aka `latest` is still at `ddmd`), the best way to check for this is querying directly in the respective target.
For the excludes list duplicates are no problem.

Repair ddmd -> dmd transition

---

changelog/changelog.ddoc
changelog/pending.ddoc
posix.mak

See https://github.com/dlang/dlang.org/pull/1821#issuecomment-315603750 and https://github.com/dlang/tools/pull/251#issuecomment-315604776
Step 1) Add new macros
- as suggested no-hardcoded difference is generated by the changelog script
- similarly to `prerelease.ddoc`, a ddoc file is used to overwrite the definitions
Step 2) Replace full text with macros at the `change.d` tool (https://github.com/dlang/tools/pull/252)
Step 3) Add option to parse `BUGSTITLE_TEXT_BODY` and generate a "incremental" changelog

Add macros for replacement with _pending

---

posix.mak

While the Makefile is growing over time, the documentation isn't.
This is an effort to improve the dlang.org's Makefile documentation.

Add an extensive Makefile documentation header

---

spec/operatoroverloading.dd

The ARGUMENTS macro should be outside the D macro

[TRIVIAL] [PDF] Fix misuse of the ARGUMENTS macro

---

latex.ddoc
spec/betterc.dd
spec/cpp_interface.dd

Before:
or 
After:
or: 
(yellow coloring comes from Okular)

[LaTeX] Use lstlisting instead of tt for CONSOLE

---

changelog/changelog.ddoc
posix.mak

Version 1: https://github.com/dlang/dlang.org/pull/1949 patching the generated changelog file with `perl` and `sed`
Version 2: https://github.com/dlang/dlang.org/pull/1977 generate separate Ddoc macro files, suited for inclusion into the changelog (companion PR: https://github.com/dlang/tools/pull/273)
Version 3: (this PR) Let the changelog generation do the work and simply define the proper macros (companion PR: https://github.com/dlang/tools/pull/274)
...
distant future
...
Version 4: emit & store simple intermediate format from `changed.d`, e.g. YAML
Parse and convert the YAML to HTML as part of the dlang.org build process
(this needs to be merged before pulling https://github.com/dlang/tools/pull/274)

Macros for emitting a contributors list as part of the changelog generation

---

posix.mak

This is the dlang.org-side of the DAutoTest integration for diffable intermediaries.
DAutoTest changes: https://github.com/CyberShadow/ae/compare/9fd710b236b00ef3c471dab590a201620b146d6c...bdc41d1669264104ae38c5919c9a1560d685c4f9

posix.mak: Simplify, add diffable-intermediaries target

---

posix.mak

- Convert all tabs not used for indentation to spaces
(spaces for alignment, tabs for indentation)
- Convert spaces used for indentation to tabs
- Fix stray tabs (e.g. before \)
- Fix other inconsistencies in indentation
Based on https://github.com/dlang/dlang.org/pull/1988.

posix.mak: Whitespace fixes

---

spec/grammar.dd

Fix Issue 17529 - dlangspec.pdf: grammar definitions go over the right margin

---

posix.mak

- all text uses a gap of two spaces after the `#` comment bar
- flow text isn't indented after a heading
- text in list items uses two additional spaces
- code blocks use four additional spaces
- fixed a small grammar issue (Most commonly -> Commonly)
Follow-up to https://github.com/dlang/dlang.org/pull/1989 - makes the indentation consistent.

Normalize whitespace indentation in the Makefile doc

---

latex.ddoc
spec/ddoc.dd

Before:
After:
-----
Before:
After:
----
See also: https://github.com/dlang/dlang.org/pull/1983

Fix Issue 18081 - dlangspec.pdf: don't escape dollars in code examples

---

posix.mak

- This target is apparently not run on DAutoTest (?) -> how about defining a target `dautotest`, s.t. we don't have to update DAutoTest manually?
- Uses a trap to avoid residue intermediate files
- Moving this into `$G` seems to be tricky as `dlangspec.opf ` etc. reference the files directly

Fix 'kindle' target

---

spec/ddoc.dd

Before:
After:
(different PDF readers were used)

[DLANGSPEC] Use a raw dollar in inline code

---

spec/version.dd

Per https://github.com/dlang/phobos/pull/5927#issuecomment-352014910
Below the spec states:
> all identifiers derived from the ones listed above by appending any character(s) are reserved. This	 	the ones listed above by appending any character(s) are reserved

Reserve version prefix Std for Phobos

---

contributors.dd
dlang.org.ddoc
posix.mak

Add initial list of all contributors. This is just as a start to explore options on how we could utilize this information from the git log.
Depends on https://github.com/dlang/tools/pull/253

Add a simple overview of all contributors

---

download.dd

As we are already at the topic:
- there's an [internal discussion](https://github.com/orgs/dlang-community/teams/all/discussions/2) going on about moving the d-apt repository to dlang-community
- it was discussed on the [NG](http://forum.dlang.org/post/mailman.704.1512753538.9493.digitalmars-d-announce@puremagic.com) that `rdmd` will be moved into `dmd-compiler`
- even though DMD is now fully open source since May this year, no one has yet stepped up & submitted the package to Debian upstream
CC @leandro-lucarella-sociomantic @jordisayol

Fix Issue 18082 - Ubuntu/Debian repository installation should mention dub

---

posix.mak

As I can't figure out a fix immediately, this should unblock all failing PRs.
See also: https://github.com/dlang/dlang.org/pull/2006

Temporarily allow failures for running the dspec tester

---

spec/arrays.dd

Revive #1040 - spec/arrays.d

---

download.dd
install.dd
posix.mak

While this isn't perfect, it should provide a good basis for continuous improvements ;-)
I wasn't sure whether `~/dlang/install.sh` or `./install.sh` should be the recommended invocation.
CC @MartinNowak @ZombineDev

Fix Issue 17998 - Document Options for install.sh

---

posix.mak

My main D directory got spammed with:
```
dmd
dmd-2.072.0
dmd-2.073.0
dmd-2.074.0
....
phobos-2.075.0
```
Thus, as dlang.org only needs those repositories, it would be very nice to keep things clean and put every into `$(GENERATED)`
Also currently the `dmd-$(VERSION)` folders conflict with the archives downloaded by the DLang installer.

Checkout stable repositories into .generated

---

posix.mak

`${DMD_DIR}` resolves to `../dmd` by default, which results in these folder being checked out in the root folder and not `$G`. Sorry.
See also: https://github.com/dlang/dlang.org/pull/1889

Fixup for #1889: Use $G instead of ../$G

---

posix.mak

- These repositories are used for the contribution script
- DMD, Druntime and Phobos are already there anyhow
- tools and installer are really small
Also if someone does this locally, it's better to do a full clone as they can directly work on it.
I'm interested if this adds a few more names...

No shallow clones for the latest repos (if not existent)

---

posix.mak

This avoids unrelated changes appearing on the DAutoTest diff.

Don't build the overall contributors list on DAutoTest

---

latex.ddoc
nodatetime.ddoc
posix.mak

From https://github.com/dlang/dlang.org/pull/2017#issuecomment-352737769
> Maybe it's as simple as setting a few variables: https://tex.stackexchange.com/questions/229605/reproducible-latex-builds-compile-to-a-file-which-always-hashes-to-the-same-va
And it really was that simple and works:
```
> diff -s spec.pdf web/dlangspec.pdf
Files spec.pdf and web/dlangspec.pdf are identical
```
Of course, this needs to be merged first, before it will take effect on DAutoTest.

Build a reproducible PDF on DAutoTest

---

spec/spec.dd

This has been discussed with @andralex and @WalterBright.
Unfortunately AFAICT only @WalterBright is able to update the book at Amazon, so he suggested to remove the link until he has time to do so.

Remove Kindle link from the spec (until it's updated)

---

posix.mak

The other variables are called `DDOC_VARS_LATEST_HTML` and `DDOC_VARS_RELEASE_HTML`, so this brings clarity by following the `DDOC_VARS_<releaseType>` scheme.

Rename DDOC_VARS for DDOC_VARS_PRERELEASE for clarity

---

posix.mak

AFAICT this isn't even used during the doc build, hence I want to check the diff.
As a next stage there are two things planned:
- display the current version on the top (for the prerelease docs)
- use https://github.com/dlang/phobos/blob/v2.077.1/std/meta.d as a source link instead of https://github.com/dlang/phobos/blob/master/std/meta.d (Ddoc already does this correctly).

Use changelog/next-version for prerelease doc builds

---

CONTRIBUTING.md
dpl-docs/dub.json
dpl-docs/dub.selections.json
dpl-docs/source/app.d
dpl-docs/views/ddox.inc.module-tree.dt
dpl-docs/views/ddox.layout.dt
dpl-docs/views/ddox.overview.dt
dpl-docs/views/inc.disqus.dt
dpl-docs/views/layout.dt

This is WIP and at least gets dpl-docs compiling with ddox 0.16.
I opened this PR to (ab)use DAutoTest a bit - sorry for the noise.

Upgrade ddox

---

index.dd

Shamelessly adapted from https://tour.dlang.org/tour/en/gems/subtyping
Here the Allman brace style really costs a lot of vertical space ...

[Idea] Add subtyping example to frontpage

---

posix.mak

With DUB 1.6.0 (part of the DMD 2.077.0 release), DUB will retry
downloads from the DUB registry and alternatively use fallback mirrors.

Bump stable DMD and DUB version

---

spec/class.dd

See also: http://dtest.dlang.io/artifact/website-e6672ddd5f4efc6e60942fd38836a7bb2abc1361-6511322dd0ebeb894df6eea5bc0109e9/web/spec/class.html
From https://github.com/dlang/dlang.org/pull/2043

Convert "Const, Immutable and Shared" to a SECTION2

---

js/listanchors.js

See: https://github.com/wilzbach/dlang.org-archives/commit/f00b197d9ba5c31e7e6eedd0b0c14b1d59ae2ec6

Bump docarchives to 2.078.0

---

spec/function.dd

Based on ambiguity [pointed out in the learn forum](http://forum.dlang.org/post/bmriawepbztadaxemvyk@forum.dlang.org).

Clarify that pointer assignment is allowed in @safe.

---

js/listanchors.js
spec/spec.ddoc

Quite similar to the way we display the button for DDoc / Ddox.
From https://github.com/dlang/dlang.org/pull/1810#issuecomment-320342675
> So the next order of business is to put the spec numbering in the URLs. I recall @wilzbach has done some work on the phobos side of that (which is somewhat independent).

Show a version chooser for the spec pages

---

dpl-docs/views/layout.dt
js/ddox.js

This is quite uninituive and I observed people fighting with this.
Changelog:
- Turn off auto-complete for Ddox search box
- Move ddox.js to page bottom
- Go to first entry of Ddox search on enter instead of Google search

Automatically select the first Ddox entry instead of searching on Google

---

dpl-docs/source/app.d

Time to remove this in an individual PR.
Introduced in https://github.com/dlang/dlang.org/pull/1891 to facilite the
transition to Ddox 0.16

Remove legacy Ddox pretty printing

---

spec/function.dd

Better wording for clarifying how @safe restricts pointers.

---

download.dd

add back missing OSX dmg download

---

download.dd

- cause red looks more like an alert

gray download/install info symbol

---

spec/grammar.dd
spec/traits.dd

As always these updates get "lost" or forgotten. We should stop merging things
without a dlang.org PR and also move into generating more parts of the
specification automatically.
https://github.com/dlang/dmd/pull/7178#issuecomment-334524503
See also: https://github.com/dlang/dlang.org/pull/1688

Document isDeprecated + mention isFuture

---

posix.mak

Needed for https://github.com/dlang/dmd/pull/7637 and https://github.com/dlang/dmd/pull/7648

Build and render the DMD man page

---

posix.mak

See also:
- https://github.com/dlang/dlang.org/pull/2067
- https://github.com/dlang/dmd/pull/7637

Remove migration support code for previewing the generated man pages

---

comparison.dd
lazy-evaluation.dd
overview.dd
pretod.dd
spec/attribute.dd
spec/property.dd
spec/traits.dd
spec/type.dd

See https://github.com/dlang/dlang.org/pull/2003#discussion_r157333463 for the motivation (it has been requested by @andralex).

Fix spelling: s/user defined/user-defined/

---

areas-of-d-usage.dd
contributors.dd
download.dd
index.dd
orgs-using-d.dd

This is no longer needed as we now use the newest version of DMD to build the docs.

Drop the $(C_A) Ddoc workaround

---

posix.mak

This should help to understand DUB failures like https://github.com/dlang/dub/issues/1336 better.

Show verbose DUB output in the log

---

posix.mak

The repositories are now checked out to `.generated` too.

Remove outdated clean warning

---

CONTRIBUTING.md
dpl-docs/dub.json
dpl-docs/dub.selections.json
dpl-docs/source/app.d
dpl-docs/views/ddox.inc.module-tree.dt
dpl-docs/views/ddox.layout.dt
dpl-docs/views/ddox.overview.dt
dpl-docs/views/inc.disqus.dt
dpl-docs/views/layout.dt
posix.mak

- https://github.com/dlang/dlang.org/pull/1891
- https://github.com/dlang/dlang.org/pull/1926
2.077.1 comes with DUB mirrors which should avoid the problems due to
code.dlang.org being down which we are seeing on doc builds against `stable`.
See also: https://github.com/dlang/phobos/pull/6035#issuecomment-357824158

Cherry-pick 1891 + 1926 from master to stable

---

posix.mak

See also: https://github.com/dlang/druntime/pull/2042
For the release docs, we will have to wait until 2.079.0
Of course this is still a bit unpolished, but it won't change if we don't expose it.

Show runtime docs in the menu on dlang.org (prerelease docs only)

---

dlang.org.ddoc

Add `BEST_PRACTICE`, `IMPLEMENTATION_DEFINED` and `UNDEFINED_BEHAVIOR` to the spec macros so that the display of these will be consistent and cross-referencable.

add spec macros to dlang.org.ddoc

---

spec/class.dd

Because `contracts.dd` is an article, not a specification.

put class invariant spec in class.dd

---

spec/expression.dd

Correct omissions in the original, and clearly mark implementation defined behavior, undefined behavior, and best practices while avoiding compiler-specific details.
Relies on new macros in https://github.com/dlang/dlang.org/pull/2091

AssertExp: make it a bit more formal and correct

---

deprecate.dd
spec/expression.dd
spec/grammar.dd

- They have been deprecated since 2.067 and error since 2.072:
https://dlang.org/deprecate.html#Floating%20point%20NCEG%20operators
- I removed the bit about the exceptions as that's no true anymore:
https://run.dlang.io/is/vkwgyZ
I also rewrote the entire table to make it less confusing to humans.

Remove floating point NCEG operators from the spec

---

spec/version.dd

[DRuntime already defined `CoreDdoc`](https://github.com/dlang/druntime/blob/master/posix.mak#L66). Let's formalize this similar too `Std` (-> https://github.com/dlang/dlang.org/pull/1999).

Define Core as reserved version identifier

---

spec/function.dd

Revive #1040 - spec/function.d

---

ctod.dd

- Fix C array looping examples by adding the missing `size_t`;
- Avoid Windows/platform specific uses of the names "word" and "dword" in the alignment examples;
- Fix and tweak typos, grammar, etc.
Also, I would review the use of "in praxis". I had never seen that. Even if it is correct, maybe the more common "in practice" would sound more natural to most readers?

Minor fixes for ctod.dd

---

spec/contracts.dd
spec/expression.dd
spec/garbage.dd
spec/struct.dd
spec/template.dd
spec/version.dd

Comparisons to other languages do not belong in a language specification.

remove comparisons to C++

---

spec/unittest.dd

More complete, more precise, and reflects more what the compiler actually does.
The interaction with Ddoc is left intact, though I suspect it should be moved to the Ddoc page.

revamp unittest description

---

spec/type.dd

> Fix bug!
> The spec claims that code that compiles does not compile. This is the kind of stuff that would be easily detected automatically.
https://github.com/dlang/dlang.org/pull/2115/commits/6f056ea7eca3f3c8a4cb6e9927f2af543e93e6ed
I haven't gone through the entire spec and annotated everything because I wanted to add support
for checking the output on stdout and stderr, i.e. check the error messages, but
this can be done afterwards too.

Add runnable annotations to spec/type.dd

---

css/style.css

Did some minor changes to style.css in order for longer names, such as 'ascending_page_allocator' to not exceed the length of the sidebar.
In order to see the changes, go to dlang.org/phobos, expand 'std' on the sidebar and check longer names such as 'ascending_page_allocator' or 'kerrigan_ritchie' to see that it now fits the length of the sidebar.

Long names now have trailing dots

---

spec/property.dd

Finally removed obsolete references to `typedef`, which has been gone from the compiler for what, 10 years?

property.dd: minor fixes

---

spec/betterc.dd

I suspect that's what was intended?

Correct unittest point: with -> without

---

spec/ddoc.dd

Document enhancement https://github.com/dlang/dmd/pull/7043

add URL recognition to Ddoc spec

---

spec/ddoc.dd

Ddoc: Auto-detected URLs should be wrapped in DDOC_LINK_AUTODETECT instead of LINK directly.

---

CONTRIBUTING.md

This page wasn't referenced here at all.
https://wiki.dlang.org/Contributing_to_dlang.org
There's also a bit of redundancy and overlap, but that's a mission for another day.

Link to Ddoc fundamentals

---

dstyle.dd

Follow-up to https://github.com/dlang/druntime/pull/2054.
I'm fully aware that Phobos is a wild mixture of a many, many styles.
This PR won't do any reformatting of Phobos, but tries to define best practices for writing new documentation header as it seems to come up often lately.
--- edit:
Obviously this entire topic is purely subjective and emotional, but the idea here is to find a common ground that can be recommended to newcomers.

Document the preferred Phobos documentation style

---

dstyle.dd

Per [this comment](https://github.com/dlang/dlang.org/pull/2129#issuecomment-360944265)

Wordsmithing style guide's doc comments

---

dstyle.dd

Some changes per the discussion in https://github.com/dlang/dlang.org/pull/2129
Phobos uses both `/++ +/` and `/** */` heavily, and there are cases where `/++ +/` works better than `/** */`, because the documentation includes `/* */` comment. Andrei agreed that both are acceptable. I did add a note about ditto comments, since those should be just fine as single line comments.
Also, I removed the bit about not having indentation in comments, since I'm pretty sure that most existing ddoc comments in Phobos do have indentation, and I don't see any reason not to have it. Personally, I think that it's ugly to have the comment smashed up to the side of the screen. instead of being indented.

Adjust section for ddoc comments in style guide.

---

dlang.org.ddoc

In general I'm not too happy about https://wiki.dlang.org/Tutorials
While it contains a lot of hidden gems, it doesn't contain much content
well suited for beginners and a lot of the tutorials are quite old and not
very idiomatic anymore :/

Add DTour link to Resources menu

---

posix.mak

Apparentely the `man` tool behaves a bit differently on OSX.
As this is only used for previewing the man page changes at dmd (for now),
I think the best course of action is to simply disable this on OSX.
I don't use OSX, someone who does and wants to fix the underlying preview command (https://github.com/dlang/dmd/blob/master/docs/Makefile#L26), is of course always invited to do so.

Disable building the man preview on OSX

---

.circleci/run.sh

Sometimes CircleCi fails randomly as it tries to access the `dmd` binary before it's built. I hope that it's due to `-j5`.
For a failing run, see e.g. https://circleci.com/gh/dlang/dlang.org/121
Also `release` defines all these target, so it's better to use the more generic target.
As an additional protection against faulty network, I added `DIFFABLE=1` too.

Run CircleCi without network traffic

---

dstyle.dd

I'm not sure why it says something about no leading zeroes. It's true that there' shouldn't be any, but AFAIK, no one has been doing it, so it comes off as weird. It's stars that some folks like to do. IIRC, it's a javadoc thing.

Clean up line about leading stars in style guide.

---

spec/class.dd
spec/struct.dd

* Don't use *tuple* when we mean expression sequence.
* Struct `.tupleof` is not a *type* sequence & it operates on a struct *instance* only.
* Add links.

Improve `.tupleof` spec for class, struct

---

faq.dd
html.ddoc
install.dd
posix.mak
spec/ddoc.dd
spec/declaration.dd

Extends the undefined ddoc check for all files and fixes the violations.

Check all files for undefined ddoc

---

deprecate.dd
spec/expression.dd

See also: https://github.com/dlang/dmd/pull/7813

End the deprecation period of using the result of a comma expression

---

posix.mak

This will trigger a hard failure when curl fails to download from the DBlog.
Example (with an invalid url):
```
curl -s --fail --retry 3 --retry-delay 5 http://blog22.dlang.org > /tmp/blog.html
make: *** [posix.mak:580: .generated/dblog_latest.ddoc] Error 6
```
The idea is to prevent this from happening again in production:

Turn curl downloads of the DBlog into hard failures

---

posix.mak

To avoids things like https://github.com/dlang/dlang.org/pull/2180

Use /bin/bash as SHELL for dlang.org to have more consistent behavior across platforms and distros

---

spec/operatoroverloading.dd

Fix issue 18337
I recently was unable to find any documentation on `opIn` and `opIn_r`.  I opened an issue and was told these were deprecated.  Adding a note about this deprecation in the spec should be helpful for others in the future who will have the same question.

Add deprecation note for opIn and opIn_r to operatoroverloading.html

---

spec/module.dd

This is an attempt at updating the spec for the changes in https://github.com/dlang/dmd/pull/6589
I wasn't so sure about the grammar changes.
(`grammar.dd` would also need an update)
See also: https://dlang.org/changelog/pending.html#multi_module_selective_imports

Update spec for multiple selective imports

---

posix.mak

Apparentely Jan changed the config today and now it redirects to HTTPS by default:
```
> curl http://blog.dlang.org
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://blog.dlang.org/">here</a>.</p>
</body></html>
```
Our curl command here didn't use `-L`, hence this file was written and the following commands silently failed. I will work on making them fail louder, but for now we should pull this.
As an exception, I will merge this myself as it's a trivial change and we need to fix the front page ASAP.
edit: rebased to get the highest priority in the queue.

DBlog now uses HTTPS by default

---

posix.mak

This should prevent future failures and stop the deploy.
As, currently it's broken (see https://github.com/dlang/dlang.org/pull/2185), it prints:
```
> make -f posix.mak html
cat .generated/dblog_latest.html | grep -m1 'entry-title' | \
sed -E 's/^.*<a href="(.+)" rel="bookmark">([^<]+)<\/a>.*<time.*datetime="[^"]+">([^<]*)<\/time><time class="updated".*Author *<\/span><a [^>]+>([^<]+)<\/a>.*/DBLOG_LATEST_TITLE=\2|DBLOG_LATEST_LINK=\1|DBLOG_LATEST_DATE=\3|DBLOG_LATEST_AUTHOR=\4/' | \
tr '|' '\n' > .generated/dblog_latest.ddoc
.generated/dblog_latest.ddoc is empty. Please check the download
make: *** [posix.mak:590: .generated/dblog_latest.ddoc] Error 1
```
edit: This PR passes because the DBlog part isn't run on DAutoTest as it uses `DIFFABLE=1`.

Hard fail if the something with the generation of the DBlog macros went wrong and the DDoc macro files are empty

---

.htaccess

I should really stop doing to important PRs late at night. Sorry for the disturbance :/
As an exception I will immediately merge this (it just modifies the .htaccess which isn't tested anyways).
I also sorted the redirects, s.t. they are easier to check for missing ones.

Fix missing redirects to /articles

---

css/style.css
index.dd

The first commit moves CSS styles affecting only the front page to `index.dd.`
This is done because:
- it keeps the main stylesheet thin and lean (easier for other sites to use it as base)
- it allows developers to know that all the changes they need to make are within the same file
- a step into only serving stylesheets needed for the current page to the user
We haven't done this before because Ddoc only allowed to do so with ugly workarounds (`padding: 0;` created a new section).
Though we have started following this pattern more and more over the last months and I used this opportunity to finally move a full chunk out of `style.css`
The second commit is the actual fix. Pretty simple.
CC @JackStouffer

Make Donate button responsive

---

ddoc_preprocessor.d

From https://github.com/dlang/dlang.org/pull/2068#issuecomment-363652740
Not so sure whether's really worth bother though.

Avoid duplicated SWNAMES in to auto-generated CLI output

---

posix.mak

This prefers dlang.org for cloning `dub` and adds it to `dautotest`, s.t. changes to DUB will be visible on the pending changelog.
See also: https://github.com/dlang/tools/pull/302

Issue 18351 - integrate dub changelog with changed.d tool

---

ddoc_preprocessor.d
posix.mak

We always want to use the latest `$(DMD)` to build the documentation as
- this is an automatic test for the newest compiler binary
- we depend on same freshly fixed bugs (and probably we do so in the future) - one example is the fixed behavior of `-w` (https://github.com/dlang/dmd/pull/7440)
This makes it more explicit and also adds `$(DDOC_BIN)` to a couple of other instances as:
- this allows us to preview its output (verbatim)
- it avoids the problem in the future that we add more features to the preprocessor and they don't end up in the PDF specification build
(this might produce changes in the verbatim files)

Use the $(DDOC_BIN) preprocessor with --compiler"

---

posix.mak

2.078.2 was released with more reliable retries and fallback mirror usage (https://github.com/dlang/dub/pull/1339) - hopefully this helps to reduce the spurious DUB failures.

Bump DMD_VER to 2.078.2

---

dlang.org.ddoc

REF1 is currently only used once in entire DRuntime and Phobos, so maybe
a special OBJECTREF macro would have been better?
Anyhow, have a look at the only use of `REF1` to understand the
motivation for this PR:
https://dlang.org/phobos/std_file.html#.thisExePath
Also there are three other PRs being blocked on this:
- https://github.com/dlang/dmd/pull/7342
- https://github.com/dlang/druntime/pull/2082
- https://github.com/dlang/phobos/pull/6140

Fix REF1 to behave analogous to the other REF macros

---

changelog/2.070.0.dd
changelog/2.072.0.dd
changelog/2.074.0.dd
changelog/2.075.0.dd
changelog/changelog.ddoc

No need to duplicate things. It just created more confusion.

Remove redundant REF_OBJECT_SHORT in favor of REF1

---

articles/cpptod.dd
check_ddoc.d
posix.mak

DAutoTest should fail when a trailing parenthesis is found.
Luckily, Ddoc is dump enough to just put them in an empty line with `$`.
Note that this requires all files to use unix file endings.
There was one violation which I fixed and added a test for the future.

Fix trailing parenthesis + add test

---

dlang.org.ddoc

This allows the ref macros to be used directly in the spec.
See also: https://github.com/dlang/dlang.org/pull/1941

Use LINK2 instead of direct a href for REF macros

---

404.dd
dlang.org.ddoc

I know it's a tiny improvement, but everything that makes it a bit easier for someone to report a bug, makes it a bit easier that he/she does so.
(I am aware that the "Report a bug" button already exists, but "above" is inconvenient for people.
After all, the last regression has been reported on the NG and not Bugzilla.
This also changes the default priority of 404 errors to "normal" instead of enhancement.

Provide direct link to Bugzilla on a 404 page

---

spec/declaration.dd

Even if these types are not implemented, they are reserved and they should therefore be listed. They are listed on the page but not in the grammar.

cent and ucent missing in the list BasicTypeX

---

dcompiler.dd

Most people opening dmd-*.html are looking for a description of the CLI flags or maybe an installation guide. While a complete listing of the files is nice, it's not super-useful to the user.
Hence, I moved it down a few section (below the CLI argument listing).

Move verbose files listing to the middle

---

download.dd

Based on feedback from the NG:
>> https://dlang.org/install.html
> I've never seen that page. Would've helped me to see it earlier. The D download page should include a blurb with a link to that install page.
https://forum.dlang.org/post/zwizsobrbboibzqrussm@forum.dlang.org
From @quickfur:
> Wow.  I set out *deliberately* looking for that link, and couldn't find it until I looked at your screenshot. I definitely wouldn't have found it if I didn't even know it was there.
https://forum.dlang.org/post/mailman.2877.1517420581.9493.digitalmars-d@puremagic.com
The info buttons have been added in: https://github.com/dlang/dlang.org/pull/1697
And the install.sh page was added in: https://github.com/dlang/dlang.org/pull/1936

Always display the download icon

---

spec/expression.dd
spec/lex.dd
spec/traits.dd

They're expressions, and belong in the expressions file, not the traits file.
This is a pure cut&paste job. No other changes other than updating links.

move Special Keywords to expression.dd

---

deprecate.dd
spec/class.dd
spec/expression.dd
spec/function.dd
spec/interface.dd

Spec and documentation update to accompany https://github.com/dlang/dmd/pull/7342

Fix Issue 9433 - Deprecate delete

---

ddoc/dub.selections.json
dpl-docs/dub.selections.json

Fixes auto-deploy and avoids a dirty working tree after `dub upgrade --missing-only`.

Update dub.selections.json files

---

css/style.css

@andralex requested this. The pink background made it look like we're trying to portray C++ in a bad light. IMO, we ought to syntax highlight it too.

Change C++ code background to white

---

spec/traits.dd

For : https://github.com/dlang/dmd/pull/7484

Update docs to highlight lambda comparison

---

changelog/changelog.ddoc
changelog/release-schedule.dd
posix.mak

For some reason the argument that D isn't stable and has no proper release model often comes up.
Also for all newcomers and not hard-core insiders its hard to know the release schedule (even many contributors on GitHub aren't aware of it).
Since @MartinNowak has revamped the release process, the releases follow a schedule, so imho we should advertise this and make it easy for people to learn about this.
If everyone is okay with the format (and it gets merged), I would do a quick follow-up that replaces that injects an automatically generated release schedule table, s.t. we don't have to update this file manually.

Add a release schedule to the changelog pages

---

spec/traits.dd

This is needed in order to get in [1]. The first draft of the lambda comparison did not feature function calls inside the lambda body, but now that this capability has been added, first this should get merged, then [1] then [2] which readds the deleted example in this PR and some other examples 
[1] https://github.com/dlang/dmd/pull/7935
[2] https://github.com/dlang/dlang.org/pull/2231

Temporarily delete an example from traits(isSame)

---

posix.mak

This allows just running `verbatim` for all HTML pages. Not really a neccessity, but sometimes handy and a trivial change.

Add a html-verbatim target analogous to html

---

spec/module.dd

Argh it looks like DAutoTest is too smart. It checks out the `stable` branch at `dlang.org`.
So we have to do https://github.com/dlang/dlang.org/pull/2237 again :/
See also: https://github.com/dlang/dmd/pull/7939

Revert "Update spec for multiple selective imports"

---

articles/variadic-function-templates.dd

Following on from #2204:
* Add short table of contents
* Update C++ sections for C++11
* Use sequence instead of tuple.
* Minor wording changes.
* Formatting tweaks.

 Improve Variadic function templates article 

---

spec/template.dd

See also: https://github.com/dlang/dmd/pull/7831

spec update following allowing default valued parameters after template variadics

---

spec/expression.dd

Following on from #2204:
* Compile-time Tuple -> Sequence
* ExpressionTuple -> ValueSeq (this matches https://dlang.org/spec/template.html#variadic-templates point 2)

[trivial] Fix using *sequence* in expression.dd

---

css/html-skeleton.css
css/style.css
html.ddoc
std.ddoc

Some modules from phobos, more precisely the allocators, had very long names.
All titles now have the separate class "d_title" and if the length exceeds a threshold, the font size shrinks.

Title font shrinks if too long

---

dlang.org.ddoc
ebook.ddoc
spec/latex.ddoc
spec/spec.ddoc

See e.g. https://dlang.org/spec/arrays.html for the problem.
In short, `BEST_PRACTICE` is defined as:
```
BEST_PRACTICE= $(P best-practice, $(B Best Practices:) $0)
```
BUT `OL,UL` are individual HTML blocks:
```html
<p>
foo
<ol> ... </ol> // <-- "invalid" HTML, starts a new block
bar
</p>
```
The [spec](https://www.w3.org/TR/html5/grouping-content.html#the-p-element) says this pretty explicitly:
> List elements (in particular, ol and ul elements) __cannot__ be children of p elements.
This fixes this and moves the macros to `spec.ddoc` where they should have been put.

Use correct HTML for BEST_PRACTICE

---

spec/arrays.dd

https://dlang.org/spec/arrays.html
Motivation:

[trivial] Remove runnable block for the first example in spec/arrays

---

index.dd

@aldacron's blog article is really nice and a good explanation for this survey.
(When I created the PR for the "State of D" banner, the article didn't exist yet and I forgot changing the link afterwards.)

State of D: link to the blog article

---

spec/struct.dd

Empty structs are a minefield of more or less intractable issues.

add detail about empty structs

---

articles/ctarguments.dd
articles/index.dd
dlang.org.ddoc
tuple.dd

* Change `expression list` to `value sequence` (this matches https://dlang.org/spec/template.html#variadic-templates point 2).
* Change `list` to `sequence`.
* Describe value & symbol sequences.
* Add subheadings.
* Tweak examples.
* Mention `tupleof`.

Improve Compile-time sequences docs

---

dlang.org.ddoc
spec/arrays.dd
spec/cpp_interface.dd
spec/latex.ddoc
spec/property.dd

Seems like the `PHOBOS` macro was a hack to get references to the standard library.
We should really use the universal `REF` here.
Note - this depends on https://github.com/dlang/dlang.org/pull/2194
edit: this PR has been merged -> this should be good to go.

Remove PHOBOS macro in favor in REF

---

posix.mak

Cherry-picked from https://github.com/dlang/dlang.org/pull/2257
- needs to use ../druntime-${LATEST}/import and ../phobos-${LATEST}
- unclear how this used to work beforehand, likely did pick up ../druntime/import
and ../phobos from a concurrent (or previous) prerelease build
Needed for DAutoTest to pass on `stable`.

fix import paths for dmd-${LATEST}

---

ddoc/source/preprocessor.d

This can now be merged as https://github.com/dlang/phobos/pull/6126 is in 2.079.0.

Remove ddoc workarounds

---

js/listanchors.js

At some point we should look into a solution that automates building the archives as part of the release process...
See also: https://github.com/dlang/docarchives.dlang.io/commit/485734452780d2ff03cdda36aee5254ad48e1cd8

Bump archives to 2.079

---

spec/lex.dd

- `volatile` is no longer part of the language.  It was removed a couple of years ago.
- It's deprecation is already documented at https://dlang.org/deprecate.html#volatile, so there's no need for it to be documented in the spec.
- The link currently goes to a non-existent anchor on the ctod page, sending the reader nowhere useful.

Remove volatile keyword from the lexer documentation

---

changelog/2.079.0.dd

Apparently, someone wasn't paying enough attention and used a markdown-style link instead of a proper ddoc macro.

Fix link in changelog for 2.079.0.

---

posix.mak

Auto-cloning is useful, but not if you run `make -f posix.mak clean`.
This should now be possible due to https://github.com/dlang/dlang.org/pull/2069

Remove auto-cloning of Phobos on start

---

dblog_feed_example.xml
dlang.org.ddoc
index.dd
posix.mak
tools/ddoc_xml_extractor.d

This won't work on DAutoTest, but the generated Ddoc file will be e.g.
```
DBLOG_LATEST_TITLE_1=DConf 2018 Programme &amp; Open Registration
DBLOG_LATEST_LINK_1=https://dlang.org/blog/2018/03/19/dconf-2018-programme-open-registration/
DBLOG_LATEST_DATE_1=March 19, 2018
DBLOG_LATEST_AUTHOR_1=Michael Parker
DBLOG_LATEST_TITLE_2=User Stories: Funkwerk
DBLOG_LATEST_LINK_2=https://dlang.org/blog/2018/03/14/user-stories-funkwerk/
DBLOG_LATEST_DATE_2=March 14, 2018
DBLOG_LATEST_AUTHOR_2=Michael Parker
```

Use the dlang.org's XML stream at feedburner to convert the latest articles to ddoc macros

---

css/style.css
dlang.org.ddoc
posix.mak
tools/modlist.d

The DRuntime docs have been exposed for quite a while after https://github.com/dlang/dlang.org/pull/2084.
However, as there has been almost no activity in improving them, I think the only way to move forward is to expose them on the main pages too.
At the moment, `rt` is only visible on the `-prerelease` menu.
Example: https://dlang.org/phobos-prerelease/rt_config.html
We did the same with the DMD docs as they also received no attention while they were only available in the `-prerelease` for a year.

Expose runtime docs on the released docs

---

dlang.org.ddoc

Let's whether DAutoTest likes this. In theory
- no changes should show up in the diff
- existing suppression of the auto-highlighting can be gradually removed (e.g. with the SUPPRESS helper or `grep`)
- ddoc should no longer do automatic highlighting (not sure whether we can verify this here, but @JackStouffer just run into this issue again - https://github.com/dlang/phobos/pull/6356)
See also:
- https://dlang.org/changelog/2.079.0.html#fix18361
- https://github.com/dlang/dmd/pull/7834
CC @quickfur

Start to opt-out of Ddoc's automatic keyword highlighting

---

posix.mak

Follow-up to https://github.com/dlang/dlang.org/pull/2310
>> BTW, does that mean that we're deploying unused organization HQ logos?
> Yes good catch.
> They were intended to be used for the orgs page (e.g. Retina displays), but this never got to my priority list. I will remove them in a quick follow-up.

Don't deploy _hq images of the orgs-using-d

---

dpl-docs/source/ddox_main.d

This got accidentally broken in https://github.com/dlang/dlang.org/commit/474fb077d1f32e5c6c3ca0ad716234a279e01e42

[trivial] apidocs: fix serve command

---

dpl-docs/source/app.d

(Introduced in #1891 to facilite the transition to Ddox 0.16)
This was already done in https://github.com/dlang/dlang.org/pull/2054, but I have no idea why it's not showing up in the history:
https://github.com/dlang/dlang.org/commits/master/dpl-docs/source/app.d

Remove compatibility --html-style=pretty flag

---

deprecate.dd

`delete` was deprecated in 2.079.  Before the `delete` keyword can be removed it will be necessary to also deprecate and remove class allocators and deallocators.  They have been planned for deprecation for years; this PR finally puts the deprecation process in motion.
See https://dlang.org/deprecate.html#Class%20allocators%20and%20deallocators
DMD PR:  https://github.com/dlang/dmd/pull/8042

Deprecate class allocators and deallocators

---

spec/struct.dd

It was incomplete, inaccurate, and needed links to the grammar.

rewrite struct initialization text

---

deprecate.dd

`scope` for allocating classes on the stack is listed as a deprecated feature.  However, no work to actually deprecate it has ever been done, and now with DIP1000, [it appears it is no longer deprecated](http://forum.dlang.org/post/np1fll$ast$1@digitalmars.com).  In fact it is currently used in DMD's source code.
Here are just a few examples
- https://github.com/dlang/dmd/blob/9da5c2dcac4f096dc90551fc92a97b810389a9b4/src/dmd/argtypes.d#L480
- https://github.com/dlang/dmd/blob/9da5c2dcac4f096dc90551fc92a97b810389a9b4/src/dmd/arrayop.d#L245
- https://github.com/dlang/dmd/blob/9da5c2dcac4f096dc90551fc92a97b810389a9b4/src/dmd/blockexit.d#L542
[It's very confusing](https://forum.dlang.org/post/ddqbairrkurpimbsmtwp@forum.dlang.org), and should either be removed from the deprecations page, or …

Clarify deprecation of `scope` as a type constraint

---

spec/statement.dd

* Compile-time Tuple -> Sequence (see #2204)
* ExpressionTuple -> ValueSeq (this matches https://dlang.org/spec/template.html#variadic-templates point 2)
* Improve wording of *Foreach over Tuples* & example
* Add link to `static foreach`

Improve *Foreach over Tuples* spec

---

posix.mak

```
If target T is defined as depending on A, B, and C, and C actually
needs A and B to build correctly, then A and B need to be listed as
dependencies of C, not T - otherwise, make will build A/B in
parallel to (or even after) C when running in multiple threads.
```

make -j fixes - move dependencies down from pseudo-targets

---

spec/attribute.dd

It seems the attributes in the grammar are all prefixed with @ but this is implied by the rule for properties i.e:
Property:
@ PropertyIdentifier
Furthermore, disable is referenced twice, they are not in alphabetical order, and `Property` and `PropertyIdentifier` are not technically correct terms anymore (or so I believe). I've ultimately just done a bit of a re-org, please see changes.

Remove '@' from attributes

---

js/listanchors.js

See also: https://github.com/dlang/docarchives.dlang.io/commit/238adb5b30e5a5149bae8833c38a871ac82b98fe

Bump archive version to 2.080

---

deprecate.dd

PR to accompany https://github.com/dlang/dmd/pull/8221
See https://dlang.org/deprecate.html#Implicit%20comparison%20of%20different%20enums
This PR moves a deprecation forward, further narrowing the gap between specification and implementation.

Error for implicit comparison of different enums

---

deprecate.dd

PR to accompany https://github.com/dlang/dmd/pull/8220
See https://dlang.org/deprecate.html#Implicit%20string%20concatenation
This PR moves a deprecation forward, further narrowing the gap between specification and implementation.

Error for implicit string concatenation

---

spec/template.dd

Link `SpecialKeyword` in Section *Template Value Parameters* points to `traits.html` but should be `grammar.html`.

Fix broken link

---

dlang.org.ddoc
js/run.js

Turns out that DDox's macro processor doesn't insert a newline when newlines occur in macros.
The workaround is to use good, old HTML.
The old MSIE < 9 support code lead to the final "}" being removed.
See also: https://github.com/rejectedsoftware/ddox/issues/204

Remove old & invalid msie < 9 support code

---

spec/traits.dd

Spec change for https://github.com/dlang/dmd/pull/8195

Fix Issue 16206 - traits getOverloads fails when one of the overload is a templatized function

---

posix.mak

- mixing both a separate target and a variable that influences the
build does not make sense
- also fixes nightly builds which recently switched to ENABLE_RELEASE=1

make relase target independent of RELEASE=1 variable

---

.circleci/config.yml
.circleci/run.sh
posix.mak

- set ENABLE_RELEASE=1 in release target and rerun makefile
- use same ENABLE_RELEASE variable as dmd and create_dmd_release
- Need both a target and a variable to be set for the build to work
with dlang.org's current makefile architecture (deps in variables).
The workaround is messy and separate targets should be used instead
of variables that affect file lists.
The approach in #2371 didn't work as it seems that variables in prerequisites (e.g. of the html target) get expanded before target-specific variables are applied. So even though `release : CHANGELOG_FILES:=$(filter-out changelog/pending,$(CHANGELOG_FILES))` does modify the list it has no effect on `html : $(ALL_FILES)` at the time the html target is run.

fix release doc build with ENABLE_RELEASE=1

---

dlang.org.ddoc

From the issue:
> This is a proposal to make it officially a part of dlang.org: promote the website to run.dlang.org, and add a link to it on the D website (e.g. under the "Resources" submenu).

Fix Issue 14099 - Promote run.dlang.io to Resources

---

spec/function.dd

We shouldn't be setting booby traps for users.
Also, the fewer usages there are in the wild, the easier it will be to properly implement later without disruption.
@WalterBright has set precedent for this with the following PRs:
https://github.com/dlang/phobos/pull/6575
https://github.com/dlang/phobos/pull/6574
https://github.com/dlang/phobos/pull/6573
https://github.com/dlang/phobos/pull/6572
https://github.com/dlang/phobos/pull/6571
https://github.com/dlang/phobos/pull/6568
https://github.com/dlang/phobos/pull/6567
https://github.com/dlang/phobos/pull/6566
https://github.com/dlang/phobos/pull/6564
See also https://forum.dlang.org/post/akrtdnphwhgjhlwkoood@forum.dlang.org

Discourage use of the `in` storage class

---

spec/template.dd

* Document that template alias parameters can evaluate their argument expression at compile-time.
* Document template parameterized by a lambda.

Fix Issue 18558 - Template alias spec incomplete

---

posix.mak

Required for https://github.com/dlang/phobos/pull/6579 as a `test` folder is added to Phobos and at the moment these files get included in the Ddox build.

Only include etc & std for the ddox source file list

---

dstyle.dd

If whether a particular attribute is applicable to a templated function
or not does not depend on the template arguments (e.g. it's a function
for operating on arrays of characters that's templated on character type
and @safe would always be inferred), then having the attributes be
explicit is better for the documentation. It also ensures that the
attribute is enforced so that it's caught if the code changes
accidentally conflict with the attribute. One of the major downsides to
attribute inference is that it's unclear which attributes apply, and
it's easier to accidentally make changes which change the attributes.
Attribute inference is critical when the applicability of an attribute
depends on the template arguments, but if the attribute is _always_
inferred regardless of the template …

Adjust guidelines for attributes on templated functions.

---

spec/arrays.dd
spec/attribute.dd
spec/class.dd
spec/contracts.dd
spec/expression.dd
spec/garbage.dd
spec/lex.dd

Searched the spec for descriptions of undefined behavior, and delineated them with the UNDEFINED_BEHAVIOR macro.

use UNDEFINED_BEHAVIOR macro

---

spec/arrays.dd

Required for https://github.com/dlang/dmd/pull/8438

Change deprecated C array syntax to D array syntax in the spec example

---

deprecate.dd

Documentation update to accompany https://github.com/dlang/dmd/pull/8438

Change deprecation to error for C-style array syntax

---

htod.dd

Imho htod shouldn't be documented on dlang.org, because
- it's not part of the release archives
- it's closed source
- it's Windows-only
- there are more modern tools like dstep
As removing the documentation might be a bit drastic, I went with adding a warning.

Add a pointer to dstep

---

dcompiler.dd

A few small improvements to the respective dmd.html files.

Modernize dcompiler documentation

---

dcompiler.dd

The dmd.html page needs serious work and apparentely it always has been like this since 2008!
I wasn't sure on the best way to fix this because the shipped `dmd.conf` looks like this:
```
[Environment32]
DFLAGS=-I%@P%/../../src/phobos -I%@P%/../../src/druntime/import -L-L%@P%/../lib32 -L--export-dynamic
[Environment64]
DFLAGS=-I%@P%/../../src/phobos -I%@P%/../../src/druntime/import -L-L%@P%/../lib64 -L--export-dynamic -fPIC
```
In other words, the shipped `dmd.conf` can't be simply copied to `/etc/`. This means we have the following solutions
a) just tell the user to add it to his `PATH`
b) advertise to use e.g. a symlink to `/usr/bin/dmd`
c) provide an alternative `dmd.conf` for copy/pasting to `/etc/dmd.conf`
d) provide a command to patch the shipped `dmd.conf`
e) suggest to move the …

Fix Issue 2473, 10941 - Linux system install instructions incorrect

---

spec/function.dd

The code section generates a pre element, which can't be in a p element.
This also confused the automatic paragraph numbering.
Prompted by https://forum.dlang.org/post/fdhaxiavcpbvaysmenyv@forum.dlang.org

move code out of $(P ...)

---

spec/traits.dd

It was very surprising to me that all imported functions because "members" of the struct according to "hasMember" trait. Let's add that behavior to the documentation.

hasMember doc: add import module effect to example

---

spec/latex.ddoc
spec/lex.dd

At least on my system the PDF build doesn't default to UTF-8 anymore.
Also, there seems to be an issue with the cyrillic letters, so for the sake of simplicity I used one of the already predefined variables which are correctly encoded for HTML, ebook and TEX.

Fix local Latex PDF build

---

spec/class.dd
spec/contracts.dd
spec/expression.dd
spec/function.dd
spec/struct.dd

I edited this on github, but then was unable to compile the docs it to check its final appearance in html (See here for why: https://forum.dlang.org/post/azdfcrfqegubikcyntfj@forum.dlang.org ). At any rate, I'm hoping this can be looked at, in particular by @tgehr for accuracy. 
Also, the grammar spec is in a different file and still needs to be changed.

update contracts.dd to reflect DIP1009

---

posix.mak

Given a .d and .di file with the same name, pick only the .di file.
Otherwise, include all .d and .di files.
For https://github.com/dlang/dmd/pull/8447#issuecomment-403256949

posix.mak: Only include .di file for DMD documentation

---

dlang.org.ddoc
ebook.ddoc
spec/attribute.dd
spec/expression.dd
spec/function.dd
spec/latex.ddoc

A first start. I wasn't sure how much into detail of UDAs we should go in the functions page as they are already defined in depth in https://dlang.org/spec/attribute.html
DMD PR: https://github.com/dlang/dmd/pull/7576

[spec] Add UDAs for parameters

---

spec/betterc.dd

Just "Not Available" sounds pretty strange.
BTW should we also add an example here on how to use D with -betterC without any runtime?

betterC section title: add 'features'

---

spec/betterc.dd

I think this isn't obvious to people, especially as it was listed in the "Not Available" features section.

Document how to run unittests in -betterC

---

spec/class.dd

Fields in Objective-C classes have a dynamic offset.
Spec update for https://github.com/dlang/dmd/pull/8541.

Document that `.offsetof`/`.tupleof` are disabled for Objective-C classes

---

articles/template-comparison.dd

The table was misleading.
From https://dlang.org/glossary.html#sfinae
If template argument deduction results in a type that is not valid, that specialization of the template is not considered further. It is not a compile error.
From Walter's comment on Reddit: https://www.reddit.com/r/programming/comments/97q9sq/why_d_is_a_good_choice_for_writing_a_language/e4bgtuq

D doesn't have SFINAE

---

dstyle.dd

dstyle.dd: Add version to the Whitespace list

---

dpl-docs/views/layout.dt

The escapes may have been needed at some point, but now they appear verbatim in the output, breaking the code.

DDox: Fix fall-back JS code for loading jQuery

---

dstyle.dd

- Pre and post contracts should have the same indentation level as their
declaration. Put no space between `in`/`out` and an open parenthesis:
```d
int foo(int r)
in(r == 0)
out(result; result == 0)
do { … }
```
```d
int foo(int r)
in { … }
out(result) { … }
do { … }
```

Add guideline for contracts

---

foundation/donate.dd

We've signed up with Flipcause to create and manage targeted donation campaigns. The general fund campaign is permanent and ongoing, and needs to be on the donate page.

Add Flipcause to the donate page.

---

changelog/prerelease.ddoc
ddoc/dub.sdl
ddoc/source/assert_writeln_magic.d
ddoc/source/preprocessor.d

- fix edit links from the beta release page (should point to stable)
- disallow deprecations and fix them (they should be fixed by the one introducing the deprecation in the future)
- Fix changelog links from the stable page pointing to the beta release (see e.g. https://dlang.org/changelog/2.082.1.html)

Improve the dlang.org changelog setup

---

spec/attribute.dd

The existing doc gave the impression that any package could be used to parameterize the `package` attribute and was not specific about which packages are granted access.

Specify effects of parameterized package attrib

---

spec/function.dd

Contrary to contract expressions, `in` and `out` statements require `do` to indicate the function body, but the grammar indicates `do` as optional.
The grammar changes in [DIP1009](https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1009.md#grammar) don't mark do as optional in this case, and DMD complains about a missing `do` with the following code:
```d
int main(string[] args)
in
{
}
{
return 0;
}
```

Fix `do` being optional after a contract statement

---

spec/lex.dd

This is the spec update for https://github.com/dlang/dmd/pull/8738 / https://issues.dlang.org/show_bug.cgi?id=19246
Binary literals like `0b` and `0b_` are now deprecated. A valid binary literal must now have at least one digit after the prefix.

Update spec to disallow invalid binary literals

---

spec/version.dd

Reverts #2466
Sorry @thewilsonator - I was away when this went in.  I've been thinking too much that I've been blocked on this.  Though now I think about it, @TurkeyMan has introduced `__traits(getTargetInfo, "floatAbi")` since I was waiting for the original PR to be merged.  Where possible results of the trait on RISCV could be `soft`, `single`, `double`, or `hard`.  So having a version identifier is not strictly blocking anymore.

Remove D_HardDoubleFloat version identifier.

---

js/run.js
spec/traits.dd
tools/dspec_tester.d

The motivation for the new examples is to demonstrate:
* Pointers are considered scalar but not arithmetic or integral.
* `__vector`s have the same traits as their element type.
* `enum`s have the same traits as the underlying type.
Also made most of the existing code examples runnable while I was at it.

Add more traits doc examples & make existing examples runnable

---

articles/cpptod.dd

`int` is not guaranteed to be at least 32 bits,
it can be as small as 16 bits in some implementations (e.g. AVR chips).
`long` on the other hand is guaranteed to be at least 32 bits.

Fix mistake in C++ code

---

spec/arrays.dd
spec/lex.dd

The first example in the slicing section fails to build as it tries to link the external symbol foo which is not provided.
I also enhanced the other example to be a little bit more interesting for casual visitors. Examples which display only 'Succeed without output.' are completely useless.

Fixed crashing example in slicing section

---

spec/traits.dd

The example code runner wraps the code in a function if no `main` is found, which makes the functions nested and changes attribute inference. Also the message printed by `__pragma(msg)` is formatted `tuple("a", "b", "c")` instead of `("a", "b", "c")` as the comment claimed.

Fix __traits(getFunctionAttributes) example

---

spec/struct.dd

Document postblits/dtors for union fields.

Fix issue 19321

---

index.dd

Twitter changed their policy and implementation for embedded timelines. They no longer allow embeds of hashtag searches. That broke the twitter box in index.html -- it was showing a link instead. This edit replaces it with an embedded timeline for @D_Programming, which is the best we can do now.

Fix broken twitter embed

---

spec/function.dd

add initial documentation for issue 19097

---

dlang.org.ddoc

Adds the [Discord](https://discordapp.com/) chat link for "D Language Code Club" (previously known as "D Code Club" and "Wilds Code Club") to the Community section. (in the following referred to as "Server") Discord is a lot like Slack.
The server currently has 378 members, where we usually have around 100 online users. (comparable to IRC) It is the official chat of [dplug](https://code.dlang.org/packages/dplug), [code-d](https://github.com/Pure-D/code-d) and [PowerNex](https://github.com/PowerNex/PowerNex). We have topic channels around general Programming, web development and OS development, a user-submitted D resources collection, a user-submitted D projects collection and a News channel about D news from the Announce forum and announcing new dub projects. There are also some off-topic …

Add Discord join link to the community section

---

dlang.org.ddoc

Reverts dlang/dlang.org#2539 as it was merged a bit too hastily and without any proper discussion (and as dlang.org her's auto-deployed this change is now live).

Revert "Add Discord join link to the community section"

---

spec/function.dd
spec/memory-safe-d.dd

Document recent dip1000 related changes in:
https://github.com/dlang/dmd/pull/8346
https://github.com/dlang/dmd/pull/8408
https://github.com/dlang/dmd/pull/8504
@WalterBright is this an accurate description?
cc  @JinShil

Document recent -dip1000 changes

---

spec/declaration.dd
spec/expression.dd
spec/simd.dd

Chatty exposition doesn't really belong in a formal spec.
Fixed error in grammar for `Vector`.

spec/vector.dd: make more formal and complete

---

spec/garbage.dd

see https://github.com/dlang/druntime/pull/2440

Add doc for --DRT-gcopt=cleanup

---

spec/class.dd
spec/function.dd
spec/objc_interface.dd

This is the spec update for https://github.com/dlang/dmd/pull/9179.

Add documentation for Objective-C classes

---

spec/garbage.dd

Documentation for https://github.com/dlang/druntime/pull/2418

Document precise GC

---

download.dd

tl;dr: the S3 bucket in use doesn't support HTTP.
HTTP works: http://downloads.dlang.org/nightlies/

Fix nightly download links

---

spec/declaration.dd

The problem is revealed for example when you try to follow the rules for a BaseClass made of an element of a TList.

fix issue 19592 - Rule for IdentifierList is wrong

---

articles/migrate-to-shared.dd

Fix the text discussing performance considerations of TLS globals (the difference is not 3 instructions, and TLS is not faster with or without PIC enabled).

TLS access is slower than classic global vars

---

spec/unittest.dd

DD_SUBLINK expects three arguments.

Fix AssertExpression link spec/unittest

---

articles/migrate-to-shared.dd

The previous change was not fair to Windows code. With these changes, the discussion is longer, but fairer for all platforms.
I also added a mitigation idea of grouping related variables into a struct such that TLS overhead is only paid once.
@jacob-carlborg @ZombineDev

Improve TLS-related perf discussion

---

dcompiler.dd

- Fix overwritten LIB macro (the macro was never used, but overwrote the actual LIB macro)
- Use individual install steps for Linux (all other pages have them too) + fix list indentation
- Fix links to the packages and install script
This page is quite complicated, so it's better to check the resulting diff of DAutoTest here.

Fix a few visual flaws in the DMD help page

---

index.dd

It's been 1.5 years now since https://github.com/dlang/dub/pull/1081 has been merged.
In other words all supported D versions of Vibe.d come with a DUB with default names (>=1.5.0).

Remove dummy name from the vibe.d example
