dlang/dlang.org

- hash-map.dd
Needed by: https://github.com/D-Programming-Language/druntime/pull/1070
> Document AA .byKeyValue().

- posix.mak
- generic shallow clone rule, either clones default branch (master)
or a specific version
> build a stable dub version for dpl-docs

- grammar.dd
- statement.dd
https://issues.dlang.org/show_bug.cgi?id=13895
> Issue 13895 - Declaration grammar is insufficient

- function.dd
Implements suggestions from #690.
> Add Function Templates section to function.dd

- html.ddoc
See https://github.com/D-Programming-Language/druntime/pull/1091#discussion_r22726125
> Add C header generic blurb to ddoc macros.

- index.dd
there should be a link to the dconf15 website
> link to Dconf15

- expression.dd
https://issues.dlang.org/show_bug.cgi?id=13700
Corresponding dmd PR: https://github.com/D-Programming-Language/dmd/pull/4209
> Issue 13700 - Rejected valid conversion from slice to fixed size array

- .gitignore
- dpl-docs/views/layout.dt
http://forum.dlang.org/thread/m8rn6c$1ntq$1@digitalmars.com
Ping @andralex
> Use code font for module name

- ddoc.dd
Please review. @adamdruppe you need to fix backticks - multiline backticks don't work.
> More backtick misuse

- grammar.dd
https://issues.dlang.org/show_bug.cgi?id=13325
> Issue 13325 - __vector not documented in language specification

- .gitignore
- css/cssmenu.css.dd
- dlang.org.ddoc
- doc.ddoc
- js/cssmenu.js
- std.ddoc
- win32.mak
> CSS menu stuff

- css/cssmenu.css.dd
> Made menus narrower to save screen real estate

- ascii-table.dd
> fix ascii table

- js/cssmenu.js
See https://github.com/D-Programming-Language/dlang.org/pull/800#issuecomment-70687208
> Fix visual issue that puts "+" back as icon on uncollapsed menu

- css/style.css
Regression introduced in 1b0cecf0c61bc6eb6225b2fe9f8976bf1b637284
> Fix mobile UI

- std_navbar-prerelease.ddoc
Required by: https://github.com/D-Programming-Language/phobos/pull/2879
> [Phobos PR 2879] Update navbar for new std.algorithm submodules.

- css/cssmenu.css.dd
- js/cssmenu.js
Implement MattCoder's mockup from
http://forum.dlang.org/post/dfflvgdzanirmsqgxgxz@forum.dlang.org
> Tweak colors

- css/style.css
> more headroom for headings

- index.dd
> turn list items of Convenience/Power/Efficiency to paragraphs

- css/style.css
Properties before/after:
std.range before/after:
> use book style for all tables; also increase row spacing a little

- std_navbar-2.066.1.ddoc
Regression introduced in e795453757a9586cf8dbc9ef7e3bd0f1373dabac
> Fix library menu header

- posix.mak
- Don't use \t zsh-ism when building sitemap
- Add --chmod to rsync
CC @andralex
> posix.mak fixes

- css/style.css
- doc.ddoc
See commit messages for what changed exactly.
> align title "D Programming Language" with content text

- grammar.dd
- iasm.dd
https://issues.dlang.org/show_bug.cgi?id=14047
> Issue 14047 - "this" missing from AsmPrimaryExp grammar

- dlang.org.ddoc
- doc.ddoc
- std.ddoc
Also DRY out other minor differences between doc.ddoc and std.ddoc.
> use same search box on phobos pages as elsewhere

- index.dd
* drop old DConf links; they're accessible through the DConf 2015 site
* drop heading
* give some room to breathe
> fiddle with DConf

- css/cssmenu.css.dd
- std.ddoc
- std_navbar-prerelease.ddoc
Alternative with separate "std.experimental" menu
> navbar for std.experimental.logger

- css/style.css
- dlang.org.ddoc
- js/cssmenu.js
Also replaces the jquery animation for the mobile search box with CSS.
> get rid of HTML duplication for mobile header

- changelog.dd
- declaration.dd
- grammar.dd
https://issues.dlang.org/show_bug.cgi?id=481
Corresponding compiler change: https://github.com/D-Programming-Language/dmd/pull/3615
> Issue 481 - Letting compiler determine length for fixed-length arrays

- changelog.dd
- links to documentation (prerelease until 2.067 is out)
> mention initOnce in changelog

- changelog.dd
Well, this is probably not sufficient information on this change, but writing documentation isn't exactly one of my strengths.
> Add struct destructor information to the changelog

- css/style.css
- index.dd
> another jab at the slogan

- version.dd
Frontend compiler PR here: https://github.com/D-Programming-Language/dmd/pull/4367
> Update predefined versions to include FreeStanding.

- std_navbar-prerelease.ddoc
Companion to https://github.com/D-Programming-Language/phobos/pull/2989
> Fix links std_xyz_package.html -> std_xyz.html

- .htaccess
- posix.mak
> Add .htaccess for std.container redirect

- dstyle.dd
> missing phobos space

- .htaccess
- posix.mak
- avoids special rule in modlist.d tool
- add rewrite to htaccess
> move std_container_package.html to std_container.html

- posix.mak
- they require checked out sources
> fix dependencies for modlist targets

- changelog.dd
Implemented in https://github.com/D-Programming-Language/dmd/pull/3651
FYI @MartinNowak
> Mention package protection attribute in changelog

- changelog.dd
- mention sealed references
- mention fixed with statement
- fix permalinks for enumerate and handle
- add missing paren
> changelog updates

- css/style.css
- dlang.org.ddoc
- index.dd
The notices on the front page look a bit ad-hoc at the moment.
> Nicer front page notices

- css/style.css
- dlang.org.ddoc
- index.dd
> Notice tweaks

- css/style.css
- dlang.org.ddoc
- index.dd
- square blocks with less shadow
- turn whole block into clickable link
- use dark background + accent color
> improve notices

- changelog.dd
Some shameless self promoting on my part. Still IMO worth mentioning.
> Added Logger info to changelog

- deprecate.dd
See https://github.com/D-Programming-Language/druntime/pull/1202
> deprecate.dd - Updated version for removal of clear

- dpl-docs/dub.selections.json
Fixes template constraints and missing unit text examples, as well as several other issues.
It also enables conditional HTML file generation based on stored hashes to speed up the build process, as well as rsync uploads:
https://issues.dlang.org/show_bug.cgi?id=13946
Also fixes display of enum values:
https://issues.dlang.org/show_bug.cgi?id=13961
> Upgrade to latest DDOX

- dcompiler.dd
1. add href names for all switches instead of just a few
2. add cross linking for switch references
3. add helpful links for some other references
4. adjust styling for consistency
> add lnames and links for all switches

- declaration.dd
- grammar.dd
See the corresponding pull request here:
https://github.com/D-Programming-Language/dmd/pull/4516
> Update the grammar to allow Args[0].T to be a type.

- changelog.dd
> Add changelog entry for issue4733

- getstarted.dd
I believe that finding an IDE is an important part of getting started with D, and it should be listed on the Getting Started page.
> add link to IDEs page

- deprecate.dd
https://github.com/D-Programming-Language/dmd/pull/4607
> Update deprecated to reflect that if (v; e) syntax is now gone

- garbage.dd
- html.ddoc
> #973 fixup

- index.dd
- js/cssmenu.js
http://forum.dlang.org/post/mi0cel$10am$3@digitalmars.com
> Add your-code-here rotation for the front page plus new example

- posix.mak
- use -conf=path/to/dmd.conf for stable dmd
> update stable dmd and dub

- css/style.css
- dlang.org.ddoc
- index.dd
http://forum.dlang.org/post/cislkitgxqepfnfqueiq@forum.dlang.org
> Add separate download/changelog links to index page notice

- expression.dd
In accordance with http://forum.dlang.org/thread/pgrfvbffrviwjudeawvz@forum.dlang.org#post-mjtihl:2424a3:241:40digitalmars.com.
> Fix documented order of evaluation

- posix.mak
- win32.mak
the next first step in removing stream from phobos
https://github.com/D-Programming-Language/phobos/pull/3352
> remove stream from the index

- posix.mak
$^ was inserting DMD as an input file.
> PR #1019 fixup

- pragma.dd
And since gawd hath invented alpha sort, so shall it be done, and it was good.
Added navigation links.
Converted tabs to spaces.
No text changes.
> refactor, add links

- getstarted.dd
We should take newbies by the hand on "Getting Started". And as far as I'm
aware, Ali's book is the best thing we have in that category.
Also, drive-by fix of bad parenthesis.
> mention Ali's "Programming in D" prominently on "Gettting Started"

- dlang.org.ddoc
- latex.ddoc
- spec.dd
> dlangspec.pdf: table of contents

- changelog.dd
See https://github.com/D-Programming-Language/phobos/pull/3356
> Add changelog entry for the addition of hasUDA to std.traits

- css/style.css
- dlang.org.ddoc
- images/hamburger.svg
- js/dlang.js
- posix.mak
As the icon is one of the first things in view for the mobile view, it should be displayed as quickly as possible.
> Improve hamburger icon load time

- deprecate.dd
Hitting two bird with one stone, as per discussion here: https://github.com/D-Programming-Language/dlang.org/pull/976#issuecomment-96258429
> Reorder deprecated features.

- changelog.dd
Do not merge until https://github.com/D-Programming-Language/phobos/pull/3421 is merged.
> Document getSymbolsByUDA

- .htaccess
I'll delete the temporary page if this gets accepted.  I have a couple more I'd like to do, but this is an initial test that I'm doing things right.
> Add 301 redirect for pages moved to the wiki.

- regular-expression.dd
It's been long over due. Time to:
- remove usage of old API with global flags
- adjust wording
- stop warning about CT version being unstable
- link to benchmarks
Benchmarks repo is somewhat WIP but has some good stuff to run and is going to improve from now on.
> Update regex article

- arrays.dd
- code_coverage.dd
- expression.dd
- property.dd
These meant left-hand/right-hand side or operand.
> fix wrong usage of "lvalue" and "rvalue"

- abi.dd
https://issues.dlang.org/show_bug.cgi?id=14579
> Issue 14579 - [SPEC] No specification on modifiers in TypeDelegate symbols

- grammar.dd
- iasm.dd
https://issues.dlang.org/show_bug.cgi?id=13302
> Issue 13302 - Inline ASM grammar is not left-associative

- glossary.dd
Bugzilla: https://issues.dlang.org/show_bug.cgi?id=14328
> Issue 14328 - The terms "lvalue" and "rvalue" should be added to the glossary

- changelog.dd
requires https://github.com/D-Programming-Language/phobos/pull/3536
> remaining changelog entries for 2.068.0

- doc.ddoc
Dub should be under the tools section.
> doc.ddoc: Add dub to sidebar

- changelog.dd
[Issue 14900 – 2.068.0 change log example does not compile](https://issues.dlang.org/show_bug.cgi?id=14900)
> Issue 14900 - fix changelog example

- overview.dd
Someone on SO was mislead by this, quick simple fix.
> change old char[] to modern string

- index.dd
- hacked at one of the last D Berlin meetups
> more examples for YourCodeHere

- hash-map.dd
possible a few more sites are affected.
but someone mentioned this in the forums:
http://forum.dlang.org/post/xajemvazpogwrftioxkp@forum.dlang.org
> add override statements to AA example

- doc.ddoc
Per: http://forum.dlang.org/thread/kxvzuikgxmoxpduxdjel@forum.dlang.org
> Put bugtracker link under Community instead of Resources.

- dcompiler.dd
Related dmd PRs:
https://github.com/D-Programming-Language/dmd/pull/4955
https://github.com/D-Programming-Language/dmd/pull/4862 (follow-up to the above)
> remove documentation for -property

- expression.dd
- grammar.dd
https://issues.dlang.org/show_bug.cgi?id=14745
Update grammar to reflect [the compiler fix](https://github.com/D-Programming-Language/dmd/pull/4800).
> Issue 14745 - Qualifiers rejected for delegate literals

- changelog/upcoming.dd
For D-Programming-Language/phobos#3022
> Add changelog entry for std.math.cmp

- changelog/2.068.2.dd
- changelog/2.069.0.dd
- changelog/changelog.ddoc
- changelog/index.dd
- css/style.css
- download.dd
- win32.mak
- changelog for 2.069.0
- add beta channel to download page
> beta preparation

- changelog/2.069.0_pre.dd
@MartinNowak made suggested changes
> Mention the codegen improvements

- changelog/2.069.0_pre.dd
- changelog/changelog.ddoc
- changelog/prerelease.ddoc
- add new NXREF/NCXREF macros for nested anchors (with leading .)
- simplify REF macros by using LINK2
> fix std.stdio.File.this link

- garbage.dd
Copy-pasted from the 2.067 change log.
> [issue 15078] GC documentation should reflect 2.067 changes

- index.dd
- js/run-main-website.js
- also add pow (^^) to the rpn calculator
> provide input for examples

- operatoroverloading.dd
Add fully working code example of a 2D array that overloads the indexing, slicing, and opDollar operators, since it may not be obvious what is the correct way to implement `opSlice` and `opDollar`.
> Full working example of 2D array with operator overloading.

- getstarted.dd
- overview.dd
https://issues.dlang.org/show_bug.cgi?id=13624
* add link in getting started to overview page
* add links in sections to pages with more info
* make it clear that D supports 64 bit
* slight change in suggestions for a first language (does anyone still learn Basic anymore?)
* convert the example program to use more D style code
To mark this issue as fixed, I think that the another example program should be added showing range based code, and a section on ranges should be added. I broke up the changes to make it easier to review.
> Fix for issue 13624 (Part 1)

- dpl-docs/dub.json
- dpl-docs/dub.selections.json
- dpl-docs/views/layout.dt
- prettify/prettify.css
Updates to the latest versions of vibe.d (compiles with the latest DMD 2.069.0 beta) and Ddox (containing various fixes).
> Upgrade dpl-docs dependencies.

- overview.dd
automatic replacement of hardware tabs with four spaces
> Fix for issue 13624 (Part 2)

- function.dd
> function.html: add simple navigation

- overview.dd
Rounding out the changes to the overview page, I added in a section that covers the basic ideas of ranges with some examples and a links to more thorough introductions. I think this is enough to mark this issue as fixed.
> Fix for issue 13624 (Part 3)

- expression.dd
- grammar.dd
https://issues.dlang.org/show_bug.cgi?id=15250
> Document variations on slice expressions to fix issue 15250

- css/print.css
- css/style.css
- js/dlang.js
- spec/function.dd
Alternative solution to https://github.com/D-Programming-Language/dlang.org/pull/1145.
~~I was unable to float the contents section to the right or left and have the contents of the page reflow around it without making the `pre` sections become only as wide as their content. This is *fine* as it is, but if someone has a solution to that, that would be awesome.~~
> function.dd: Table of Contents 2

- css/print.css
- css/style.css
* ~~removed overqualifed css rules~~
* removed commented out old code
* changed `0px` and `0em` to `0`
* added some extra prefixed css rules
* made long lines under 80 characters
> Cleaned up css files

- overview.dd
* Added the contents box
* Moved the D mascot image to the left as it was awkward to have that much focus on the right of the page.
* Removed some unnecessary new lines.
> Add contents box to the overview page

- dlang.org.ddoc
- spec/spec.ddoc
And make it the default on language reference pages.
Google has picked up the new locations, time to do this.
> add search option for language reference

- spec/function.dd
Typo error, bar instread of foo
> Typo error, bar instread of foo

- dlang.org.ddoc
- std.ddoc
Let's see if this does the trick.
> Fix MREF and REF for phobos-prerelease target

- spec/hash-map.dd
Also added a section on construction and reference semantics.
> Add documentation for new clear method (for 2.071)

- spec/expression.dd
- spec/grammar.dd
- spec/version.dd
D-Programming-Language/dmd#5363
> Grammar change for D-Programming-Language/dmd#5363

- spec/abi.dd
Simply moved the line up.
https://issues.dlang.org/show_bug.cgi?id=15644
Spec change for:
https://github.com/D-Programming-Language/dmd/pull/5397
> fix Issue 15644 - Switch object layout ABI to MI style

- spec/class.dd
- spec/grammar.dd
https://issues.dlang.org/show_bug.cgi?id=15666
> Fix issue 15666

- spec/attribute.dd
- spec/grammar.dd
See D-Programming-Language/dmd#5302
FYI @Hackerpilot
> [2.071.0] Document deprecated attribute as accepting AssignExp

- css/style.css
- index.dd
- js/run.js
Accessibility improvements:
* controls now accessible by pressing tab
* WAI-ARIA attributes added
* still has graceful degradation without JavaScript
Other improvements:
* boxes now open with quick sliding animation
* (subjective) less work in the macro means easier maintainability by
web developers new to D
> Rework expandable code example boxes

- dlang.org.ddoc
> use https for google search on main page

- spec/template.dd
> [trivial] Mention "eponymous templates" in section title

- spec/template.dd
Added content to template doc page.
> Additional template doc example

- CONTRIBUTING.md
- changelog/2.067.0.dd
- changelog/changelog.ddoc
- dlang.org.ddoc
- download.dd
- dpl-docs/views/layout.dt
- faq.dd
- index.dd
- posix.mak
- rdmd.dd
- std_consolidated.ddoc
update links to the new home :)
> update links to dlang

- dpl-docs/views/ddox.inc.module-tree.dt
See https://forum.dlang.org/thread/nerjg7$2tqv$1@digitalmars.com
> Move package.d modules navigation entries into their package menu.

- spec/template.dd
This is to be applied in tandem with https://github.com/D-Programming-Language/phobos/pull/3756
> Update template spec for tuple -> AliasSeq renaming

- spec/struct.dd
- spec/template-mixin.dd
Based on suggestions from https://issues.dlang.org/show_bug.cgi?id=15957
> update template mixin and opAssign spec to reflect what compiler actually does

- spec/contracts.dd
See https://issues.dlang.org/show_bug.cgi?id=6453
> Update spec after issue 6453

- index.dd
It will probably take a couple of weeks until the videos are ready, so this was the best that came to my mind as filler.
> replace outdated dconf notice - fix issue 16040

- dlang.org.ddoc
- index.dd
Adds a link to tour.dlang.org.
Ping @stonemaster.
> add link to tour.dlang.org

- css/style.css
> quickindex: hide empty caption and use auto-width

- dpl-docs/views/layout.dt
It had gone out of sync with the Ddoc one.
> DDOX: update top menu

- orgs-using-d.dd
From: http://www.infognition.com/blog/2014/why_d.html
CC @thedeemon (head of Infognition)
> Orgs using D: add testiomonial from Infognition

- orgs-using-d.dd
- dont hyphenate the uses
- removed duplicate "hiring"
> Visual improvements to orgs using D

- orgs-using-d.dd
> Sort orgs using D alphabetically

- orgs-using-d.dd
follow-up to #1312
CC @leandro-lucarella-sociomantic
> but I was asked to change the description of the company to "Real-time personalized advertising".  I hope that's OK.
Sure - your only enemy is the font. If I add "personalized", it will wrap to two lines. Any ideas?
(I changed it now to "Real-time advertising")
> Also, there are 2 other DConf talks that might be relevant to describe what the company do or its relationshipt to D:
Updated to the latest as it is a summary of all the great stuff Sociomantic has been doing for/with D.
> Orgs using D: update sociomantic's description

- orgs-using-d.dd
Based on http://dconf.org/2014/talks/crapuchettes.html
> An industry success story: EMSI needed to improve its data processes with n-­dimensional dataset processing, in-­memory data manipulation, data type checking, internal testing, and code correctness. D was the language of choice because it couples low-­level performance with high-­level design.
Also according to @Hackerpilot emsi is doing a rebranding to Emsi.
> Orgs using D: Update Emsi's description

- orgs-using-d.dd
Apparentely it's well defined how to express a ratio:
https://en.wikipedia.org/wiki/Ratio#Notation_and_terminology
Also ends an ending dot.
> Orgs using D: nitpick in Tripaneer quote

- changelog/2.013.dd
- d-floating-point.dd
- glossary.dd
- gsoc2011.dd
- gsoc2012.dd
- spec/cpp_interface.dd
- spec/objc_interface.dd
- spec/version.dd
- template-comparison.dd
- variadic-function-templates.dd
Sister PR to https://github.com/dlang/phobos/pull/4413
> Fix broken URLs

- areas-of-d-usage.dd
- index.dd
- posix.mak
As the _first five minutes matter_, I thought it would be nice if we have an overview of areas in which D is used.
It is different to the great [Overview](http://dlang.org/overview.html) page as it tries for every area to inform about
-  applications written in D
-  key reasons/selling points
That being said, this document is a draft and your feedback & review is highlighy appreciated.
If I left out an area or you miss a great application - please let me know!
Also note that I propose to put this on dlang.org, because in contrast to the wiki we can go through the very helpful peer-review stage and have the official branding.
> Areas of D usage

- spec/expression.dd
Document the type of pointer difference.
> pointer subtraction yields ptrdiff_t

- index.dd
DFeed change: https://github.com/CyberShadow/DFeed/commit/c3199d6a01887974345d3f0f72eee1f982419e9c
> index.dd: Pre-populate subject line for "your code here" submissions

- spec/contracts.dd
I just found this by accident:
and I really like the our D man, see also
- http://dlang.org/overview.html
- https://dlang.org/spec/iasm.html
Unfortunately the git history doesn't tell why it was removed, maybe @aG0aep6G or @CyberShadow know?
We need more of such great artwork
Btw I don't know the author, but he seems to tweet a bit: https://twitter.com/DlangGuy
> uncomment dman against bugs

- posix.mak
- to check json validity @Cybershadow
> add chm-nav.json target to posix.mak

- areas-of-d-usage.dd
- index.dd
- macros.ddoc
- orgs-using-d.dd
> A few tweaks to the recent changes

- index.dd
From Andrei:
http://forum.dlang.org/post/ni2flg$2ge3$1@digitalmars.com
CC @mdparker - we should probably keep an eye on this news spot and update it from time to time.
Now that we have @CyberShadow's awesome auto-deploy, there's no excuse ;-)
> add video-wrapup of dconf

- html.ddoc
- js/listanchors.js
I guess I've broken them with #1338.
> fix anchor thingies on phobos pages

- spec/attribute.dd
- spec/grammar.dd
Spec update for the compiler change: https://github.com/dlang/dmd/pull/5750
> Issue 9766 - align(n) with n compile-time constant

- orgs-using-d.dd
Inspired by @llaine and #1381, I thought it's worth adding easily accessible information for future org additions.
> Provide infos how to add an org using d

- spec/contracts.dd
> fix oversized anti-bug d-man on mobile

- overview.dd
just saw this by skimming over the page. In general I think we should replace this example program with sth. else, because it's not very D-idiomatic and I think we can find a better example. 
Has someone a good idea?
> let D example program conform to DStyle

- orgs-using-d.dd
It seems like I messed the alphabetical order after with the ecratum rebase. Sorry about that.
Btw I remember there was a discussion about ordering the companies after their size / social impact factor. Did we come to a consensus there?
> Orgs using D: ebay before ecratum

- orgs-using-d.dd
https://github.com/dlang/dlang.org/pull/1409#issuecomment-231295391
> orgs-using-d: Fix Ecratum's "Hiring" link

- deprecate.dd
- spec/grammar.dd
> Issue 12558 - Document implicit catch statement deprecation

- orgs-using-d.dd
> [Orgs using D]: add quote from Tamedia Digital

- js/show_contributors.js
Fixes the problem Andrei has with the AutoTester & enables the contributors list for druntime.
> ignore invalid files for contributor listing & enable druntime

- spec/attribute.dd
- spec/module.dd
- Rename to visibility attribute
- Expand documentation on name lookup in module doc
CC @MartinNowak
> Fix issue 16004 - Document changes to protection attributes

- spec/template.dd
fix issue https://issues.dlang.org/show_bug.cgi?id=16370
> Reword limitation on static fields for interfaces to be clearer

- dpl-docs/views/ddox.layout.dt
- dpl-docs/views/inc.disqus.dt
Reverts dlang/dlang.org#1363
@andralex
> Revert "Kill disqus"

- latex.ddoc
- spec/grammar.dd
- spec/lex.dd
- spec/traits.dd
https://issues.dlang.org/show_bug.cgi?id=16441
> Added doc for __FILE_FULL_PATH__

- spec/cpp_interface.dd
- spec/grammar.dd
> Add introductory sentence for extern(C++).

- CONTRIBUTING.md
Reverts dlang/dlang.org#1448
Sorry guys, I thought we would have the discussion on the PR
> Revert "Add a small writing style guide"

- deprecate.dd
Reverts dlang/dlang.org#1445. I'll pull this now.
> Revert "Fix relative links in deprecate page"

- overview.dd
Also removed some obsolete points. The overview could still be a lot better, but this fixes some of the worst of it.
> Remove comparisons with C++

- changelog/2.071.2_pre.dd
> removed unused ddoc right paranthesis

- changelog/2.071.2_pre.dd
- spec/traits.dd
This reverts commit 2ecabf0dab63dcdb935af859093ffc05b366c3ec, reversing
changes made to 37f4dee570ff26a03b497ea4a4784b64b2771014.
> Revert "Merge pull request #1444 from MartinNowak/fix15907"

- spec/statement.dd
Related to https://issues.dlang.org/show_bug.cgi?id=16193
> add  to opApply() delegate parameter

- std.ddoc
see http://forum.dlang.org/post/b685b75c-28ff-2748-55e3-c6d317da3371@erdani.org
> [TRIVIAL] [EASY] [PULL DON'T THINK] Workaround for ddox bug

- spec/arrays.dd
see https://forum.dlang.org/post/ivjnopgnimqedmsnxpeo@forum.dlang.org
> Clear up some array usage

- overview.dd
A second pass through overview.dd
> more fixes for overview.dd

- changelog/2.071.2_pre.dd
> Revert "remove wrong `P` around `LI`s"

- html.ddoc
- std_consolidated.ddoc
> Revert "[don't merge before 2.072] Remove last standing WEB macro"

- win32.mak
> repair (hopefully) win32.mak build target

- changelog/2.072.0_pre.dd
- see https://github.com/dlang/dmd/pull/5897
- see https://github.com/dlang/dmd/pull/5830
> changelog entries for unrestricted unions/scope value params

- foundation.dd
We should proudly share that info!
> The foundation is tax-exempt

- .htaccess
- 404.dd
- posix.mak
- win32.mak
https://issues.dlang.org/show_bug.cgi?id=16147
> fix Issue 16147 - Provide shiny 404 error pages

- dcompiler.dd
documents changes by https://github.com/dlang/dmd/pull/6244
> document new command line switch -mscrt=libname

- dcompiler.dd
https://issues.dlang.org/show_bug.cgi?id=16914
> document -mavx switch

- dcompiler.dd
Document https://github.com/dlang/dmd/pull/6306
> change -mavx switch to -mcpu

- index.dd
In general we should try to keep the "News" section fresh & have an eye to keep it up-to-date ;-)
> Add a message about the donation page on the frontpage

- spec/module.dd
Add documentation for dlang/druntime#1720
> Add documentation for "deprecate" cycle handling

- spec/attribute.dd
- spec/function.dd
- spec/grammar.dd
Examples (essentially) taken from: https://wiki.dlang.org/DIP25
> [spec] Document return attribute

- changelog/2.073.0_pre.dd
> Fix  changelog/2.073.0_pre typo

- js/run_examples.js
Follow-up to https://github.com/dlang/phobos/pull/4966
(slowly going towards the target of having no blacklist)
> Update runnable modules blacklist

- css/ddox.css
- dpl-docs/views/ddox.overview.dt
Fixes rejectedsoftware/ddox#126
> Avoid auto-hyphenation of code in the dpldocs documentation.

- foundation.dd
> Add address

- dcompiler.dd
Corresponding PR is https://github.com/dlang/dmd/pull/6286
> document -mv compiler switch

- spec/abi.dd
Document changes by https://github.com/dlang/dmd/pull/6496
> FuncAttrScope is now mangled as Nl

- posix.mak
This will add the "DMD as a library" documentation to the release pages of Ddoc and Ddox.
The DMD pages have been part of the prerelease pages [since four months](https://github.com/dlang/dlang.org/pull/1581):
Ddoc: https://dlang.org/phobos-prerelease/ddmd_mars.html
Ddox: https://dlang.org/library-prerelease/ddmd/mars.html
As we got _no_ feedback I feel like the only way people will notice (and thus maybe start to improve it), is exposing the documentation on the release docs.
CC @andralex @RazvanN7 
(changing the documentation generation from `ddmd` to `dmd` is rather trivial and already needs to be done for the prerelease pages anyways.)
> Add DMD to the release pages of Ddoc and Ddox

- spec/traits.dd
Implementation: https://github.com/dlang/dmd/pull/6829
Enhancement: https://issues.dlang.org/show_bug.cgi?id=17425
> add __traits(getParameterStorageClasses(f, i)

- deprecate.dd
Follow-up to https://github.com/dlang/dlang.org/pull/1672
> Deprecate.dd: clear error column for sort/remove deprecation

- posix.mak
> Rename DMD_REL to DMD_STABLE v2

- rdmd.dd
We should really auto-generate this like e.g. DUB does ...
> Fix Issue 17262 - Better docs for rdmd

- spec/garbage.dd
see https://github.com/dlang/druntime/pull/1798
> document precise scanning of DATA segment

- changelog/changelog.ddoc
> changelog: Link to all versions page in the sidebar unconditionally

- css/style.css
> css: Enforce input/textarea background only on dlang.org

- areas-of-d-usage.dd
Remove link to std.experimental.ndslice.
> Update Areas of Usage

- template-comparison.dd
> Fix broken link to cpp0x

- dcompiler.dd
- doc.ddoc
- freebsd.ddoc
- linux.ddoc
- osx.ddoc
- windows.ddoc
- The issue is about the fact that we never mention that DUB is part of the release archives
- I tried to update the file contents archive and link to them (img + text)
- See below for the actual file listings from the archives
CC @MartinNowak @CyberShadow
File archives
----------------
- 2.074.1
- for better readability I removed the hits from other directories (the default configs of every OS are part of nearly all archives)
```
> als dmd.2.074.1.windows.7z | grep bin/
2017-05-31 17:29:06 ....A         1011               dmd2/windows/bin/README.TXT
2017-05-31 17:41:22 ....A      3772330               dmd2/windows/bin/d.chm
2017-05-31 17:28:32 ....A         4630               dmd2/windows/bin/sc.ini
2017-05-31 17:29:06 ....A       215274               dmd2/windows/bin/windbg.hlp …
```
> Fix 17480 - Update file contents of the release archives & link to them on downloads.html

- js/run.js
Follow-up to https://github.com/dlang-tour/core/issues/562 and https://github.com/dlang-tour/core/pull/563
> Update examples Export URL to run.dlang.io

- index.dd
> Add example about std.process

- changelog/2.006.dd
- changelog/2.070.0.dd
- changelog/2.072.0.dd
- changelog/2.075.0_pre.dd
- chm-nav.dd
- chmgen.d
- d-array-article.dd
- dlang.org.ddoc
- posix.mak
- spec/class.dd
- spec/garbage.dd
- spec/simd.dd
- spec/spec.ddoc
Fixes broken links and prepares things for Phobos fixes and part 2.
> chmgen stuff, part 1

- dlang.org.ddoc
- index.dd
Follow-up to https://github.com/dlang/phobos/pull/5582#issuecomment-313922823
> BTW, the dlang.org front page's "Contribute" section should link to a wiki page which lists entry-level tasks such as these.
I have started to rework https://wiki.dlang.org/Get_involved a bit, but, of course, more love is always welcome!
> Link to get involved

- index.dd
Marking this "needs work" as I would need to remove `RUNABLE_EXAMPLE` from the `EXTRA_EXAMPLE` macro.
> [Idea] Add example about running a minimal web server

- index.dd
> Repair runnability of 'Invoke external programs' example

- .gitignore
- changelog/changelog.ddoc
- changelog/update_nav.sh
- posix.mak
This reverts commit a9c048297e468c4a6ed640a6d8c4f3d3ab045a7e, reversing
changes made to ea0c2de19520e2b8ebab76bbb8fe217c17be2f78.
See https://github.com/dlang/dlang.org/pull/1823#issuecomment-315605644 and https://github.com/dlang/dlang.org/pull/1821#issuecomment-315603750. Let's take the time necessary to do this properly.
> Revert "Merge pull request #1817 from wilzbach/use-pending-for-changelog"

- .gitignore
Files in question:
```
images/qualifier-combinations-eps-converted-to.pdf
images/qualifier-conversions-eps-converted-to.pdf
```
> Ignore generated PDF files

- index.dd
> Update high-level vision to 2017H2

- posix.mak
https://github.com/dlang/druntime/pull/1605#issuecomment-319419160
> posix.mak: Build Phobos stable with Druntime stable, not master

- index.dd
Initial submission by Max Haughton, minimized by Timon Gehr.
http://forum.dlang.org/post/ol9ocn$13rs$2@digitalmars.com
Updated a bit to conform to D Style and horizontal space.
Blocked by general availability of static foreach in released compilers.
> Add RPN calculator front-page example

- .gitignore
- chmgen.d
- posix.mak
- win32.mak
> chmgen: Emit d.tag in JSON syntax too

- spec/arrays.dd
> Purge the .sort and .reverse array properties

- changelog/2.076.0.dd
introduced in https://github.com/dlang/dlang.org/pull/1880
> Fix master white space check

- changelog/2.076.0.dd
- posix.mak
Cherry-pick 2446f951f66abd26252ba2874d66e71d62631083 and 8e34ed084d0b9cbb176581abf9041e36a9615064 to stable to unbreak stable build.
> Cherry-pick build fixes from master to stable

- changelog/2.076.0.dd
- posix.mak
https://github.com/dlang/dlang.org/pull/1885
> Redo #1885 with correct branch

- changelog/2.076.0.dd
I removed two duplicates the better c and static foreach
> remove duplicates in changelog of 2.076.0 release

- index.dd
Adapted from
https://forum.dlang.org/post/dvjltobyaaxoihhqywhp@forum.dlang.org
> Add hex viewer runnable example

- js/listanchors.js
See also: https://github.com/wilzbach/dlang.org-archives/commit/3b62b5782768e8ed7fc6673fdbab166f36bd9de6
> Bump docarchives to 2.076

- posix.mak
CC @MartinNowak @CyberShadow (follow-up to #1684)
> Rename {DMD,DRUNTIME,PHOBOS,VERSION}_STABLE -> _LATEST

- posix.mak
Needed for https://github.com/dlang/dmd/pull/7135
See also: https://github.com/dlang/dmd/pull/7135#issuecomment-329357396
> Prepare dlang.org for the ddmd -> dmd transition

- orgs-using-d.dd
Sorry for the trouble.  I made a mistake when copying the link over for my testimonial.  I should have caught this before making a pull request.
> fix incorrect link for ctrecordings testimonial

- dcompiler.dd
- spec/version.dd
Depends on https://github.com/dlang/dmd/pull/7248.
Previous PR: https://github.com/dlang/dlang.org/pull/1892
> Rename D_betterC to D_BetterC

- download.dd
Install the correct "d-apt" public key
> "d-apt" public key

- index.dd
- see http://vibed.org/api/vibe.http.server/listenHTTP
> use string setting for listenHTTP

- index.dd
> Fix Issue 17723 - Replace Facebook on the front page with Weka.io

- js/run.js
Somehow the button got broken in the past - this PR fixes this.
> Fix 'Open in Editor'-Button

- index.dd
Before:
After:
Copy from the mail to @rostyboost
> Hi Sebastian,
> Sure you can do that. Just cc me on the related PR.
>
> Thanks!
>Benoît
Thanks a lot Benoît!
CC @JackStouffer @ZombineDev @rostyboost
> Issue 17723 - Replace Weka.io on the front page with Netflix

- spec/struct.dd
* Add member initializer example.
* `memberName:expression` can be used for non-static variables too.
* Move non-static struct initialization paragraph to dynamic initialization.
* Minor tweaks.
> Update struct initializer docs

- posix.mak
From https://github.com/dlang/phobos/pull/5617#issuecomment-316623709
> Regenerate changelog on new changes

- spec/statement.dd
AFAICT this simple change should work.
CC @UplinkCoder
> Fix Issue 17265 - WithStatement: Find better Example for what with really does

- circleci.sh
- posix.mak
- sitemap contained invalid links to ../dmd/changelog/PR7356.dd.html
caused by conflicting CHANGELOG_FILES variable
> fix chmgen tag generation

- js/run.js
Follow-up to https://github.com/dlang/dlang.org/pull/1955 which has been merged a bit too quickly ;-)
> Fix runnable examples

- spec/attribute.dd
- spec/class.dd
- spec/declaration.dd
- spec/function.dd
- spec/module.dd
- spec/statement.dd
Code samples don't look good when wrapping around in the PDF document.
> [TRIVIAL] [PDF] Normalize code line lengths to 80 columns or less

- changelog/changelog.ddoc
- posix.mak
See also: https://github.com/dlang/tools/pull/252 and https://github.com/dlang/dlang.org/pull/1838
> Remove NIGHTLY_VERSION and --nightly

- spec/interface.dd
> dlangspec.pdf: Replace $(D from code comments

- posix.mak
Inspired by the usage of `$G` and `$D` in the DMD Makefile (we already use `$G` here)
The idea here is that this puts emphasis on the important bits, e.g. compare `$(DOC_OUTPUT_DIR)/sitemap.html` with `$W/sitemap.html`
> Use $W instead of DOC_OUTPUT_DIR for better visibility

- spec/attribute.dd
> Revive #1040 - spec/attributes.d

- dcompiler.dd
- spec/enum.dd
- spec/expression.dd
> Revive #1040 - spec/{enum,expression}.d + dcompiler.d

- posix.mak
- add different changelog target (pending against `upstream/master` vs. upcoming
release build against `upstream/stable`)
- generate the changelog/next-version, s.t. the file existence check can
be dropped
- move LOOSE_CHANGELOG_FILES to the individual targets
- document the changelog targets
- rename CHANGELOG_VERSION_LATEST to CHANGELOG_VERSION_STABLE
- fix whitespace indentation in the changelog documentation
@MartinNowak currently runs the `changed.d` without this Makefile:
https://gist.github.com/MartinNowak/a471fe7ddbfeef205cdf04c93a94c6d0#file-release-sh-L62
This won't allow us to include the contributor list, hence a separate target as for the release build a different upstream branch is used.
> Improve changelog targets

- contributors.dd
Based on @quickfur and Ketmar's ideas at http://forum.dlang.org/post/mailman.1080.1513627235.9493.digitalmars-d-announce@puremagic.com
`multicolumn` is part of CSS3 and quite [usable nowadays](https://caniuse.com/#search=multicolumn).
> Improve contributors listing

- glossary.dd
- spec/interface.dd
- spec/template.dd
> Revive #1040 - spec/{interface,template}.d + glossary.d

- posix.mak
The idea is to make it:
- easy to modify in case of future updates
- easy to spot and understand by contributors to see what's going on with DAutoTest
> Add special `dautotest` target

- posix.mak
Follow-up to https://github.com/dlang/dlang.org/pull/2031
See also: https://github.com/CyberShadow/ae/blob/bdc41d1669264104ae38c5919c9a1560d685c4f9/sys/d/manager.d#L1718
> Improve dautotest target

- posix.mak
After the refactoring of the Objective-C glue layer in the compiler the `objc_glue.d` file is now used by all platforms. See https://github.com/dlang/dmd/pull/7513 for reference.
> Remove `objc_glue.d` from the set of excluded files

- posix.mak
Required for https://github.com/dlang/dmd/pull/7513
> Fix DDox exclusion for ObjC

- .gitignore
- .htaccess
- appendices.html
- dcompiler.html
- debugger.html
- howtos.html
- language-reference.html
- posix.mak
Check for yourself:  https://dlang.org/dcompiler.html
__edit__: found a couple of more old files
>  Remove old & unused HTML files

- posix.mak
Depends on https://github.com/dlang/dmd/pull/7567.
Only after https://github.com/dlang/dmd/pull/7567 is in `stable`, we can fully
remove the `DMD_EXCLUDE` workaround.
> Start to remove platform-specific Ddox hacks

- download.dd
Continuation of https://github.com/dlang/dlang.org/pull/1697
> Download page info icon tweaks

- cpptod.dd
I thought it would be good to get this documented.
Details in the DLang forum post:
http://forum.dlang.org/post/vtltaepzruyhazxmacaf@forum.dlang.org
> cpptod to explain the differences between the usage of references in D & C++

- css/style.css
- index.dd
There needs to be an obvious call to action for donation on both the front page and on the foundation page if we want people to know about it. Currently, the only way people know about donating to the Foundation is if they happen to go to the Foundation's page.
> Added Donation Call to Action to the Front Page

- css/style.css
- index.dd
Before:
After:
CC @JackStouffer
> Use FA_ICONs for the front page

- css/style.css
> Fixed orgs using d on large screens

- dcompiler.dd
> [trivial]  Fix some dcompiler.dd formatting, add -dip1000 

- spec/struct.dd
Mostly a cut&paste job from https://github.com/dlang/dlang.org/pull/2096
> add Struct Invariant to spec

- spec/traits.dd
See https://github.com/dlang/dmd/pull/7569.
> document  possible new `isDisabled` __traits

- ddoc_preprocessor.d
- posix.mak
See also: https://github.com/dlang/dlang.org/pull/2101
> Use a better error message for the Ddoc preprocessor

- deprecate.dd
- spec/lex.dd
DMD PR: https://github.com/dlang/dmd/pull/7767
> Deprecate hexstrings

- spec/function.dd
Motivation: http://forum.dlang.org/post/p2o666$r4h$1@digitalmars.com
> clarify CTFE spec a bit

- spec/pragma.dd
Fix errors and gaps, identify implementation defined behavior and best practices.
> pragma.dd: clarify and tighten up spec

- spec/lex.dd
and removed a bunch of non-spec and non-lexical chatter.
> lex.dd: numerous small improvements

- index.dd
> Mention sponsors + contributors on the front page

- deprecate.dd
From https://github.com/dlang/dmd/pull/7813#discussion_r165006712
> "thanks" sounds a bit condescending.

- css/style.css
- index.dd
> Replace company links with their success stories + rename testimonials link to success stories

- changelog/changelog.ddoc
- changelog/update_nav.sh
Even though the page is generated for a while now, it's still rather unknown.
> Add nightly (aka pending) changelog to the changelog navigation menu

- js/run.js
First commit of https://github.com/dlang/dlang.org/pull/1981 without the controversial bit, s.t. the fix can be pulled immediately.
> Fix Issue 18306 - No compliation errors shown when running modified examples

- posix.mak
Maybe we should fix the Makefile to `/bin/bash` to avoid such issues?
edit: submitted https://github.com/dlang/dlang.org/pull/2181
> Use standard bash if instead of the shorthand

- posix.mak
This should hopefully fix our deployment issues.
> Remove outdated rm blog.html in posix.mak

- ddoc_preprocessor.d
I think this might address the issue with https://github.com/dlang/dmd/pull/7777 but I'm not 100% sure.
> Escape commas in option flag arguments

- spec/version.dd
See https://github.com/dlang/dmd/pull/7882 and https://issues.dlang.org/show_bug.cgi?id=18407 for discussion.
> Clarify behavior of debug statements

- spec/function.dd
See also: https://github.com/dlang/dmd/pull/7882
> Support @nogc in debug{} blocks

- dlang.org.ddoc
- foundation/index.dd
Maybe we have more luck next year...
> Remove GSoC 2018 from the Foundation page

- posix.mak
See https://github.com/dlang/dlang.org/pull/2213#discussion_r168968067
> Remove --only-tag from d-latest.tag

- css/style.css
> Remove text justification in table cells

- index.dd
Didn't view locally yet, because the build kept hanging in my Linux VM . I'll check the autotester link when it's ready.
> Add DConf submission deadline notice

- dlang.org.ddoc
s.t. people aren't confused that something is broken
> Show dummy content to the front page when run with DIFFABLE=1

- spec/module.dd
Reverts dlang/dlang.org#2131 - see also: https://github.com/dlang/dmd/pull/7939
> Revert "Update spec for multiple selective imports"

- css/style.css
- js/run_examples.js
Before:
After:
See also: https://github.com/dlang/dlang.org/pull/2239
> Add text: 'Open in IDE' to the Phobos run.dlang.io buttons

- changelog/pending.ddoc
- posix.mak
Follow-up to https://github.com/dlang/phobos/pull/6132#issuecomment-363557604
CC @schveiguy
> Add contributor hints and explanation of pending.dd

- spec/expression.dd
> add links for Integer Promotions and Usual Arithmetic Conversions

- spec/traits.dd
Implementation: https://github.com/dlang/dmd/pull/7908
> add __traits(isReturnOnStack, func)

- changelog/2.079.0.dd
- did not land in generated changelog as that is generated from stable
(see https://github.com/dlang/phobos/pull/6199 and https://github.com/dlang/phobos/pull/6226)
> pick changelog fixes from master

- spec/objc_interface.dd
The dlang.org part of https://github.com/dlang/dmd/pull/7762.
> Update the Objective-C documentation with support for class methods

- index.dd
- spec/betterc.dd
Saying TLS doesn't work with betterC has bothered me [ever since that page got added](https://github.com/dlang/dlang.org/pull/1796#discussion_r128740386), also took the opportunity to make other tweaks to that page and the front page.
> Tweak betterC and front page

- spec/expression.dd
Related recent change: https://github.com/dlang/dlang.org/pull/2132
> Improve function argument order spec.

- index.dd
This content is important for people and currently very hard to reach
and know about.
Preview:
> Add 'Run' + 'Explore' sections

- foundation/donate.dd
> Add OpenCollective + Smile donation buttons

- ddoc/source/preprocessor.d
Required for https://github.com/dlang/tools/pull/327
> Include pending.dd in the changelog footer generation

- foundation/sponsors.dd
> Add OpenCollective backers to foundation/sponsors

- dcompiler.dd
See also: https://dlang.org/changelog/2.079.0.html#osx-10_9
> Fix Issue 18603 - Update minimally required version for macOS

- deprecate.dd
Spec PR to accompany https://github.com/dlang/dmd/pull/8053
> Update deprecations page for removal of NCEG operators

- html.ddoc
From:
https://github.com/dlang/tools/pull/336#discussion_r176952807
CC @CyberShadow
> Add $(TAB) macro

- html.ddoc
Follow-up to https://github.com/dlang/dlang.org/pull/2296#discussion_r176956324
> Move $(TAB) to a better position in html.ddoc

- articles/faq.dd
> Fix Issue 18702 - FAQ item 'What does D have that C++ doesn't?' comparison link

- spec/struct.dd
Used the opportunity to add most of this file to the spec tester.
> Fix Issue 18747 - [Structs, Unions] example is invalid

- rdmd.dd
- use proper syntax highlighing
- use the fancy CONSOLE macro
- use a message box for the instructions for Windows
> Modernize rdmd's synopsis

- download.dd
s.t. it's easy to check whether the project is still alive and up-to-date.
It's also often nice to have a convenient way to reach the maintainer or learn more about the project.
> download.dd: Add link to OpenSUSE's + Homebrew's project page

- spec/struct.dd
It was woefully incomplete. Copied a bunch from the recent class construction spec.
> rewrite struct constructor section

- spec/enum.dd
Spec update to accompany https://github.com/dlang/dmd/pull/8404
> Add enum member attributes to the spec

- spec/class.dd
See : https://github.com/dlang/dmd/pull/8331
> Fix Issue 17580 - Marking methods as synchronized is allowed despite spec

- posix.mak
Required for https://github.com/dlang/dmd/pull/8442
> Include interface files in the DDox build

- js/listanchors.js
Would be great to integrate this into the release process somehow, but for now it still depends on me manually building the docs :/
> Bump currently archived version to v2.081.0

- ddoc/dub.sdl
- ddoc/dub.selections.json
- dpl-docs/dub.json
- dpl-docs/dub.selections.json
- apparently resolves conflict between libdparse 0.7.2-alpha.4 and ~>0.8
> upgrade dependencies to fix build

- articles/code_coverage.dd
- articles/ctarguments.dd
- articles/exception-safe.dd
- articles/faq.dd
- articles/migrate-to-shared.dd
- articles/mixin.dd
- articles/pretod.dd
- articles/regular-expression.dd
- articles/template-comparison.dd
- articles/templates-revisited.dd
fixes issue 19067 - [Mixins] Dead Link to template-mixin
> fix various broken links in articles

- CONTRIBUTING.md
From https://github.com/dlang/dlang.org/pull/2367#issuecomment-389071811
> Mention how to build the documentation with the distro-wide dmd

- spec/function.dd
> remove overlooked diff markers

- orgs-using-d.dd
(also adapted the layout of the links of SARC while I was at it)
Preview:
CC @Laeeth
> Update Organizations using D for Symmetry

- spec/function.dd
Inspired by @schveiguy's [forum post](https://forum.dlang.org/post/pjuq6s$1lf0$1@digitalmars.com).
> Explain why a Lazy Variadic Delegate is better than a Lazy Variadic Array

- spec/function.dd
* Add two sub-headings for better Table of Contents.
* Be more precise about lazy parameters.
* Add link from lazy params to lazy variadics.
> [function.dd] Improve Lazy Parameters section

- spec/expression.dd
Depends on https://github.com/dlang/dmd/pull/8237.
> Issue 18743 - ConditionalExpression with AssignExpression requires parens

- posix.mak
Not sure if this helps anything, but trying to dig to root of https://github.com/dlang/dmd/pull/8519#issuecomment-408674418.
> Bump stable DUB/DMD

- spec/pragma.dd
For https://github.com/dlang/dmd/pull/8654
> Add pragma(linkerdirective, "") to spec.

- spec/traits.dd
This is the companion of https://github.com/dlang/dmd/pull/8583
> Update spec for Issue 19180 - Expose... __traits(isZeroInit, T)

- spec/traits.dd
For https://github.com/dlang/dmd/pull/8724
> Spec for __traits(getTargetInfo)

- spec/contracts.dd
Fix documentation to match the recent dstyle clarification.
> adjust contracts documentation examples to match dstyle

- changelog/2.083.0_pre.dd
https://forum.dlang.org/post/osxjfludeknpcphxjvzi@forum.dlang.org
https://forum.dlang.org/post/shmmwojvtvuiinnoqjye@forum.dlang.org
> Add changelog clarifications from forum

- changelog/prerelease.ddoc
(done from my phone, but should be simple enough)
See also:
https://github.com/dlang/dlang.org/pull/2493
> Add edit buttons for the changelog entries to the prerelease changelog

- posix.mak
Maybe https://github.com/dlang/dub/pull/1513 (reimplementation of the dependency resolution) helps to fix the current failure.
> Bump the host compiler to 2.082.1

- posix.mak
- also see https://github.com/dlang/dlang.org/pull/2497
> use newer host compiler to workaround dub regression

- spec/declaration.dd
DMD pull request : https://github.com/dlang/dmd/pull/8938.
> Update grammar for enhancement 7804

- spec/struct.dd
See: https://github.com/dlang/dmd/pull/8098
> Spec change for Issue 18474

- spec/function.dd
The next paragraph already says the same thing.
> Remove duplicate paragraph for pure fuctions

- spec/traits.dd
Companion PR to https://github.com/dlang/dmd/pull/9016
> Update getAliasThis documentation per issue 19439

- install.dd
See also: https://github.com/dlang/installer/pull/282
> Add ldc-latest-ci to the install script information

- spec/module.dd
> Fix syntax formatting

- spec/class.dd
- spec/objc_interface.dd
This is the spec update for https://github.com/dlang/dmd/pull/9226.
> Add documentation for Objective-C instance variables

- foundation/sponsors.dd
* Reorder sponsors list based on current donation amounts
* Put OpenCollective script at the top. Looks odd at the bottom.
* Minor edits.
> Refactor sponsors page.

- spec/struct.dd
As per le DIP [1].
[1] https://github.com/dlang/DIPs/blob/master/DIPs/DIP1018.md
> Update struct.dd to highlight copy constructor addition

- spec/expression.dd
> Define rvalues and lvalues

- spec/class.dd
See https://github.com/dlang/dmd/pull/9289
> Update spec for Issue 16657 and 11161

- deprecate.dd
Documentation update to accompany https://github.com/dlang/dmd/pull/9549
> Advance deprecation of hex string literals (Error)

- spec/expression.dd
> Optional ref in function literals

- spec/hash-map.dd
Added a note to the doc saying that the feature is not yet implemented.
> Static Initialization of AAs is not yet implemented, yet it is in the spec!

- spec/garbage.dd
doc for https://github.com/dlang/druntime/pull/2514
> add documentation for parallel marking by the GC

- spec/declaration.dd
This is the documentation part of https://github.com/dlang/dmd/pull/9667.
> Add AliasDeclarationY rule for the function types

- spec/struct.dd
> Add a paragraph about default construction

- deprecate.dd
Spec change to accompany https://github.com/dlang/dmd/pull/9786
> Advance deprecation of class allocators and deallocators: Removal

- spec/struct.dd
Reverts dlang/dlang.org#2642
See: https://github.com/dlang/dlang.org/pull/2642#issuecomment-492585252
> Revert "Add a paragraph about default construction"

- spec/cpp_interface.dd
Based on n.g. discussion:
https://digitalmars.com/d/archives/digitalmars/D/Can_we_just_have_struct_inheritence_already_327900.html#N327900
https://digitalmars.com/d/archives/digitalmars/D/Can_we_just_have_struct_inheritence_already_327900.html#N328393
> add struct guide to C++ empty base optimization

- orgs-using-d.dd
> Correct AID hiring link

- spec/traits.dd
for https://github.com/dlang/dmd/pull/10013
> add `__traits(getLocation, symbol)`

- spec/operatoroverloading.dd
Spec update for https://github.com/dlang/dmd/pull/10130
> Deprecate D1 operator overloads

- spec/declaration.dd
- spec/type.dd
Implementation: https://github.com/dlang/dmd/pull/10215
> fix Issue 20053 - add mixin types

- download.dd
Got from https://d-apt.sourceforge.io/. Seems that commands on the main page never worked.
> Fix Ubuntu repo setup

- spec/function.dd
Should be merged after dmd PR: https://github.com/dlang/dmd/pull/10264
> Spec change for Issue 809

- deprecate.dd
> Add 'body' to the list of deprecated features

- spec/intro.dd
> add Memory Model and Object Model

- install.dd
See: https://github.com/dlang/installer/pull/409
> install: Update list of supported platforms

- js/run.js
> Fix Issue 20500 - always pass -unittest and --DRT-testmode=run-main

- spec/interfaceToC.dd
Fix bug noted here https://github.com/dlang/dlang.org/pull/2760#discussion_r384503887
> interfaceToC: fix format string

- changelog/2.091.1_pre.dd
- download.dd
- update download and changelog for v2.091.1-beta.1
> merge stable

- orgs-using-d.dd
It no longer exists and the company that bought it no longer works in D.
> Remove sociomantic from "orgs using D"

- spec/abi.dd
See also https://github.com/dlang/dmd/pull/11049
> Spec: Add FuncAttrLive

- spec/abi.dd
> Fix FuncAttrLive

- spec/pragma.dd
Add spec for series of PRs implementing it ending with:
https://github.com/dlang/dmd/pull/11043
> document pragma(printf) and pragma(scanf)

- download.dd
Updated Homebrew DMD download link
> Updated Homebrew formula link

- spec/ob.dd
- spec/spec.dd
Since it's in the compiler, it needs documentation.
> Add documentation for @live functions

- install.dd
To go with https://github.com/dlang/installer/pull/454.
> Documenting usage on Windows.

- spec/function.dd
This is based on Walter's #2768, but I got carried away so this heavily remixes and expands the original.
The goal here is being able to tell exactly what `@safe` and `@trusted` functions can
assume on their inputs and what they must ensure for their outputs.
@WalterBright, you probably want to have a look.
@dkorpel, as the author of the upcoming [DIP on `@system` variables](https://github.com/dlang/DIPs/pull/179) you might be interested.
> safe interfaces, safe values, safe aliasing

- README.md
(Edited): The issuestats service is no longer up.
> Remove issuestats badge

- spec/class.dd
- spec/template.dd
* Add subheadings for easier browsing.
* Tweak wording.
* Fix some typos.
* Add example for anonymous classes.
* Add link to nested class instantiation from implicit template nesting docs.
> Improve Nested Classes section

- spec/version.dd
Fix identifier capitalization, make example interactive, fix typo.
> [trivial] [spec/version.dd] Tweak Static If section

- spec/intro.dd
Minor edits for readability, punctuation, etc.
> Revision pass on intro page

- spec/template.dd
Add various useful links.
Mention enum templates in variable templates heading.
Use `static if` for factorial template example & make interactive.
> [spec/template.dd] Add see also links & tweaks

- spec/template.dd
> Identify template this functions detect mutability

- spec/traits.dd
See https://github.com/dlang/dmd/pull/11442
> add __traits(child, parent, member)

- posix.mak
- spec/ddoc.dd
> Remove deprecated preview=markdown & adapt documentation

- install.dd
Add documentation for:
- `get-path` - https://github.com/dlang/installer/pull/297
- `,dub` - https://github.com/dlang/installer/pull/301
> install.sh: document get-path and ,dub

- spec/class.dd
> Remove multiple aliasThis mention

- spec/type.dd
Spec update of https://github.com/dlang/dmd/pull/11610/.
> Add conversions of base class to derived class (arrays)

- download.dd
Add a 'Leave a Tip' link on the download page that's large enough to grab attention.
> Add donation link to download page.

- index.dd
I'm trying to think like a complete newbie. 
I think we often forget that some people actually come to D as a first language.
1. tee = Perform a transparent operation
2. walkLength = optimized version of length
3. byLine = Get an input range set up to read one line at a time
> Show comments on code example

- spec/traits.dd
see https://github.com/dlang/dmd/pull/11863 for the corresponding dmd PR
> Spec PR for `__traits(getCppNamespaces, sym)`

- spec/pragma.dd
https://github.com/dlang/dmd/pull/11967
> spec change for issue 21378 - Allow `pragma(inline, knownAtCTFE);`

- orgs-using-d.dd
I work as a consultant for Symmetry, and am submitting this change at the request of Laeeth (senior partner)
> Update Symmetry hiring link in orgs-using-d

- ddoc/source/preprocessor.d
Required for https://github.com/dlang/dmd/pull/12005
> Fix casing/spelling of TargetOS

- spec/errors.dd
- spec/function.dd
- spec/statement.dd
> add links to Error class

- spec/function.dd
> improve ref function documentation

- spec/function.dd
1. add hyperlinks
2. fix misspelled hyperlink
3. simplify prose
4. make code examples correct code
5. improve examples
6. add required `va_end`
> improve C-style Variadic Functions section

- spec/attribute.dd
- spec/interface.dd
- spec/objc_interface.dd
Corresponding DMD PR: https://github.com/dlang/dmd/pull/11821.
> Add documentation for Objective-C interfaces

- spec/simd.dd
Implementation: https://github.com/dlang/dmd/pull/12045
> fix Issue 10445 - add .min, .max, etc. properties for vector types

- spec/expression.dd
Missing documentation on existing behavior.
> add paragraph on casting static arrays

- spec/function.dd
Use fewer words and more pedantic language.
> improve Function Inheritance and Overriding section

- spec/function.dd
> Improve D-style Variadic Functions section

- spec/function.dd
Better explanation, more comprehensive example.
> fix Lazy Variadic Functions section

- spec/function.dd
Add missing information, add more cases to example, fix turgid prose.
> fix Local Variables section

- spec/function.dd
Corrected some confusion about what a delegate could be initialized with.
> Improve Delegates, Function Pointers, and Closures section

- spec/function.dd
Clarify text, have example code refer to numbered list.
> redo No-GC Functions section

- spec/function.dd
Just give it some good polishing.
> Improve Uniform Function Call Syntax section

- spec/traits.dd
> Introduce getVisibility as replacement to getProtection

- download.dd
- js/platform-downloads.js
Fix a couple issues with https://github.com/dlang/dlang.org/pull/2933
CC @schveiguy
> Correct download links to download years

- spec/struct.dd
To match: https://github.com/dlang/dmd/pull/12140
> Update struct posbtblit/copy constructor cohabitation section

- ebook.ddoc
- spec/function.dd
Document its improved capability.
> redo Function Attribute Inference section

- spec/contracts.dd
> improve contracts introduction

- spec/expression.dd
- spec/lex.dd
---
CC: @maxhaton 
Related to https://github.com/dlang/dmd/pull/12252.
> spec: add `__MANGLED_FUNCTION__` special keyword

- spec/interface.dd
"you" should be banished from reference material.
> interface.dd: improve COM section

- spec/interface.dd
- spec/type.dd
This is just a first pass at improving this page. It is a very aged file little changed since D started.
1. add useful links
2. spit arrays into static arrays and dynamic arrays
3. add missing interfaces
4. remove redundant enum section
5. better explanation of void and real types
6. move string exposition to where other alias types are
> type: mostly fix up links

- spec/type.dd
Also fix wrong monospaced mixin types heading.
> spec: Tweak typeof docs

- spec/statement.dd
PR: https://github.com/dlang/dmd/pull/12246
> Spec change for Issue 16140

- glossary.dd
- spec/template.dd
Add some see also links.
Fix capitalization of Square, Foo.
Add IFTI sub-section; move up paragraph about order of parameters.
Add some sub-headings for easier browsing.
> [spec/template.dd] Improve Function Templates section

- spec/traits.dd
Spec pull request for https://github.com/dlang/dmd/pull/12156
> fix Issue 21585 - add __traits(totype, string)

- index.dd
pragma(msg, ) can do that instead.
> index.dd: avoid using std.conv.text

- spec/expression.dd
- spec/module.dd
> dot identifier

- spec/abi.dd
Corresponding DMD change dlang/dmd#12340
> abi: add mangling for issue 21753

- spec/declaration.dd
- spec/function.dd
See https://github.com/dlang/dmd/pull/12326 and https://issues.dlang.org/show_bug.cgi?id=21665
> add @safe restrictions on types with invariants

- spec/lex.dd
- improve the flow
- make it a little more formal
- correct grammar/punctuation
> Revise the first few paras of lex.dd

- foundation/donate.dd
Corrected the grammar and made it sound a little less awkward.
> fix wording of first sentence in foundation donation paragraph

- changelog/release-schedule.dd
> Update year on release schedule page

- posix.mak
- spec/betterc.dd
- spec/importc.dd
- spec/ob.dd
- spec/spec.dd
- spec/spec.ddoc
This is the boilerplate for adding the documentation file for ImportC.
> initial commit for importc.d

- spec/importc.dd
This adds enough of an outline that PRs for improvements can be done in parallel without needing to constantly rebase.
> ImportC: add an outline

- spec/importc.dd
> ImportC: fix some typo errors

- spec/importc.dd
> ImportC: add LNAME2 to H3

- spec/importc.dd
Copied from the changelog for ImportC.
> ImportC: add Other Solutions section

- spec/importc.dd
> ImportC: add more to limitations section

- spec/betterc.dd
- spec/importc.dd
> explain difference between ImportC and BetterC

- spec/statement.dd
spec changes corresponding to https://github.com/dlang/dmd/pull/12912
> add scope to foreach iteration symbols

- spec/statement.dd
Clarify what switch expressions are accepted, and when integral promotions on it are done. This documents existing behavior.
> switch expression and integral promotions

- spec/statement.dd
In response to @andralex 's comments on https://github.com/dlang/dlang.org/pull/3073
> minor edits to #3703

- spec/importc.dd
Add section on C11 _Generic selection_.
> ImportC: _Generic

- spec/traits.dd
The traits was upstreamed from LDC in dlang/dmd#13298
> Add  __traits(initSymbol) to the spec

- index.dd
> Dconf is over

- spec/function.dd
---
See 3. point in https://dlang.org/spec/function.html#variadic
> spec/function: fix typesafe_variadic_functions hyperlink

- spec/importc.dd
- spec/type.dd
See also: https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1034.md
> [spec] Document `noreturn`

- spec/importc.dd
Document https://github.com/dlang/dmd/pull/13561
> ImportC: add EnumBaseType to enums

- spec/template-mixin.dd
Add 3 links to template.html.
Fix: templated nested functions are often possible.
Use writeln instead of writefln.
Tweak Duff's device example.
> [spec/template-mixin.dd] Tweak examples & make them runnable

- spec/importc.dd
The implementation: https://github.com/dlang/dmd/pull/13539
> ImportC: add documentation for __import

- book/build.d
Insert a custom macro to override the timestamp with a placeholder text. This is already implemented for the HTML files s.t. DAutoTest can provide a proper diff without unrelated changes.
> book: Remove timestamps when building with DIFFABLE=1

- spec/template.dd
Add *Template Instantiation* heading:
Add description, mention IFTI.
Make *Explicit Instantiation* a subheading.
Add *Common Instantiation* subheading.
Make *Instantiation Scope* a subheading & fix example formatting.
> [spec/template.dd] Improve template instantiation docs

- spec/pragma.dd
> spec: pragma: fix ctr_destructor documentation

- spec/traits.dd
> [spec/traits.dd] Fix wrong uses of 'tuple'

- spec/version.dd
Signed-off-by: João Lourenço <jlourenco5691@gmail.com>
Spec for: https://github.com/dlang/dmd/pull/13048
> Add Contracts versions

- spec/pragma.dd
see https://github.com/dlang/dmd/pull/11835
> Allow `pragma(mangle,...)` on an aggregate

- deprecate.dd
- spec/lex.dd
See https://github.com/dlang/dmd/pull/12244/
> Deprecate body keyword

- deprecate.dd
See https://github.com/dlang/dmd/pull/13666
> set error and removal date for delete’s deprecation

- .circleci/run.sh
- download.dd
The new release wasn't found because of wrong year
> Update release year found in download link

- spec/traits.dd
Implementation PR: https://github.com/dlang/dmd/pull/13071
> Add __traits(parameters) to language spec

- spec/version.dd
Related to: https://github.com/dlang/dmd/pull/13896
> Add version condition invariants

- spec/arrays.dd
> Spec changes for static array .tupleof

- dstyle.dd
@atilaneves 
This came up in https://github.com/dlang/phobos/pull/8410#discussion_r826115306
I wrote down what I think is the norm in dmd, Phobos, druntime, and the spec. Style is very subjective, so this initial description deliberately does not go into too much detail to prevent nailing it down too hard.
> Add UFCS to style guide

- spec/attribute.dd
DIP: <https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1038.md>
DMD PR: dlang/dmd#13589.
> Add @mustuse (DIP 1038) to the language spec

- spec/attribute.dd
- spec/struct.dd
Refine link to disabled default constructor.
Add anchor for disabled copy constructor & example.
> [spec] Improve @disable docs

- spec/function.dd
Assumes the changes of: https://github.com/dlang/dmd/pull/13993
> Document `scope` inference from `pure`

- spec/importc.dd
> Document ImportC support for typeof operator

- spec/function.dd
Discussion in comments to https://github.com/dlang/dmd/pull/12817
> clarify return-ref combined with scope parameters

- book/d.en/memory.d
- spec/garbage.dd
- spec/pragma.dd
- spec/traits.dd
For https://github.com/dlang/dmd/pull/14063.
> Add __traits(classInstanceAlignment)

- spec/arrays.dd
- spec/const3.dd
- spec/declaration.dd
- spec/function.dd
- spec/lex.dd
- spec/statement.dd
> minor changes to undefined behavior notes

- spec/attribute.dd
Make example runnable & use asserts.
> [spec/attribute] Use static data in example

- spec/struct.dd
Show how to instantiate a struct and copy it.
Document `new` on a struct.
List kinds of member declarations:
Link to methods, static fields/methods, operator overloading & alias this.
> [spec/struct] Improve introduction section

- book/contextMacros.ddoc
- index.dd
Some of the companies in the "Industry Proven" list aren't around or aren't using D anymore. This updates the list with our biggest sponsor and two other companies that have been using and contributing a long time.
> Update org list on main page

- spec/abi.dd
https://github.com/dlang/dmd/pull/14233
> Update return scope mangling spec

- spec/function.dd
Note: Dmd allow to put contracts on main function. If this should be rejected, I’ll update the spec accordingly
> Specs: Change D Main Function to allow contracts and shortened methods

- spec/traits.dd
This came up on Discord
https://discord.com/channels/242094594181955585/811702037532115015/983457413808144446
> Fix isModule example

- spec/importc.dd
to reflect the greatly increased preprocessor support in ImportC.
> expand on preprocessor section

- spec/importc.dd
The idea to show a working example of ImportC as soon as possible.
> ImportC: add quick examples

- posix.mak
Fixes build script paths to work with new merged dmd-druntime repository
See https://github.com/dlang/projects/issues/92
> [project] Merge druntime into the dmd repository

- spec/importc.dd
Every time I read it I see things that need improvement.
> adjustments to ImportC documentation

- spec/hash-map.dd
Update example to match part of https://github.com/dlang/dmd/pull/14335.
Add link to object.update.
> Fix Issue 22237 - AA.update is underspecified

- spec/hash-map.dd
Add Examples heading otherwise they're listed under Properties.
Make example get compiled.
Add missing import.
> Fix AA word count example

- spec/type.dd
Add Grammar heading for navigation.
Use list instead of paragraph.
Fix two anchor links.
> [spec/type] Tweak introduction

- articles/const-faq.dd
Dr Dobbs site appears to be kinda broken.
> Fix link to “Invariant Strings” article

- spec/expression.dd
List function name or ref function call separately from dot operator.
Add links.
> [spec/expression] Improve Lvalue section

- spec/expression.dd
Make more examples runnable.
Use `static assert` where possible.
> [spec/expression] Tweak examples

- spec/function.dd
Gradually iterating into something clean.
> fix formatting mistake

- spec/struct.dd
Add simple Dynamic Initialization of Unions section.
Add paragraph defining an anonymous struct/union.
> [spec/struct] Improve union init & anonymous docs

- spec/abi.dd
- spec/type.dd
> Fix 23186 - wchar/dchar do not have their endianess defined

- spec/class.dd
> [spec/class] Tweak alias this docs

- spec/expression.dd
Bugzilla: https://issues.dlang.org/show_bug.cgi?id=21243
DMD PR: https://github.com/dlang/dmd/pull/14454
> Allow lambdas to return auto ref

- spec/function.dd
Use list for inferred attributes.
> [trivial] [spec/function] Tweak attribute inference docs

- spec/version.dd
For https://github.com/dlang/dmd/pull/14245.
> spec: Add predefined version D_Optimized

- spec/declaration.dd
Make template example runnable.
Add import link.
Add static import for function alias example.
> [spec] List symbols which can be aliased

- spec/operatoroverloading.dd
Show post-increment lowering to opUnary.
Explain opIndexUnary indexing and slicing, add examples.
> Improve opUnary docs

- spec/enum.dd
Also remove noisy unnecessary AssignExpression links.
> Fix Issue 23511 - Incrementing a not supported type in enum

- tools/dspec_tester.d
https://issues.dlang.org/show_bug.cgi?id=15129 strikes again (like https://github.com/dlang/dmd/pull/14817).
> Fix possible data race with runnable example tester

- spec/importc.dd
See https://forum.dlang.org/post/uqllydlolryuzhkcghro@forum.dlang.org
> Fix ImportC square example

- spec/arrays.dd
I simply added the information specified.
> Fix Issue 18765: - [Arrays] Docs need info on initialization of static array with element literal

- spec/module.dd
Signed-off-by: Robert Grancsa <robert.grancsa2002@gmail.com>
> Fixed issue 22348 - Specify forward referencing of MixinDeclaration

- spec/type.dd
Signed-off-by: Matei Hriscu <matei.hriscu@proton.me>
> Fix issue 11493 - Correctly explain code snippet behaviour

- spec/template.dd
Fixed an issue that seemed to be resolved and changed the names to match
> Fix issue 16707

- download.dd
old link was dead / the site shut down
See discussion on https://github.com/dlang/dub/pull/2592#issuecomment-1427876293
> Update OpenBSD download link

- dpl-docs/views/layout.dt
See https://forum.dlang.org/thread/nbhumgijyvtdipkydxql@forum.dlang.org
> Fix druntime/dmd "Edit this Page" paths

- spec/attribute.dd
For https://github.com/dlang/dmd/pull/14881
> Allow TemplateSingleArgument on UDA

- spec/statement.dd
Add links.
Add 2 runnable examples with output shown.
Add labelled break/continue examples.
Tweak wording.
> [spec] Improve break and continue docs

- spec/expression.dd
Needed for https://github.com/dlang/dmd/pull/15053. After merging that, it will be an error.
> IsExpression: comment out alias template instance with parameters

- spec/hash-map.dd
wasn't able to build, since the makefile seems to be broken nowadays, so just trusting ye old CI here.
See https://forum.dlang.org/thread/kqfkzghjoyruzgbsvmje@forum.dlang.org
> make AA "Not yet Implemented" note better

- spec/traits.dd
Try to clear away the fog over precisely what these traits mean.
> clarify what isIntegral, isScalar, etc. __traits mean

- spec/statement.dd
document https://github.com/dlang/dmd/pull/15131
> with statement now does enum expressions

- dlang.org.ddoc
- spec/importc.dd
- spec/windows.dd
Should use this term more often.
> add ACC macro for Associated C Compiler

- spec/lex.dd
https://github.com/dlang/dmd/pull/15002#issuecomment-1499339001
> Remove # from tokens

- spec/declaration.dd
- spec/function.dd
Minor tweaks.
Add link to function type aliases.
> [spec] Tweak docs on default arguments

- spec/ob.dd
Bartosz proposed an ownership system for D back in 2009.
> Link to Bartosz Milewski's blog

- spec/class.dd
- spec/template-mixin.dd
...which can be confusing because of mixin templates
> Fix Issue 23946 - spec states "there can only be one destructor"

- articles/dll-windows.dd
Lots of useful recommendations I didn't know about.
> add reference to DLL best practices

- spec/expression.dd
Documentation for when https://github.com/dlang/dmd/pull/14706 is merged.
> [spec] Disallow throwing qualified objects

- spec/glossary.dd
- spec/legacy.dd
- spec/spec.dd
- spec/spec.ddoc
Create the spec page where legacy code support will be documented.
> add spec/legacy page

- spec/enum.dd
> [spec/enum] Tweak grammar

- spec/class.dd
Move *Super Class* section above *Fields*, which has an example using inheritance.
Add simple example.
Add note about multiple inheritance/interfaces.
> [spec/class] Improve super class docs

- articles/template-comparison.dd
A couple of (long overdue) updates to C++/D Template Comparison.
> Updates to Template Comparison page

- spec/hash-map.dd
https://github.com/dlang/dmd/pull/15468
> Remove note about static initialization of AAs

- dcompiler.dd
Changes to documentation to include changes in dlang/dmd#15648
> Update documentation about config load oder on posix systems; see dlang/dmd#15648

- index.dd
It's not displaying anything since months
> Remove the X widget

- spec/template.dd
> [spec] Improve variable template examples

- spec/declaration.dd
Follow up to [#3707](https://github.com/dlang/dlang.org/pull/3707#discussion_r1376545170).
@dkorpel
> Mention C 'spiral rule', not 'right-left rule'

- spec/declaration.dd
- spec/function.dd
See https://github.com/dlang/dmd/pull/15362
> Specify safe values for `bool`

- orgs-using-d.dd
> Fix syntax mistake

- spec/expression.dd
- spec/struct.dd
Some mistakes I noticed when inspecting the rendered output of https://github.com/dlang/dlang.org/pull/3744
> Fix named argument documentation

- spec/importc.dd
> document ImportC to D source translation

- spec/attribute.dd
- spec/function.dd
Taken from:
https://dlang.org/changelog/2.102.0.html#dmd.system-variables
> [spec/attribute] Document @system variables

- spec/statement.dd
Update for https://github.com/dlang/dmd/pull/16418.
> [spec] `foreach_reverse` with a delegate is an error

- ddoc/source/assert_writeln_magic.d
Similar to https://github.com/dlang/tools/pull/471
> assert_writeln_magic.d: Upgrade libdparse

- changelog/2.082.0.dd
- changelog/2.095.0.dd
- changelog/2.097.0.dd
- index.dd
- spec/cpp_interface.dd
- spec/importc.dd
I have committed the fix but have not built to verify.
> Fix some invalid links

- spec/module.dd
> [spec] Improve module scope operator example

- spec/legacy.dd
Next edition error added here: https://github.com/dlang/dmd/pull/15863.
> [spec/legacy] Add entry for aliasing an instance member

- spec/statement.dd
State that using only one variable will make it a value sequence.
Use finite range.
> [spec] Improve foreach on a tuple range docs

- spec/function.dd
Add links.
Rename subheading.
Mention linkage.
Mention `.di` files.
> [spec/function] Improve prototype docs

- spec/expression.dd
Conversion to bool - follows on from #3830.
Also add link from casting basic types to casting integers.
> [spec/expression] Add links

- spec/expression.dd
For https://github.com/dlang/dmd/pull/16638
> Treat import("file") as hex string literal

- spec/glossary.dd
Add anchors.
Fix term capitalization.
Add IES - Interpolated Expression Sequence.
Tweak formatting of link to std.range.
Add local link to higher-order functions.
> [spec/glossary] Minor tweaks, add IES

- spec/function.dd
See this test: https://github.com/dlang/dmd/blob/83adb8aeab12ef7902eefae81223fdd300cfc1e0/compiler/test/runnable/testv.d#L63
> Allow variadic parameters with default in grammar

- spec/hash-map.dd
See https://dlang.org/changelog/2.101.0.html#dmd.new-aa.
Add example under *Construction and Reference Semantics*.
> [spec/hash-map] Document `new AA`

- spec/template-mixin.dd
For https://github.com/dlang/dmd/pull/16387.
> [spec] TemplateMixin assignment grammar

- articles/faq.dd
Add link to const(FAQ) and remove related questions. (Like those, there are still 4 other D 2.0 items which don't seem to be answered).
Move wiki link to top list.
Use RUNNABLE_EXAMPLE.
Fix typo.
> [articles/faq] Tweaks

- spec/type.dd
> [spec/type] Add example for derived types

- spec/expression.dd
- spec/function.dd
Add example.
Add rationale for halt.
> [spec/expression] Improve `assert(0)` docs

- spec/grammar.dd
> [spec/grammar] Add overview

- spec/traits.dd
Spec for https://github.com/dlang/dmd/pull/17043
> add __traits getBitfieldOffset and getBitfieldWidth

- spec/traits.dd
I'm not 100% certain I got this right, if I haven't let me know what to fix.
> Add new trait isCOMClass

- spec/traits.dd
Implementation: https://github.com/dlang/dmd/pull/20615
> Add __traits(hasMoveConstructor, type)

- spec/attribute.dd
for https://github.com/dlang/dmd/pull/20589
> [spec/attribute.dd] Add `align(default)`

- book/dlang.org.ddoc
- dlang.org.ddoc
- std_consolidated.ddoc
Following https://github.com/dlang/dmd/pull/20665
> Remove SAMPLESRC macro

- spec/function.dd
This addition explains a very powerful feature of D in a digestible manor for people coming from other programming languages.
> Give examples of UFCS in other languages

- spec/attribute.dd
- spec/expression.dd
Can someone please just confirm my links are correct? It wasn't super obvious how to declare a link target.
> Added __rvalue function attribute to the spec

- spec/betterc.dd
Inspired by Tsoding's recent D stream where he couldn't find a quick definition: https://youtu.be/Gj5310KnUTQ&t=286
> Add one line definition for betterC

- spec/class.dd
Add Overview, Declarations headings.
Make Access Control, Super Class, Fields subheadings of Declarations.
Group static ctor/dtors under a common heading.
> [spec/class] Improve TOC

- articles/ctod.dd
The runnable example added yesterday unfortunately did not work. Changed the code so that it actually works. Added also another features of an interpolated string.  I noticed during Tsoding's stream and also from personal experience, that discovering features often happen by looking for something else.
> Make the runnable example actually work

- articles/cpptod.dd
Also demonstrate field access of struct pointer (last example).
Note: #4203 should probably be merged first, to ensure the tests work.
> [articles/cpptod] Make some examples runnable

- spec/expression.dd
Use Markdown list for different type behaviour.
Clarify that pointers must have a common type.
Clarify that array elements must have a common type.
Add example.
> [spec/expression] Improve EqualExpression docs

- spec/expression.dd
- spec/struct.dd
> [spec/expression] Add struct equality example

- areas-of-d-usage.dd
Small PR - Resolves a few broken GitHub repo sources in `areas-of-d-usage.dd`. Relevant page: https://dlang.org/areas-of-d-usage.html
> Resolve broken GitHub repo sources

- spec/class.dd
Describe a constructor.
~~Change~~ Extend example to show member variable is in scope.
`return;` can be used.
> [spec/class] Improve constructor docs

- spec/class.dd
Add Restrictions heading.
Add example of multiple calls without loop.
> [spec/class] List base construction call restrictions too

- articles/d-array-article.dd
Also add link to `isOutputRange`.
> [articles/d-array-article] Make most examples runnable

- spec/expression.dd
Use GRAMMAR_INLINE macro.
Use a list for different kinds of base expression. 
Add link to pointers.
> [spec/expression] Tweak Slicing formatting

- spec/attribute.dd
For https://github.com/dlang/dmd/pull/21796
> Improve parameter UDA spec

- dlang.org.ddoc
Under *Community* submenu.
Fixes #4305.
> Add link to store in top menu
